### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by cculma** [ConesaLab/SQANTI3#1]
Hi, I was running SQANTI3 but it shows me this message: No such file or directory: ### `FileNotFoundError: [Errno 2] No such file or directory: '/home/hawkins/Documents/Cesar/RNA/globus/lordec_reports/sqanti3/refAnnotation_sqanti_LID50568_1001.genePred'`

Do you know what could be wrong?

Best,

Cesar

**Comment by FJPardoPalacios** [comment]
Hi Cesar,

Could you give me more information about how did you run SQANTI3?
It seems to be a problem with some path, can you check them?

Fran

**Comment by cculma** [comment]
Hi, I am running the bed resulting of TAMA collapse as follow:

`python ../../../Iso_assay/tama/tama/tama_go/format_converter/tama_convert_bed_gtf_ensembl_orf_nmd.py blastp_LID50568_1001_3_1.bed blastp_LID50568_1001_3_1.gtf`

And then I am using the gtf file as input to run SQANTI3:

```
python ../../../Iso_assay/sqanti2/SQANTI3/sqanti3_qc.py \
-x /home/hawkins/Documents/Cesar/NGSEP/ngsep_tutorial/Ms_Chen/Ms/Ms \
-e /home/hawkins/Documents/Cesar/RNA/globus/lordec_reports/rna_seq/kallisto_LID50568_1001/abundance.tsv \
-c /home/hawkins/Documents/Cesar/RNA/globus/lordec_reports/star_Ms/SJ.out_LID50568_1001.tab \
-d /home/hawkins/Documents/Cesar/RNA/globus/lordec_reports/sqanti3 \
-t 12 \
-o sqanti_LID50568_1001 \
-g no_cap_Ms_LID50568_1001.gtf \
/home/hawkins/Documents/Cesar/NGSEP/ngsep_tutorial/Ms_Chen/final.all.gene.gff \
/home/hawkins/Documents/Cesar/NGSEP/ngsep_tutorial/Ms_Chen/final.all.fasta 
```

I followed all the tutorial installation, step by step, and additionally, if I used the file resulting from collapse with cupcake, `cupcake.gff` it works fine with `sqanti1`. 

Best,

Cesar

**Comment by veravelasco** [comment]
> Hi, I was running SQANTI3 but it shows me this message: No such file or directory: ### `FileNotFoundError: [Errno 2] No such file or directory: '/home/hawkins/Documents/Cesar/RNA/globus/lordec_reports/sqanti3/refAnnotation_sqanti_LID50568_1001.genePred'`
> 
> Do you know what could be wrong?
> 
> Best,
> 
> Cesar

Hi. I have the same error now.  How'd you fix it?  Thanks.

Vera

**Comment by cculma** [comment]
In my case were two errors:
1. The wrong use of genome.gff instead of genome.gtf
2. I was trying to run SQANTI3 in the workstation with python2.7 by default (it works well for SANTI1), therefore I install SQANTI3 in the server which runs with python3.7 and now is working.

Best,

Cesar

**Comment by Magdoll** [comment]
Closed unless otherwise noted by OP.

**Comment by Ismail-Curie** [comment]
Hello, I still have the same issue, could you help me find a solution to that.

**Comment by Magdoll** [comment]
Hi @Ismail-Curie , please show the full command you are running and the error. Also, please make sure you are using the latest SQANTI3 version (v1.1)

**Comment by Ismail-Curie** [comment]
Hi @Magdoll,

I'm using the latest SQANTI3 version, below the full command:
python3.7 sqanti3_qc.py --force_id_ignore /home/ismail/Downloads/cluster_via_merge/clustered.lq.fasta /home/ismail/Downloads/ref/gencode.v28.annotation.gtf /home/ismail/Downloads/ref/hg38_base.fasta -x /home/ismail/my_hg38_base/my_hg38_base -t 10 -d /home/ismail/ALTERNA/Results_SQANTI/

Thank you,
Ismail

**Comment by Magdoll** [comment]
Hi @Ismail-Curie ,
I'm actively moving users away from inputting a fasta input - can you please provide a GTF input instead? You can align `clustered.lq.fasta` using minimap2 and convert it to GTF/GFF3 using [sam_to_gff3.py](https://github.com/Magdoll/cDNA_Cupcake/wiki/Sequence-Manipulation-Wiki#sam2gff3) in Cupcake.

If issue persists, please provide an email so I can request file upload to check for issues :-)

-Liz

**Comment by Ismail-Curie** [comment]
Hi @Magdoll,
I still have the same error even after using a gtf input instead of fasta, can I send you the files? (my email is jamail.ismail1@gmail.com)

**Comment by Magdoll** [comment]
Hi @Ismail-Curie , file request emailed!

**Comment by Ismail-Curie** [comment]
Hi @Magdoll ;
I sent the input file.
Thank you.

**Comment by Magdoll** [comment]
Hi @Ismail-Curie ,
I discovered two issues and both are related to your GFF3 input structure.

The input needs to have a `transcript` record and a `exon` record. I converted it using gffread
```
gffread -T input.gff3 -O output.gtf
```

Next, some of your transcripts have the same ID and are on different chromosomes or strand.
For example below you have three records that share the same ID, this causes errors in running SQANTI3.

I am emailing you back the fixed results.

```
chr1    hg38    transcript      634766  634924  .       +       .       transcript_id "transcript/455494"; gene_id "transcript/455494";
chr1    hg38    exon    634766  634924  .       +       .       transcript_id "transcript/455494"; gene_id "transcript/455494";
chrM    hg38    transcript      9546    9990    .       +       .       transcript_id "transcript/455494"; gene_id "transcript/455494";
chrM    hg38    exon    9546    9990    .       +       .       transcript_id "transcript/455494"; gene_id "transcript/455494";
chrM    hg38    transcript      9571    9787    .       -       .       transcript_id "transcript/455494"; gene_id "transcript/455494";
chrM    hg38    exon    9571    9787    .       -       .       transcript_id "transcript/455494"; gene_id "transcript/455494";
```

**Comment by Ismail-Curie** [comment]
Thank you very much @Magdoll.

**Comment by kudasonya** [comment]
Hello @Magdoll, I am trying to solve the same issue and have converted my collapsed.gff from cupcake to a .gtf, but am still getting the same error. 
```
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /ei/projects/3/31655266-640a-41d2-8663-59bba38bc3c4/data/data/References/hg38_sequin.fa....
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
Traceback (most recent call last):
  File "/ei/.project-scratch/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/SQANTI3/sqanti3_qc.py", line 2461, in <module>
    main()
  File "/ei/.project-scratch/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/SQANTI3/sqanti3_qc.py", line 2444, in main
    run(args)
  File "/ei/.project-scratch/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/SQANTI3/sqanti3_qc.py", line 1839, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene = reference_parser(args, list(genome_dict.keys()))
  File "/ei/.project-scratch/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/SQANTI3/sqanti3_qc.py", line 664, in reference_parser
    for r in genePredReader(referenceFiles):
  File "/ei/.project-scratch/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/SQANTI3/sqanti3_qc.py", line 137, in __init__
    self.f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/ei/.project-scratch/8/8289c66d-2d56-4706-a307-5a9a3eb3747e/refAnnotation_Capture4_barcode11_sqanti.genePred'
```

I ran cDNACupcake with the following command:
`python cDNA_Cupcake/cupcake/tofu/collapse_isoforms_by_sam.py --input Capture4/barcodes/demultiplexed/barcode11/barcodes11.fastq --fq -s Capture4_barcodes11.sorted.sam --dun-merge-5-shorter -c 0.97 -o Capture4_barcode11`
And then SQANTI:
`python SQANTI3/sqanti3_qc.py Capture4_barcode11.collapsed.gtf References/gencode.v29.annotation_sequin.gtf References/hg38_sequin.fa --cpus 20 --report pdf --genename --isoAnnotLite -o Capture4_barcode11_sqanti`

**Comment by kudasonya** [comment]
I also checked my collapsed.gtf and there don't seem to be any duplications of same IDs.

**Comment by Ismail-Curie** [comment]
Hello @kudasonya,
The problem might be related to your fasta file, I had the same issue for a long time, it was resolved by changing my reference.
good luck,
Ismail
