### ISSUE TITLE
No GeneIDs in GTFs

### ISSUE THREAD

**Issue by moschmi** [ConesaLab/SQANTI3#10]
I am analyzing scRNA data. I need a gtf file with annotated geneIDs.
I used sqanti3_qc.py with the isoAnnotLite option. This gives me the tappAS_annot_from_SQANTI3.gff3 with gene-IDs. After filtering that output with_RulesFilter.py the resulting GTF has no gene-ID, just PBs. 
It would be great if all the GTFs have geneIDs without need for extra annotation.

**Comment by aarzalluz** [comment]
Please see answer to issue #17.
