### ISSUE TITLE
How to convert TAMA's output to SQANTI3's input?

### ISSUE THREAD

**Issue by gouwei1** [ConesaLab/SQANTI3#102]
I used TAMA collapse to produce a *.bed file, while SQANTI3 require a *.gtf file for input. How can I convert them? Thank you !

**Comment by sguizard** [comment]
You can use the script `tama_convert_bed_gtf_ensembl_no_cds.py` to convert the file from bed to gtf.
```
tama_convert_bed_gtf_ensembl_no_cds.py tama.bed tama.gtf
```

**Comment by gouwei1** [comment]
> You can use the script `tama_convert_bed_gtf_ensembl_no_cds.py` to convert the file from bed to gtf.
> 
> ```
> tama_convert_bed_gtf_ensembl_no_cds.py tama.bed tama.gtf
> ```

Thank you!
