### ISSUE TITLE
difference between ORF_length and the length of ORF_sequence

### ISSUE THREAD

**Issue by xiaonalu** [ConesaLab/SQANTI3#103]
Hi, Thanks for the SQANTI3 update.
I found that the number in the ORF_length and the actual sequence length of the ORF_seq sometime not matched. I understand the ORF_length is counted from the CDS_length divided by 3, while I think the length of ORF_seq should not be longer than this number. Thanks

**Comment by FJPardoPalacios** [comment]
This bug was solved with the latest version of SQANTI3. 
`ORF_Seq` used to include the sequence of peptides upstream the starting Methionine (`*_corrected.faa` contained the trimmed sequence as it should be), which caused the disagreement between CDS_length/3 and the length of ORF_seq.

Fran
