### ISSUE TITLE
cython is needed tobuild and install cDNA_Cupcake

### ISSUE THREAD

**Issue by gilfreund** [ConesaLab/SQANTI3#105]
https://github.com/ConesaLab/SQANTI3/blob/f15c052249b0f047448c8a908bc43126c8d283bd/SQANTI3.conda_env.yml#L8

Building cDNA_Cupcake will fail if cython is not available. Might be a good idea to add is to the environment yaml.

**Comment by aarzalluz** [comment]
Fixed in SQANTI3 version 5.0.
