### ISSUE TITLE
What's the meaning of the lowercase and capital in the corrected.fasta

### ISSUE THREAD

**Issue by xiaonalu** [ConesaLab/SQANTI3#106]
Hi, Thanks for the program.
I want to ask What's the meaning of the lowercase and capital in the classification.filtered_lite.fasta in SQANTI3. Are the lowercase still represents intron in this file? Thanks
Best
Xiaona

**Comment by aarzalluz** [comment]
The .fasta output file of SQANTI3 is obtained as follows, as per the documentation:

> FASTA file: the _corrected.fasta file contains the genomic sequences of transcripts supplied to SQANTI3 QC, obtained using the _corrected.gtf file and the provided reference genome.

Therefore I would assume that this depends on the meaning of upper/lowercase in the actual genome sequence (check [this stack exchange discussion](https://bioinformatics.stackexchange.com/questions/225/uppercase-vs-lowercase-letters-in-reference-genome) for some insight).

Hope that helps,

Ángeles
