### ISSUE TITLE
ISM 5’/3’internal fragment

### ISSUE THREAD

**Issue by xiaonalu** [ConesaLab/SQANTI3#108]
Hi, I understand the illustration about the ISM 5’/3’internal fragment, but I am curious how the program actually analyze it. Could it be possible some transcripts present exactly in the ISM 5’fragment format in reality? Is the subcategory supported by other data, CAGE or anything? Is it safe to filter out the ISM 5’/3’internal fragment transcripts? Thanks

**Comment by aarzalluz** [comment]
Hi @xiaonalu,

SQANTI3's isoform classification is naive to whether the transcript is real or not -this is something that the user must decide based on the SQ3 descriptors, which, as you mentioned, include CAGE peaks and TSS ratio (5' end) as well as polyA motif and peak information (3' end). Of course, these are particularly relevant to validate the TSS and TTS of isoforms in the ISM category. 

My advice would be to evaluate the support that theTSS/TTS of your ISM isoforms have from those data sources, which is available in the SQANTI classification file, and filter out potential artifacts. We recently published [a paper](https://www.nature.com/articles/s41467-022-29497-w) in which we build and filter a transcriptome based on those criteria. You can find the info in Supplementary Note 1.

Best,

Ángeles
