### ISSUE TITLE
Is there Issue with Matrix.so?? 

### ISSUE THREAD

**Issue by B10inform** [ConesaLab/SQANTI3#109]
Hi all,

With SQANTI3, I am getting the following error. Any help would be appreciated.

Module conda3/1.0 loaded 
R scripting front-end version 4.1.1 (2021-08-10)

**** Parsing Isoforms....
**** RT-switching computation....
Full-length read abundance files not provided.
Isoforms expression files not provided.
**** Writing output files....
**** Generating SQANTI3 report....
Loading required package: Biobase
Loading required package: BiocGenerics

Attaching package: ‘BiocGenerics’

The following object is masked from ‘package:gridExtra’:

    combine

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which.max, which.min

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: splines
Loading required package: Matrix
Error: package or namespace load failed for ‘Matrix’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/software/R/R-4.1.1/library/Matrix/libs/Matrix.so':
  libRlapack.so: cannot open shared object file: No such file or directory
Error: package ‘Matrix’ could not be loaded
Execution halted
Traceback (most recent call last):
  File "/home/software/SQUANTI/SQANTI3-4.2/sqanti3_qc.py", line 2509, in <module>
    main()
  File "/home/software/SQUANTI/SQANTI3-4.2/sqanti3_qc.py", line 2492, in main
    run(args)
  File "/home/software/SQUANTI/SQANTI3-4.2/sqanti3_qc.py", line 2101, in run
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/home/.conda/envs/SQANTI3.env/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/.conda/envs/SQANTI3.env/bin/Rscript /home/software/SQUANTI/SQANTI3-4.2/utilities/SQANTI3_report.R /home/SQANTI/SQANTI3/Rx_classification.txt /home/SQANTI/SQANTI3/Rx_junctions.txt /home/Iso-Seq/SQANTI/SQANTI3/Rx.params.txt /home/software/SQUANTI/SQANTI3-4.2/utilities False pdf' returned non-zero exit status 1.

Thanks

**Comment by aarzalluz** [comment]
Installation dependency issue, non-SQ3 related. Closing unless OP updates.
