### ISSUE TITLE
Error in PolyA Peak Finding

### ISSUE THREAD

**Issue by lzx325** [ConesaLab/SQANTI3#110]
I think L1622 should be `rec.txEnd` and L1624 should be `rec.txStart`.
https://github.com/ConesaLab/SQANTI3/blob/f15c052249b0f047448c8a908bc43126c8d283bd/sqanti3_qc.py#L1611-L1626

**Comment by FJPardoPalacios** [comment]
You are totally right! This was a bug and I just fixed it

Thank you for letting me know!

Fran
