### ISSUE TITLE
Request: allow --isoAnnotLite to run without precomputed tappAS species specific GFF3 file

### ISSUE THREAD

**Issue by joelnitta** [ConesaLab/SQANTI3#111]
In a previous version of SQANTI3 (sorry, not surely exactly which one...) if memory serves me correctly, `--isoAnnotLite` could be used without `--gff3` and a `_tappAS_annot_from_SQANTI3.gff3` would be produced. This is useful in the case that one wants to analyze the SQANTI3 results in tappAS for a species that lacks a pre-computed GFF3 file.

In the current version (4.2 ), if I specify `--isoAnnotLite` without `--gff3`, no `_tappAS_annot_from_SQANTI3.gff3` is produced. At the very least, if the intention is not to allow such usage, an error should be returned instead of simply ignoring the flag.

**Comment by aarzalluz** [comment]
Hi @joelnitta,

Thank your for reporting this -we'll have a look into it and revert the change for the next release of SQANTI3. As you say, it makes no sense to force users to provide a GFF3 file, as there are many people working on non-model organism transcriptomics.

In the meantime, you will need to run IsoAnnotLite outside of SQANTI3 to be able to produce a tappAS-compatible GFF3 file.

Best,


Ángeles

**Comment by aarzalluz** [comment]
Hi @joelnitta,

We just released a new version of IsoAnnotLite that fixes the --gff3 issue you reported. You can download it from [here](https://isoannot.tappas.org/isoannot-lite/). Could you try replacing the IsoAnnotLite script in utilities with the newer version, and let us know the result?

Best,

Ángeles

**Comment by aarzalluz** [comment]
Closing because fix was reported to solve the issue in https://github.com/ConesaLab/tappAS/issues/39.
