### ISSUE TITLE
Options for ORF starting with non-methionine codon

### ISSUE THREAD

**Issue by MarLee39** [ConesaLab/SQANTI3#112]
Thank you for developing such a nice tool!  
I know that SQANTI predicts ORF started at the first in-frame methionine, shortening the N terminus. But I would like to check whether that ORFs have the possibility starting with non-canonical codons (other than methionine). Is there any options (or any ways) to choose starting codon (methionine or non-methionine) in SQANTI?

**Comment by aarzalluz** [comment]
Closing (unanswered).
