### ISSUE TITLE
Error with sqanti3_qc.py, halting while executing SQANTI3_report.R

### ISSUE THREAD

**Issue by sunnyd13579** [ConesaLab/SQANTI3#114]
Re-posting the following issue in the right repo (apologies! :| Had them both open, and posted on the wrong page :| )
https://github.com/Magdoll/cDNA_Cupcake/issues/191

@Magdoll , checked the following files and they are not empty
dedup.5merge.collapsed_classification.txt
dedup.5merge.collapsed_junctions.txt

And the following files were generated after running sqanti3_qc.py
![files_generated](https://user-images.githubusercontent.com/98926314/152387435-798688bc-b6a1-4126-abfb-0b3941911bab.JPG)

**Comment by aarzalluz** [comment]
Issue appears to be fixed. Closing unless OP reopens.
