### ISSUE TITLE
reporting issue regarding data chuncking option -n : gmst.pl data input empty error

### ISSUE THREAD

**Issue by hd00ljy** [ConesaLab/SQANTI3#117]
I use SQANTI with -n option to speed up the process and orf prediction option.

For some reason, I also split the input transcript gtf (not ref gtf) into several files and I suddenly got errors I haven't observed before.

```
error: data input empty
Process Process-10:
Traceback (most recent call last):
  File "/home/hrs/.conda/envs/SQANTI3.env.4.2/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/hrs/.conda/envs/SQANTI3.env.4.2/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/(some path)/SQANTI3-4.2/sqanti3_qc.py", line 1884, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/(some path)/SQANTI3-4.2/sqanti3_qc.py", line 594, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/home/hrs/.conda/envs/SQANTI3.env.4.2/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /(some path)/SQANTI3-4.2/utilities/gmst/gmst.pl -faa --strand direct --fnn --output (output path)/SQANTI4.2_splits/9/SQANTI4.2_corrected.fasta
```

So basically gmst.pl threw the error complaining about the empty input but I manually checked that SQANTI4.2_corrected.fasta in the 9th split was not empty.

I finally found the following system call within gmst.pl threw the error during ORF prediction and the itr_2.mod file was the one that was empty.
```
/(some path)/SQANTI3-4.2/utilities/gmst/probuild --par /(some path)/utilities/gmst/par_1.default --mkmod itr_2.mod --seq sequence --geneset itr_1.lst --ORDM 4 --order_non 2 --revcomp_non 1 --fixmotif --PRE_START_WIDTH 6 --width 12 --log gms.log
```

It seems some process prior to probuild within gmst.pl gave the result to none of the input transcripts.

So I thought that if I could merge the problematic split and the non-problematic one the issue may be temporarily resolved.
I tried reducing the -n option from 28 to 14 and the SQANTI run was successful.

It seems to arise if only the ORF-less transcripts are coincidentally placed in a single chunck.

**Comment by aarzalluz** [comment]
SQANTI3 currently runs GeneMark for ORF prediction, a tool that is unfortunately not maintained/updated. Errors related to GMST will therefore not be worked on, however, given the high amount of issues it is generating, we intend to find an alternative way to predict ORFs for future SQ3 releases as soon as we can.

In the meantime, the --skipORF argument can be used to avoid ORF prediction entirely and prevent SQANTI3 from crashing. We apologize for any inconveniences.
