### ISSUE TITLE
Why intergenic transcripts have known junctions?

### ISSUE THREAD

**Issue by hd00ljy** [ConesaLab/SQANTI3#119]
I got many intergenic transcripts that have known junctions either canonical or non-canonical.

They overlap with known transcripts
For example, the green transcript in the capture below overlaps some known gene but were categorized as intergenic

Could you let me know the criteria you use to determine whether a transcript is intergenic.

![image](https://user-images.githubusercontent.com/13775022/154033133-b08db477-418e-49c0-b627-218a57245fb4.png)

**Comment by Dongxu-Zheng** [comment]
I think the green transcript is an intergenic isoform because it is in the "-" strand instead of "+" strand. It is a novel transcript and it is not an isoform or transcript of PGD.

**Comment by FJPardoPalacios** [comment]
@Dongxu-Zheng is right, the green isoform is an intergenic one because it doesn't match the strand of PGD

**Comment by hd00ljy** [comment]
Thank you for the comments!

I have one more question then.

Why the green transcript was categorized as integenic but not as antisense?

I'd like to know the distinction between antisense and intergenic
