### ISSUE TITLE
polyA_peak

### ISSUE THREAD

**Issue by xiaonalu** [ConesaLab/SQANTI3#125]
Hi, when I ran squanti3 for mouse data with--polyA_peak, I have a polyA_peak_GRCm39.bed as input. Is there a human version could be download? Thanks

**Comment by FJPardoPalacios** [comment]
Probably in the same repository you found the mouse data. If it's not the case, you can go to the [polyA site atlas](https://polyasite.unibas.ch/atlas) and download the human BED file. Please, double check the version of your reference genome and the BED file. If it's not matching, you can always [lift the genome annotation](https://genome.ucsc.edu/cgi-bin/hgLiftOver) to the desired version.

Bests,
Fran
