### ISSUE TITLE
How the SQANTI3 define mono-exon?

### ISSUE THREAD

**Issue by KHiLLCH1N9** [ConesaLab/SQANTI3#127]
<html>
<body>
<div style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: black; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: black; background-color: transparent;"><span> </span>Hi!
I got the classifcation files and junction files after running the 'qc' and 'filter' step of SQANTI3. However, I was confused about the full-spliced-match result of mono-exon <span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: black; text-align: center; background-color: white;">subcategory. I found that the results shown in the *.filtered_lite_classification.txt, the length of isoforms defined as mono-exon full-splice-match were not perfect match of  the reference . And the mono-exon isoforms have only one exon without splice junction,but the SAQNTI3 classfied them into full-splice-match. Take the result below as an example:</span><br aria-hidden="true"></span></div><div style="margin: 0px; padding: 0px; border: 0px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: black; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: black; background-color: transparent;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: black; text-align: center; background-color: white;"><div class="ugHd8hEKTmP3zNa_t33nm" has-hovered="true" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit; position: relative; overflow: hidden; height: 116px; width: 944.5px;"><div class="_3OSvA877av7sNgMphVnY6Z" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit; opacity: 0; z-index: -1; position: absolute;"><button type="button" class="ms-Button ms-Button--icon KBwACy35vUu44VLeJybtU root-229" title="显示原始尺寸" aria-label="显示原始尺寸" data-is-focusable="true" style="margin: 0px; padding: 8px; border: none; font-style: inherit; font-variant: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: controlIcons !important; vertical-align: baseline; color: var(--white); outline: transparent; position: absolute; -webkit-font-smoothing: antialiased; box-sizing: border-box; display: inline-block; text-decoration: none; text-align: center; cursor: pointer; border-radius: 2px; width: 32px; height: 32px; background: var(--neutralPrimary); user-select: none; top: 5px; z-index: 1; box-shadow: 0 0 5px var(--neutralSecondary); left: 5px;"><span class="ms-Button-flexContainer flexContainer-159" data-automationid="splitbuttonprimary" style="margin: 0px; padding: 0px; border: 0px; font: inherit; vertical-align: baseline; color: inherit; display: flex; height: 16px; flex-wrap: nowrap; justify-content: center; align-items: center;"><i data-icon-name="FullScreen" aria-hidden="true" class="ms-Icon root-90 css-167 ms-Button-icon icon-161" style="display: inline-block; font-size: 16px; margin: 0px 4px; height: 16px; line-height: 16px; text-align: center; flex-shrink: 0; -webkit-font-smoothing: antialiased; font-style: normal; font-weight: normal; speak: none; font-family: controlIcons;"></i></span></button></div>

isoform | chrom | strand | length | exons | structural_category | associated_gene | associated_transcript | ref_length | ref_exons | diff_to_TSS | diff_to_TTS | diff_to_gene_TSS | diff_to_gene_TTS | subcategory
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
PB.109.1 | chr1 | + | 1991 | 1 | full-splice_match | ENSG00000284602.1 | ENST00000641729.1 | 2190 | 1 | 57 | 142 | 57 | -142 | mono-exon

</div>the length of PB.109.1 is shorter than the reference length and the diff_to_TSS and diff_to_TTS shown me the differences, but I don't known why this isoform was defined as full-splice-match. I was wondering if this result might be the error of  the<span> </span><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12pt; line-height: inherit; font-family: Calibri, Arial, Helvetica, sans-serif; vertical-align: baseline; color: black; text-align: left; background-color: white;">algorithm, but I found there are more than 100 mono-exon isoforms of my data were defined as FSM. I want to know how the mono-exon isoforms were defined as  FSM.
</span></span></span></div>
</body>
</html>

**Comment by FJPardoPalacios** [comment]
Hi!
SQANTI3 will classify as FSM any mono-exonic isoforms overlapping a mono-exonic reference transcript-model, which is the case of your matching[ transcript ](https://www.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000284602;r=1:25232586-25234775;t=ENST00000641729). Maybe it's not obvious to define them as *"splice match"* since there are not SJs neither in your isoform nor the reference transcript-model, but if you think about their one and only exon, there is a clear match. I will say that your ~100 mono-exon FSM are being associated to mono-exonic reference transcripts (check `exons` and `ref_exons` columns), so it's not an error of the algorithm.

PS: Please, do not open issues and close them later because you asked via email or similar. If you found out the answer you were looking for before anyone can reply, just let it know in the issue. If not, we'll answer it and anyone with a similar question would be able to read the answer. We're kind of trying to create a community here, but it won't work out if we start jumping from issues to personal emails. Thanks.
