### ISSUE TITLE
Outputs from QC with --short_reads 

### ISSUE THREAD

**Issue by AbeerMM** [ConesaLab/SQANTI3#131]
Hello,

I'm running SQANTI3 for each sample individually, and below is my command:

     python ~/softwares/SQANTI3/sqanti3_qc.py -t 40 ${sampleName}.collapse.gtf annotation.gtf hg38.fa --fl_count ${sampleName}.collapse.abundance.txt --cage_peak refTSS_v3.3_human_coordinate.hg38.bed --polyA_motif_list mouse_and_human.polyA_motif.txt --polyA_peak atlas.clusters.2.0.GRCh38.96.bed --short_reads ${sampleName}.fofn --genename --saturation --report pdf --output ${sampleName}

As you can see I'm using fofn for short reads (fastq files). I have paired-end samples, so I expect Kallisto to run smoothly. I have some observations and I want to make sure there is no errors in the results I'm generating 

1. I noticed in Kallisto folder generated by the QC, the folder name is: ${sampleName}.R1 even though I provided the argument: --output ${sampleName}. Does that mean only one read is used? or there is something wrong with reading the fofn? Actually, even in STAR_mapping folder, the labels has R1 in them.

2. I get NaN in ratio_TSS column for all my samples. I'm not sure why. Based on the Wiki page:
      >STAR and Kallisto will be run to calculate automatically the coverage of the SJ, the isoform expression and also the ratio_TSS, a metric that quantifies the differences of mean coverage 100bp upstream and downstream the reported TSS.

      So, I'm not sure why I can't get the ratio_TSS values.

3. There is an internal step after the STAR_mapping is generated and where the intermediate files (inside_TSS.bed & outside_TSS.bed) are generated that takes very long (> 8 hours), after this messages:

      `Input pattern: /data/sample1/STAR_mapping/.
The following files found and to be read as junctions:
/data/sample1/STAR_mapping/sample1.R1SJ.out.tab
68585 junctions read. 2541 junctions added to both strands because no strand information from STAR.`

It gets stuck here for hours, and I try to inspect the process that's taking too long and found this command:

      bedtools coverage -sorted -g /data/sample1/STAR_index//chrNameLength.txt -b /data/sample1/STAR_mapping/sample1.R1Aligned.sortedByCoord.out.bam -a /data/sample1/outside_TSS.bed 

It doesn't run in parallel or on multiple threads. That's why it's taking long. If there is any workaround to speed up this step, that'd be very helpful. Also, getting the NaN values in ratio_TSS after this long run seems to be a bug.

4. If I use the chunk parameter (-n) along with (-t), would that speed up the run? will the split files be combined at the end? is there any conflict between -n & -t? if I have -t 40, and -n 10, does that mean 40 will be divided on 10 split files, or each split file will have 40 threads?

Update: I just tried the option -n 10 -t 40, and I noticed even though I have the STAR_index in the main folder, but each split run will generate its own STAR_index adding more time to each split run. I think there should be an option to give the STAR_index that can be used in all the internal processes. 

Thank you

**Comment by FJPardoPalacios** [comment]
Hi!

We definitely are going to implement the option of giving the STAR_index path to avoid the problem you mentioned regarding parallelization. 

About the 1st question: `--output` argument is used for the main output files, but for STAR and Kallisto outputs, SQANTI3 will take the names of the Illumina files. We normally expect (and recommend) to have several replicates for Illumina data. Would it be possible to have a look to some lines of your fofn file?

Regarding the 3rd question: How many samples or replicates have you sequenced with Illumina? And how many isoforms do you have in the `{sampleName}.collapse.gtf`? I'm asking because SQANTI3 will go through all the detected TSS and calculate for each sample(or replicate) its `ratio_TSS`, keeping just the maximum value across all samples. Having a big number of samples or isoforms will make it to take more time. For that we use **bedtools**, but I don't know if **bedtools** allows to parallelize processes, if there's a way, I'll try to include it in the code to speed it.

I'm still curious about the NaN results for the `ratio_TSS` column... Do you know if the `bedtools coverage` command finish correctly? If the `inside_TSS.bed` and `outside_TSS.bed` files were still in the output folder, something went wrong since they are temporary files...

Fran

**Comment by AbeerMM** [comment]
> About the 1st question: `--output` argument is used for the main output files, but for STAR and Kallisto outputs, SQANTI3 will take the names of the Illumina files. We normally expect (and recommend) to have several replicates for Illumina data. Would it be possible to have a look to some lines of your fofn file?
> 
Unfortunately, I only have one replicate Illumina for each long-read sample. So, I only have one line in each fofn file:

         /data/fq/Human.RNAseq.Sample1.R1.fastq /data/fq/Human.RNAseq.Sample1.R2.fastq
Can I input these two file directly in the command instead of fofn since I have one rep? Also my fastq files are unzipped, could that have an effect?

> Regarding the 3rd question: How many samples or replicates have you sequenced with Illumina? And how many isoforms do you have in the `{sampleName}.collapse.gtf`? I'm asking because SQANTI3 will go through all the detected TSS and calculate for each sample(or replicate) its `ratio_TSS`, keeping just the maximum value across all samples. Having a big number of samples or isoforms will make it to take more time. For that we use **bedtools**, but I don't know if **bedtools** allows to parallelize processes, if there's a way, I'll try to include it in the code to speed it.
> 

For each run, I only have one replicate sequenced with Illumina. I have ~ 70,927 transcripts in my {sampleName}.collapse.gtf file 

> I'm still curious about the NaN results for the `ratio_TSS` column... Do you know if the `bedtools coverage` command finish correctly? If the `inside_TSS.bed` and `outside_TSS.bed` files were still in the output folder, something went wrong since they are temporary files...
> 

I think the bedtools command finish correctly. I monitored the run, and I saw these files `inside_TSS.bed` and `outside_TSS.bed` get generated then at the end they get removed. So, it seems it's calculating the ratios, but I don't know what happens when writing the results.

**Comment by FJPardoPalacios** [comment]
We are intrigued about your problem and I'm specially surprised by this line:
`Input pattern: /data/${sampleName}/STAR_mapping/.`
It shouldn't look like that and the actual `sampleName`should be printed... I've never used the `${variable}` to call a variable, I simply do `$variable`. Maybe that is a problem for some part of the code, could you try to remove those brackets? 

Regarding the compressed FASTQ files and the one line fofn, that's not a problem, and the number of transcripts doesn't seem to me a crazy amount, so I wouldn't say that is an issue neither.

Fran

**Comment by AbeerMM** [comment]
@FJPardoPalacios Thanks for your response. I'll try what you suggested. However, I tried to see if this problem has anything to do with my installation, and I ran the example included in the package, and surpassingly, I get NaN as well!!

Could you please test that on your side to see if this issue is producible? If it gives you Nan as well, it could mean that the recent update has some issue.

Thanks again for your troubleshooting

**Comment by AbeerMM** [comment]
I'm using miniconda3, and I don't know why when I create Sqanti environment, it uses python3.9. That could be the reason. I'm not sure how to force it to use python3.7. Also, I get this warning when I create the env:

     Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

**Comment by FJPardoPalacios** [comment]
Hi Abeer!

I just re-run the example and it worked for me. It actually calculates all the ratio_TSS, no matter if I provide one or two replicates for the Illumina data. Btw, I'm using python 3.9.5, so that shouldn't be the problem. I don't know what could be happening...

Fran
