### ISSUE TITLE
Number of annotated genes significant decreased after sqanti3 run

### ISSUE THREAD

**Issue by zmz1988** [ConesaLab/SQANTI3#132]
Hi developers, first of all, thank you for the nice tool! I have a question about the outputted corrected.gtf from sqanti3. My input annotation has more than 30,000 coding genes, but after the run of sqanti, I only have 8000 genes in corrected.gtf file. Considering that transcripts from our Isoseq data only have a busco value of 44%, I would assume that sqanti3 only outputs the corrected genes that are supported by Isoseq data?

Another point I don't understand is that actually I provided the short-read sequence (.bam file) for sqanti3 together with the long read data. Will sqanti3 only focus on the long-read supported gene?

Here is my command

`python /home/user/SQANTI3-4.2/sqanti3_qc.py ../long_read_protocol/cupcake.collapsed.gff ./tsebra/sample_idfix.gtf ./sample.fasta.mod.MAKER.masked \
--SR_bam bam_file.fofn \
-c ../01_trimmed_filtered_Illumina_RNAseq/sample_SJ.out.tab \
-fl ../long_read_protocol/cupcake.collapsed.abundance.txt \
--cpus 20 \
--report both \
-o Sample `

Btw, I got quite some warning along the sqanti run
```
R scripting front-end version 4.1.2 (2021-11-01)
**** Parsing Isoforms....
Input pattern: ../01_trimmed_filtered_Illumina_RNAseq/Sample_SJ.out.tab.
The following files found and to be read as junctions:
../01_trimmed_filtered_Illumina_RNAseq/Sample_SJ.out.tab
185342 junctions read. 629 junctions added to both strands because no strand information from STAR.
/home/user/SQANTI3-4.2/utilities/short_reads.py:174: FutureWarning: The frame.append method is deprecated and will be removed from pan
das in a future version. Use pandas.concat instead.
  inside_df = inside_df.append([{'id' : entry.name , 'inside' : float(entry[6])}], ignore_index=True)
/home/user/SQANTI3-4.2/utilities/short_reads.py:174: FutureWarning: The frame.append method is deprecated and will be removed from pan
das in a future version. Use pandas.concat instead.
  inside_df = inside_df.append([{'id' : entry.name , 'inside' : float(entry[6])}], ignore_index=True)
/home/user/SQANTI3-4.2/utilities/short_reads.py:174: FutureWarning: The frame.append method is deprecated and will be removed from pan
das in a future version. Use pandas.concat instead.
(omit hundreds of similar lines as above and below)
WARNING: PB.8252.2 not found in FL count file. Assign count as 0.
WARNING: PB.8252.3 not found in FL count file. Assign count as 0.
WARNING: PB.8253.1 not found in FL count file. Assign count as 0.
WARNING: PB.8252.4 not found in FL count file. Assign count as 0.
WARNING: PB.8253.2 not found in FL count file. Assign count as 0.
WARNING: PB.8255.1 not found in FL count file. Assign count as 0.
WARNING: PB.8254.1 not found in FL count file. Assign count as 0.
WARNING: PB.8256.2 not found in FL count file. Assign count as 0.
WARNING: PB.8256.5 not found in FL count file. Assign count as 0.
Isoforms expression files not provided.
**** Writing output files....
**** Generating SQANTI3 report....
Loading required package: Biobase
Loading required package: BiocGenerics
(omit hundreds of the lines as below warning)
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
Warning messages:
1: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
2: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
`summarise()` has grouped output by 'associated_transcript'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'associated_transcript'. You can override using the `.groups` argument.


processing file: SQANTI3_report.Rmd
output file: SQANTI3_report.knit.md


Output created: Sample_SQANTI3_report.html
There were 32 warnings (use warnings() to see them)
Removing temporary files....
SQANTI3 complete in 1021.4617640599608 sec.

```

**Comment by FJPardoPalacios** [comment]
Hi! Thank you for using SQANTI3. 

SQANTI3 was thought to analyze Long-Reads (LR) based transcriptomes by comparing them to a reference annotation. So it will only output information about **your isoforms**, the ones you have in your `../long_read_protocol/cupcake.collapsed.gff`. For instance, your BAM file will tell how Short-Reads (SR) are mapping around your isoforms' TSS (this is the *ratio_TSS* column) and your `../01_trimmed_filtered_Illumina_RNAseq/sample_SJ.out.tab` will provide information about the coverage of the SJs present in your isoforms. *sqanti3_qc.py* doesn't filter out anything (specially if you input your isoforms as GTF), it just gathers information about them, when possible.

None of the analysis or evaluations are done at the gene level, in fact, all those isoforms of the LR-based transcriptome mapping to an unannotated locus (or at least not matching to a known gene) will be categorized as "novel genes", even if they look like several isoforms coming from the same locus, SQ3 doesn't try to define new genes at all.

Regarding the *warnings*: Don't worry about those related with `pandas` and the last ones, they are issues with functions that will be deprecated when a new version of some packages come up, but it's okay. I'm more curious about those like this:
`WARNING: PB.8252.2 not found in FL count file. Assign count as 0.`
Can you find those PB ids in your `../long_read_protocol/cupcake.collapsed.abundance.txt` file?

Bests,
Fran

**Comment by zmz1988** [comment]
Hi Fran, Thanks for replying me!

Ok, now it's much clearer to me. I was thinking to use SQANT3 to add the outputted Isoform information to my annotation file. So I guess, to do that, I would just need to add the novel isoforms from the filtered corrected.gtf to my annotation, right?

No, they are in the `cupcake.collapsed.gff`, but not in `../long_read_protocol/cupcake.collapsed.abundance.txt`. I also don't understand why.

**Comment by aarzalluz** [comment]
Hi @zmz1988 -for questions about cupcake, please refer to the [cDNA_cupcake](https://github.com/Magdoll/cDNA_Cupcake) repo.

Regarding your last question, we recommend filtering isoforms based on the quality control attributes that SQANTI QC provides before using them for downstream analysis. After removing false positive isoforms, you can just use the filtered GTF output by SQANTI3 as your annotation. You may check [our wiki](https://github.com/ConesaLab/SQANTI3/wiki/Running-SQANTI3-rules-filter) to see how to run the currently available SQ3 filter, or perform custom filtering based on your preferences.

I'm closing the issue now, but feel free to contact us if you need assistance with anything else.

Best,

Ángeles
