### ISSUE TITLE
How to generate the TSS bed file for other species?

### ISSUE THREAD

**Issue by zmz1988** [ConesaLab/SQANTI3#134]
Hi developers, I have some questions about how to generate the TSS bed file for plant species. Sorry if this question is naive.

Do we need the experimental verified TSS sequence as input for SQANTI3? Or we could simply input the predicted TSS sequence? I guess the first option?

I find some database for plant promoter sequence at [here](http://www.softberry.com/berry.phtml?topic=plantprom&group=data&subgroup=plantprom) . If I would like to use SQANTI on rice or Arabidopsis, could I lift [this](http://www.softberry.com/data/plantprom/Links/PLPR_verified_dicot.seq) for Arabidopsis and [this](http://www.softberry.com/data/plantprom/Links/PLPR_verified_monocot.seq) for Rice? These files include promoter sequences as well. Shall I remove the promoter sequences from these files before lifting them?

Thanks a lot in advance!

**Comment by aarzalluz** [comment]
Closing (unanswered).
