### ISSUE TITLE
Using FLAIR quantify output for --fl_count argument

### ISSUE THREAD

**Issue by pgupta3005** [ConesaLab/SQANTI3#136]
I have long read nanopore reads that I have collapsed into a gtf transcriptome via FLAIR align/correct/collapse, to be used as input for SQANTI3 (version 4.1). Furthermore, using FLAIR quantify, I get a tsv file with raw counts for the transcripts identified. However, I am unable to use it as the --fl_count argument. I changed the columns of the file to be 'pbid' and 'fl_count' as would be present in single sample FL count file from Iso-seq pipeline. This is what the file looks like -

```bash
$ head FLAIR_out/quant4.tsv
pbid    count_fl
ENST00000000233.10      39.0
ENST00000000412.8       36.0
ENST00000000442.11      42.0
ENST00000001008.6       76.0
ENST00000002165.10      40.0
ENST00000004103.8       195.0
ENST00000004982.6       6.0
```  

I also use --force_id_ignore to use non-PacBio reads. However, the command exits with the error - 

```bash
Number of classified isoforms: 16461
Traceback (most recent call last):
  File "/home/pallavi/softwares/SQANTI3-4.1/sqanti3_qc.py", line 2486, in <module>
    main()
  File "/home/pallavi/softwares/SQANTI3-4.1/sqanti3_qc.py", line 2470, in main
    run(args)
  File "/home/pallavi/softwares/SQANTI3-4.1/sqanti3_qc.py", line 1913, in run
    fl_samples, fl_count_dict = FLcount_parser(args.fl_count)
  File "/home/pallavi/softwares/SQANTI3-4.1/sqanti3_qc.py", line 1808, in FLcount_parser
    d = dict((r['pbid'], r) for r in reader)
  File "/home/pallavi/softwares/SQANTI3-4.1/sqanti3_qc.py", line 1808, in <genexpr>
    d = dict((r['pbid'], r) for r in reader)
KeyError: 'pbid'
```  

Kindly let me know if any further changes could be made to the fl_counts file to use it for SQANTI3. Thanks!

**Comment by FJPardoPalacios** [comment]
Hi @pgupta3005 ,

Could you write down the command line you are using for running SQANTI3?

Thanks!

**Comment by pgupta3005** [comment]
Hi! Sorry for the late response. Here is the command I ran.

```
nohup python /home/pallavi/softwares/SQANTI3-4.1/sqanti3_qc.py FLAIR_out/ind1_ONT_flair_collapse.isoforms.gtf \
gencode.v31.primary_assembly.annotation.gtf GRCh38.primary_assembly.genome.fa \
-o ind1_out --dir SQANTI3_out/ --fl_count FLAIR_out/quant4.tsv --expression rsem_exp/isoform/ --coverage STAR2_out/cov/  \
--SR_bam STAR2_out/SR_bam_input/ --saturation --force_id_ignore --report both \
--cage_peak /home/pallavi/softwares/SQANTI3-4.1/data/ref_TSS_annotation/human.refTSS_v3.1.hg38.bed \
--polyA_motif_list /home/pallavi/softwares/SQANTI3-4.1/data/polyA_motifs/mouse_and_human.polyA_motif.txt > ind1_SQANTI3.log &
```

**Comment by FJPardoPalacios** [comment]
Hi @pgupta3005 ,

Everything seems to be fine... Is it possible that in the file "FLAIR_out/quant4.tsv" there is an extra space after `pbid` ? The format is pretty strict and that might be a problem.

Fran

**Comment by pgupta3005** [comment]
Hi! Thanks a lot for the suggestion. There was indeed an extra space after the entire first column. Moreover, just for record, there were a couple of changes required further -
1. The first column of the output from FLAIR quantify is reported as ENSTxxx_ENSGyyyy or SRRzzz_chr12nnn. This was changed to retain just the transcript ID, i.e., everything before the '_'.
2. Since iso-seq reports absolute counts, there must not be decimal points in the second column of FLAIR quantify output.

So, the input to --fl_count looks like this

```
pbid    count_fl
ENST00000000233.10      39
ENST00000000412.8       36
ENST00000000442.11      42
ENST00000001008.6       76
ENST00000002165.10      40
ENST00000004103.8       195
ENST00000004982.6       6
```
