### ISSUE TITLE
How to run SQANTI3_qc with short read data

### ISSUE THREAD

**Issue by Ismail-Curie** [ConesaLab/SQANTI3#139]
Hi,
I am running the Iso-seq-SQANTI3 pipeline on multiple samples, my data is sequenced in both Pacbio long read sequencing and Illumina short read sequencing. I still don't understand how to include my short reads in the SQANTI_qc step, because to generate the expression matrix I need the corrected.fasta file from SQANTI3. Should I run the SQANTI3-qc step twice ? 
The first time to have the fasta file that I will use to generate the expression matrix using kallisto, then a second time with the expression matrix.

I also would like to know if it is possible to provide FASTQ files (paired short reads) from multiple samples to SQANTI_qc, if so, how to do that and how SQANTI3 uses them.

Thank you very much,
Ismail

**Comment by aarzalluz** [comment]
Hi @Ismail-Curie,

As described in the wiki, you can provide your short reads directly as FASTA/FASTQ files:

> It is possible to feed SQANTI3 with your matching RNA-Seq data (FASTA/FASTQ files) through the --short_reads argument. The expected file format is a File Of File Names (.fofn), which is a text file that contains the paths of the Short-Read RNA-Seq data with one line per replicate and separated by one space in the case of paired-end data. 

However, SQANTI3 is not a quantification tool: it only uses short read data for quality control purposes. 

SQ3 uses Illumina coverage to discriminate whether a transcript is a true isoform or an artifact. You should use the SQANTI QC output **filter your transcriptome** and remove low quality isoforms (which are abundant in long read defined transcriptomes). This is the reason why SQANTI3 quantification is not meant to be used for downstream analysis -we strongly advice against proceeding with transcriptome analysis without good isoform filtering.

The quality-filtered GTF can then be used for quantification outside of SQANTI using any method of your choice (Kallisto or other), and your short read data. Once low-quality isoforms are removed, short reads will be more confidently assigned and your quantification will be much more accurate -and more importantly, your analysis will not include false positive isoforms.

Best,

Ángeles
