### ISSUE TITLE
python error in sqanti3_qc.py

### ISSUE THREAD

**Issue by ruthfa** [ConesaLab/SQANTI3#14]
when I set 'python sqanti3_qc.py -h' I obtain the following error:

Traceback (most recent call last):
  File "sqanti3_qc.py", line 123, in <module>
    if os.system(RSCRIPTPATH + " --version")!=0:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

Shall I need to check my installation? I am not allow to use the .yml files so I have installed all the dependencies manually and maybe I have forgotten something

**Comment by FJPardoPalacios** [comment]
Yes, please check your installation. It seems that SQANTI3 is not able to find Rscript command...

**Comment by Magdoll** [comment]
Closed unless OP continues to have issue.
