### ISSUE TITLE
bcbiogff error

### ISSUE THREAD

**Issue by jchang97** [ConesaLab/SQANTI3#141]
Hi there, 

Thank you so much for creating this amazing tool!

I am just getting this error when running sqanti3_qc.py:

`Unable to import BCBio! Please make sure bcbiogff is installed.`

However, it seems that it's in my pip list:

```
$ pip list
Package              Version
-------------------- -------
bcbio-gff            0.6.6
```

Any suggestions would be greatly appreciated!

Thank you

**Comment by aarzalluz** [comment]
Hi @jchang97,

Just a couple of basic checks before we debug this further -when [installing SQ3](https://github.com/ConesaLab/SQANTI3/wiki/SQANTI3-dependencies-and-installation), were you able to successfully create the conda environment? Also, please make sure to activate it before running SQANTI3.

If you did both, then you might want to install the missing package manually into your environment -althought it is an error that I for one had never seen before.

Ángeles

**Comment by jchang97** [comment]
Hi Ángeles,

Thank you for your reply!

Yes, I was able to successfully create the conda environment and have activated it before running sqanti3_qc.py.

I used the code below to install the bcbio-gff package but sqanti3_qc.py still gives me the same error as above.
`conda install -c bioconda bcbio-gff`

Thank you

**Comment by aarzalluz** [comment]
Ok -that seems strange. It seems to me that there is a general dependency issue and/or a problem with the creation of the conda environment. Can you provide more details about your OS and the command that you are using to run SQANTI3?

**Comment by jchang97** [comment]
I am running on Linux and the command I am using is:
```

module load minimap2/2.17
module load perl/5.34.0
module load python/3.7.4
module load foss/2019b
module load kallisto/0.45.1
module load star/2.7.9a
module load foss/2020b
module load r/4.0.4

python "/data/gpfs/projects/punim1466/sw/SQANTI3-4.3/sqanti3_qc.py" -t 30 -n 10 --gtf "/data/gpfs/projects/punim1466/analysis/nanopore/isoform/novel_isoforms/gff/libA/isoform_annotated.filtered_libA.gff3" "/data/gpfs/projects/punim1466/db/refdata-gex-GRCh38-2020-A/genes/genes.gtf" "/data/gpfs/projects/punim1466/db/refdata-gex-GRCh38-2020-A/fasta/genome.fa" -g --cage_peak --coverage --force_ id_ignore --aligner_choice=minimap2
```

Thank you :)

**Comment by aarzalluz** [comment]
Hi @jchang97,

You don't really need to load those modules manually -just run `conda activate SQANTI3.env` (or if you gave the environment a different name, type that in) and then the python call to `sqanti3_qc.py`. All the necessary modules are installed when the environment is created. Please remember that, if you are running SQANTI3 as a job in a queue system (e.g. SLURM) instead of locally, you should use `source activate SQANTI3.env` instead.

**Comment by jchang97** [comment]
Sorry for the late response, but it is now working thank you so much for your help, really appreciate it!

**Comment by oucstar** [comment]
@aarzalluz ,so sorry to bother you,I have the same 
error message,I am running on Linux and the command I am using is:source activate SQANTI3.env,I was able to successfully create the conda environment and have activated it before running sqanti3_qc.py,I am just getting this error when running sqanti3_qc.py:

Unable to import BCBio! Please make sure bcbiogff is installed.

However, it seems that it's in my pip list:

$ pip list
Package              Version
-------------------- -------
bcbio-gff            0.6.9

Looking forward to your reply,Thank you!

**Comment by sum732** [comment]
Hello @aarzalluz,

I am facing the same as well. Followed the steps to install the latest version: `SQANTI3_v5.1.1`

showing the same error `python sqanti3_qc.py -h
Unable to import BCBio! Please make sure bcbiogff is installed.`

```
 pip list | grep "bcbio-gff"
bcbio-gff            0.6.9
```
I am using `source activate SQANTI3_v5.1.1` to activate the SQANTI3 env

Once inside the env, i tried to install the bcbio-gff using conda, but no affect. 

Any suggestions to fix this issue?

Many Thanks for supporting SQANTI3.

Best,
SM

**Comment by Dongxu-Zheng** [comment]
> Hello @aarzalluz,
> 
> I am facing the same as well. Followed the steps to install the latest version: `SQANTI3_v5.1.1`
> 
> showing the same error `python sqanti3_qc.py -h Unable to import BCBio! Please make sure bcbiogff is installed.`
> 
> ```
>  pip list | grep "bcbio-gff"
> bcbio-gff            0.6.9
> ```
> 
> I am using `source activate SQANTI3_v5.1.1` to activate the SQANTI3 env
> 
> Once inside the env, i tried to install the bcbio-gff using conda, but no affect.
> 
> Any suggestions to fix this issue?
> 
> Many Thanks for supporting SQANTI3.
> 
> Best, SM

Hi, please check #186 Caspar solved the problem.
