### ISSUE TITLE
ModuleNotFoundError: No module named 'bx' when "python sqanti3_qc.py --help"  

### ISSUE THREAD

**Issue by wzhang42** [ConesaLab/SQANTI3#143]
Hi, ConesaLa,
    Thanks for your developing SQANTI package for long read transcript characterization and QC.  I think that I follow the instruction  (https://github.com/ConesaLab/SQANTI3/wiki/Dependencies-and-installation) to download and install SQANTI.     
  I succeed in 
  1)   conda env create -f SQANTI3.conda_env.yml
  2.)  conda activate SQANTI3.env
   When I am at SQANTI3.env  terminal and type "python sqanti3_qc.py --help",   it then report the following error messages:
**Traceback (most recent call last):
  File "sqanti3_qc.py", line 28, in <module>
    from indels_annot import calc_indels_from_sam
   File "/SQANTI/SQANTI3-4.3/utilities/indels_annot.py", line 6, in <module>
    from bx.intervals import Interval
ModuleNotFoundError: No module named 'bx'**
Additionally, I use "pip list" and found most of the Python related libraries/packages are there.
.....
bcbio-gff            0.6.6
**biopython            1.79
bx-python            0.8.13
Cython               0.29.28**
dill                 0.3.4
edlib                1.3.9
gffutils             0.10.1
intervaltree         3.1.0
numpy                1.22.3
pandas               1.4.2

**Comment by sparthib** [comment]
Hi @aarzalluz , I have encountered the same issue, I am on version 5.2.1 and used the yml file to build my conda environment. I checked the list of packages I have using `conda list` and bx-python does exist, so I am not sure what the issue is. Any help would be appreciated. Thanks!

**Comment by carolinamonzo** [comment]
Hi @sparthib, that's very strange, it's one of the packages installed when you install the SQANTI3 environment. Did your installation give any errors? It looks like an installation problem in your setup.
In any case, you can solve this by installing bx-python on the activated conda environment.

**Comment by sparthib** [comment]
Thanks @carolinamonzo , it got solved after I manually installed bx-python. I am getting another error now. I looked through other issues to find that people downgraded to `biopython==1.75`, but when I do that I am getting this error 

```
File "/users/sparthib/SQANTI3/sqanti3_qc.py", line 29, in <module>
    from rt_switching import rts
  File "/users/sparthib/SQANTI3/utilities/rt_switching.py", line 6, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
```

As far as I understand, this is related to the biopython module, I am not sure what I am supposed to be doing here. 

Thanks,
Sowmya

**Comment by carolinamonzo** [comment]
Hi @sparthib this is super weird. Did you make a new conda environment for sqanti3 using the SQANTI3.conda_env.yml file that is currently in the SQANTI3 repository? Are you loading it? It should already have the correct version of biopython. 

conda env create -f SQANTI3.conda_env.yml
conda activate SQANTI3.env

Once activated you should see (SQANTI.env) before your prompt.

**Comment by sparthib** [comment]
@carolinamonzo the issue was that `biopython` and `bcbio-gff` would show up when I used `conda list` when I installed them using `conda install` but turns out they didn't show up when I did `pip list`. They were only recognized when I installed them using `pip`.
