### ISSUE TITLE
Cython module not found when installing cDNA_Cupcake

### ISSUE THREAD

**Issue by DrOllyGomez** [ConesaLab/SQANTI3#144]
Bug and Context:
-Followed install instructions for SQANTI3 as in page "wiki/Dependencies-and-installation"
--with change: we have miniconda3 rather than Anaconda, if that's relevant (version conda 4.10.3)
-success in steps 0-3 (ie from beginning to gtfToGenePred
-downloaded cDNA_Cupcake as in step 4
-issued "python setup.py build" as per instruction, got........
(SQANTI3.env) mike.harbour@bioinf3:~/SQANTI3/SQANTI3-4.3/cDNA_Cupcake$ python setup.py build
Traceback (most recent call last):
  File "/home/mike.harbour/SQANTI3/SQANTI3-4.3/cDNA_Cupcake/setup.py", line 4, in <module>
    from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'

am using
-Ubuntu release 20.04.3

Grateful for any help and advice.
Thanks in advance
Mike

**Comment by aarzalluz** [comment]
To fix this, you just need to install cython manually in your conda environment before setting up cDNA_Cupcake.

We are currently working on a major release of SQANTI3 that will include little enhancements such as this one, i.e. installing cython when building the conda environment. We expect it to be available within the next few days. 

Best,

Ángeles

**Comment by DrOllyGomez** [comment]
Thankyou very much! I installed Cython in the conda environment using pip, The build of cDNA-cupcake went fine.
I'm starting with SQANTI3 this week! Best
Mike
