### ISSUE TITLE
Correct encoding of CAGE/polyA columns (inconsistent logical values)

### ISSUE THREAD

**Issue by aarzalluz** [ConesaLab/SQANTI3#148]
Some **logical** columns in the SQANTI3 QC classification file still have lowercase TRUE/FALSE values (i.e. True/False). This is automatically corrected when table is read with tidyverse functions (e.g. `read_tsv()`) but not when loaded with base R functions such as `read.table()` (done in ML filter).

Problematic columns:
- `within_CAGE_peak`
- `within_polyA_site`

Fix in next release.

**Comment by aarzalluz** [comment]
Solved in v5.0 (updated 1st June 2022).

**Comment by ray1919** [comment]
I found there are both `within_cage_peak` and `within_CAGE_peak` in `SQANTI3_report.R`, I think all terms are case-sensitive in function like `STM_function`

Another problem,

```
x["within_cage_peak"]=="True"
```

It is a logical value, should not be treated as character.

**Comment by aarzalluz** [comment]
Noted, thanks!

**Comment by FJPardoPalacios** [comment]
Updated!
