### ISSUE TITLE
Could you please tag your project.

### ISSUE THREAD

**Issue by fizwit** [ConesaLab/SQANTI3#15]
To promote reproducible science, could you please use git tags. Creating a tag also creates a release for your project. We require tagged releases when building scientific software.  Pulling from the master is not reproducible.

I would also recommend using at least a 3 digit semantic versioning scheme; Magor.Minor.Patch.  Please do not
follow the git examples by putting a "v" as the leading character. Github will create a "release" when the tag is pushed.

thanks for making your software available

```
git tag 1.0.0
git tag push origin 1.0.0
```

**Comment by Magdoll** [comment]
This is now tagged.
