### ISSUE TITLE
Question: Short_reads parameters

### ISSUE THREAD

**Issue by mad-scientist-in-training** [ConesaLab/SQANTI3#150]
Hello, 

I'm considering using the --short-reads option when running SQANTI3 - I just have a question about using this parameter. In the documentation, it says that SQANTI3 uses Kallisto or STAR to quantify read counts for the short reads, but are these counts being quantified against the provided primary reference assembly file (like from Gencode or Ensembl) or is it calculating the counts against the provided set of transcripts that I just ran through cupcake_collapse?

Thanks so much for the help, 

Camille

**Comment by aarzalluz** [comment]
Hi @mad-scientist-in-training,

SQANTI3 will quantify the long read defined transcripts. The whole point is to use short read-based information -such as junction coverage, overall isoform expression, the TSS ration, etc.- to perform quality control of the isoforms and be able to tell true from false positive isoforms apart.

Please, keep in mind that we do not recommend using this quantification for downstream analysis -you should filter the unreliable isoforms and then quantify the curated transcriptome again with your preferred quantification method.

I hope that helps!

Ángeles

**Comment by mad-scientist-in-training** [comment]
Gotcha - thanks so much!!

Best, 

Camille
