### ISSUE TITLE
JSON file not filtering appropriately for Rules Filter script

### ISSUE THREAD

**Issue by ryanpe13002** [ConesaLab/SQANTI3#151]
To whom it may concern,

I am trying to run a filter script using "sqanti3_filter.py rules" using the attached JSON file. I structured it according to the example provided in the wiki, and am trying to implement the ruleset attached below. The problem is, the algorithm is plainly NOT filtering according to the criteria I laid out (filtering reasons outfile attached here: [BRCA_PacBio_v1.filter1_filtering_reasons.txt](https://github.com/ConesaLab/SQANTI3/files/8782404/BRCA_PacBio_v1.filter1_filtering_reasons.txt)).

For example, minimum coverage is listed as a criteria in all but incomplete splice match category, but low minimum coverage is not listed **anywhere** in the filtering reasons outfile. Further, NIC and NNIC are frequently filtered for reasons of diff_to_gene_TSS, diff_to_gene_TTS, etc., which are not criteria for those categories in the ruleset below.

What am I doing wrong? I must be making a mistake in how I am configuring the JSON file, but I cannot see where it is, and am having difficulty troubleshooting. Any guidance on how to appropriately structure the JSON file, or where the error is coming from, would be deeply appreciated.

Thanks so much,
Ryan Englander
MD/PhD Candidate, Jackson Laboratory for Genomic Medicine

Ruleset:
**FSM**
- perc_A_downstream_TTS < 80% **AND** RTS_stage = FALSE **AND** bite = FALSE

**ISM**
- perc_A_downstream_TTS < 80% **AND** RTS_stage = FALSE **AND** bite = FALSE **AND** (dist_to_CAGE_peak = [-99,99] **OR** diff_to_gene_TSS = [-99,99]) **AND** (polyA_motif_found = TRUE **OR** diff_to_gene_TTS = [-99,99])

**NIC**
- perc_A_downstream_TTS < 80% **AND** RTS_stage = FALSE **AND** bite = FALSE **AND** ((min_cov >= 10 **AND** all_canonical = "canonical") **OR** (min_cov >= 50 **AND** all_canonical = "noncanonical"))

**NNIC** (same as NIC)
- perc_A_downstream_TTS < 80% **AND** RTS_stage = FALSE **AND** bite = FALSE **AND** ((min_cov >= 10 **AND** all_canonical = "canonical") **OR** (min_cov >= 50 **AND** all_canonical = "noncanonical"))

**Rest**
- perc_A_downstream_TTS < 80% **AND** RTS_stage = FALSE **AND** bite = FALSE **AND** min_cov >= 10 **AND** all_canonical = "canonical"

**Comment by FJPardoPalacios** [comment]
Hi @ryanpe13002 !

I'm not surprised at all about the unexpected output of the filtering script since yesterday we came up with a bug in the code and I guess that you downloaded SQANTI3 at least 24h ago. My apologies for that. It was a problem with the iteration of the rules, that's why you only find out reasons to exclude an isoform that were defined in the first two rules (FSM and ISM rules).

The bug should be already fixed in the repository (adc8af18ccaf77bc937203494110b0e6d2796778) , please try to update the code and run the filter using the same JSON. 

Please, let me know if there is still any issue. I'm sorry about this inconvenience, but we are working on improving and polishing the code, so any help with the testing will be highly appreciated.

Bests,
Fran

**Comment by ryanpe13002** [comment]
Thank you so much @FJPardoPalacios ! My apologies, I'm not super fluent in Github - how do I download the script from this particular repository? Thank you so much for your help!

Kindest regards,
Ryan

**Comment by ryanpe13002** [comment]
Hi @FJPardoPalacios ,

I downloaded the new repository, and the Rules Script looks to be filtering according to the JSON file appropriately.

However, I am running into a new problem where the "filtering reasons" file does not include all of the isoforms called as artifacts in the "classifications" output file. I have attached an Excel file showing the differences in the numbers in "Discrepancies.xlsx", and have also attached the "filtering reasons" files (classification file was too large). The script and JSON used were the same as above.

[Discrepancies.xlsx](https://github.com/ConesaLab/SQANTI3/files/8789810/Discrepancies.xlsx)
[BRCA_PacBio_v1.filter1_filtering_reasons.txt](https://github.com/ConesaLab/SQANTI3/files/8789811/BRCA_PacBio_v1.filter1_filtering_reasons.txt)

I will keep looking into this issue and will let you know if I find anything.

**Comment by ryanpe13002** [comment]
To whom it may concern,

I've taken a look at the discrepancy, and it seems that anything called as mono-exon (either mono-exon alone or mono-exon by intron retention) is not being given a filtering reason(s) on the filtering_reasons.txt file. My supposition is that the "NA" values that are returned as a result of a transcript being a mono-exon are causing the discrepancy somewhere.

I have attached the classification data from the group of transcripts for which no filtering reasons were provided, in case that is helpful for fixing the bug.

[No_filtering_reason_given.txt](https://github.com/ConesaLab/SQANTI3/files/8808937/No_filtering_reason_given.txt)

**Comment by aarzalluz** [comment]
> You can download it from the main page of [SQANTI3 repository](https://github.com/ConesaLab/SQANTI3) just by clicking in the green "Code" button and choosing "Download zip".
> 
> If you cloned the repository, you can simply do `git pull` and all the changes that were made in the code will be updated in your local folder.
> 
> Bests, Fran

**Warning to SQ3 users:** SQANTI3 v5.0 now contains a version of `sqanti3_filter.py` that fixes the reported bug in the rules filter (we have removed v5.0 and released it again today, i.e. 1st June 2022). We do not recommend cloning the repo for installation -instead, please download the latest stable SQANTI3 release. Installation instructions are available [here](https://github.com/ConesaLab/SQANTI3/wiki/Dependencies-and-installation).

**Comment by aarzalluz** [comment]
Fixed in v5.1
