### ISSUE TITLE
sqanti3_qc fails in Singularity container because SQANTI3_report.R needs write access for temporary files

### ISSUE THREAD

**Issue by svigneau** [ConesaLab/SQANTI3#152]
sqanti3_qc fails when running within a Singularity container because SQANTI3_report.R needs write-access for temporary files, and Singularity containers are read-only. This happens, for instance, when trying to run sqanti3_qc in a Snakemake workflow using containers.

The issue arises from the rmarkdown::render calls at the end of the script. A simple fix is to add "intermediates_dir = output_directory" to this function's arguments, instead of using the default value which corresponds to the script's directory.

Here is the command to quickly perform the substitution (e.g., in a Dockerfile):

```sed -i "s\rmarkdown::render(input = paste(utilities.path, "/report_qc/SQANTI3_report.Rmd", sep = "/"), output_dir =  output_directory, output_file=\rmarkdown::render(input = paste(utilities.path, "/report_qc/SQANTI3_report.Rmd", sep = "/"), output_dir =  output_directory, intermediates_dir = output_directory, output_file=\g' SQANTI3-5.0/utilities/report_qc/SQANTI3_report.R```

**Comment by aarzalluz** [comment]
Hi @svigneau,

Thank you for reporting this. If you have time and have already edited the code in your forked version of the repo, could you submit a PR? No worries if not -I have marked it as an enhancement so that @FJPardoPalacios or myself can make the change before the next release of SQ3. 

Best,

Ángeles

**Comment by aarzalluz** [comment]
Fixed in v5.1
