### ISSUE TITLE
SQANTI incorrectly categorizing mono-exonic transcripts

### ISSUE THREAD

**Issue by ryanpe13002** [ConesaLab/SQANTI3#153]
To whom it may concern,

I am working with SQANTI3 QC data for a long-read transcriptome I have built, and I am running into some strange outputs from my mono-exonic by substitution novel-in-catalog sequences.

![image](https://user-images.githubusercontent.com/65777056/171295353-872c27f9-a240-4979-bb58-d144148fdac2.png)

For instance, in the attached image, you can clearly see that the novel transcript PB.1004.6 is an incomplete splice match to ENST00000465645.1 (confirmed by looking at the GTF coordinates - both transcripts end on chr1:28238098). However, SQANTI3 is classifying this transcript as NIC/mono-exonic by intron retention, presumably because of overlap between the start of PB.1006.4 and the end of the second exon in ENST00000335514.10.

Why is this the case? Is the NIC category given priority over ISM? Thanks so much!

GTF of all reference transcripts from that gene + PB.1006.4 for reference:
chr1	.	transcript	28236445	28238098	.	+	.	gene_id "PB.1004"; transcript_id "PB.1004.6";
chr1	.	exon	28236445	28238098	.	+	.	gene_id "PB.1004"; transcript_id "PB.1004.6";
chr1	HAVANA	transcript	28236154	28238098	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000465645.1"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-202"; level 2; protein_id "ENSP00000437337.1"; transcript_support_level "1"; hgnc_id "HGNC:871"; tag "basic"; tag "CCDS"; ccdsid "CCDS44096.1"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009842.2";
chr1	HAVANA	exon	28236154	28236270	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000465645.1"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-202"; exon_number 1; exon_id "ENSE00001897027.1"; level 2; protein_id "ENSP00000437337.1"; transcript_support_level "1"; hgnc_id "HGNC:871"; tag "basic"; tag "CCDS"; ccdsid "CCDS44096.1"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009842.2";
chr1	HAVANA	exon	28236361	28238098	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000465645.1"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-202"; exon_number 2; exon_id "ENSE00001876539.1"; level 2; protein_id "ENSP00000437337.1"; transcript_support_level "1"; hgnc_id "HGNC:871"; tag "basic"; tag "CCDS"; ccdsid "CCDS44096.1"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009842.2";
chr1	HAVANA	transcript	28236124	28238100	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000335514.10"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-201"; level 2; protein_id "ENSP00000335203.5"; transcript_support_level "1"; hgnc_id "HGNC:871"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; ccdsid "CCDS319.1"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009841.2";
chr1	HAVANA	exon	28236124	28236270	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000335514.10"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-201"; exon_number 1; exon_id "ENSE00001815223.2"; level 2; protein_id "ENSP00000335203.5"; transcript_support_level "1"; hgnc_id "HGNC:871"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; ccdsid "CCDS319.1"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009841.2";
chr1	HAVANA	exon	28236361	28236452	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000335514.10"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-201"; exon_number 2; exon_id "ENSE00002097527.1"; level 2; protein_id "ENSP00000335203.5"; transcript_support_level "1"; hgnc_id "HGNC:871"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; ccdsid "CCDS319.1"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009841.2";
chr1	HAVANA	exon	28237837	28238100	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000335514.10"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-201"; exon_number 3; exon_id "ENSE00001153845.6"; level 2; protein_id "ENSP00000335203.5"; transcript_support_level "1"; hgnc_id "HGNC:871"; tag "basic"; tag "MANE_Select"; tag "appris_principal_1"; tag "CCDS"; ccdsid "CCDS319.1"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009841.2";
chr1	HAVANA	transcript	28236109	28238105	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000497986.5"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-204"; level 2; protein_id "ENSP00000435579.1"; transcript_support_level "2"; hgnc_id "HGNC:871"; tag "basic"; tag "CCDS"; ccdsid "CCDS320.1"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009843.2";
chr1	HAVANA	exon	28236109	28236270	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000497986.5"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-204"; exon_number 1; exon_id "ENSE00001909763.1"; level 2; protein_id "ENSP00000435579.1"; transcript_support_level "2"; hgnc_id "HGNC:871"; tag "basic"; tag "CCDS"; ccdsid "CCDS320.1"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009843.2";
chr1	HAVANA	exon	28236361	28236452	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000497986.5"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-204"; exon_number 2; exon_id "ENSE00002097527.1"; level 2; protein_id "ENSP00000435579.1"; transcript_support_level "2"; hgnc_id "HGNC:871"; tag "basic"; tag "CCDS"; ccdsid "CCDS320.1"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009843.2";
chr1	HAVANA	exon	28237761	28238105	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000497986.5"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-204"; exon_number 3; exon_id "ENSE00001918899.1"; level 2; protein_id "ENSP00000435579.1"; transcript_support_level "2"; hgnc_id "HGNC:871"; tag "basic"; tag "CCDS"; ccdsid "CCDS320.1"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009843.2";
chr1	HAVANA	transcript	28236142	28246906	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000468425.2"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-203"; level 1; protein_id "ENSP00000435341.1"; transcript_support_level "2"; hgnc_id "HGNC:871"; tag "basic"; tag "exp_conf"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009844.2";
chr1	HAVANA	exon	28236142	28236270	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000468425.2"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-203"; exon_number 1; exon_id "ENSE00002123006.2"; level 1; protein_id "ENSP00000435341.1"; transcript_support_level "2"; hgnc_id "HGNC:871"; tag "basic"; tag "exp_conf"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009844.2";
chr1	HAVANA	exon	28236361	28236452	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000468425.2"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-203"; exon_number 2; exon_id "ENSE00002097527.1"; level 1; protein_id "ENSP00000435341.1"; transcript_support_level "2"; hgnc_id "HGNC:871"; tag "basic"; tag "exp_conf"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009844.2";
chr1	HAVANA	exon	28246589	28246906	.	+	.	gene_id "ENSG00000130770.18"; transcript_id "ENST00000468425.2"; gene_type "protein_coding"; gene_name "ATP5IF1"; transcript_type "protein_coding"; transcript_name "ATP5IF1-203"; exon_number 3; exon_id "ENSE00001880910.2"; level 1; protein_id "ENSP00000435341.1"; transcript_support_level "2"; hgnc_id "HGNC:871"; tag "basic"; tag "exp_conf"; havana_gene "OTTHUMG00000003533.3"; havana_transcript "OTTHUMT00000009844.2";

**Comment by aarzalluz** [comment]
@ryanpe13002 -bug fixed by @lkondratova, improvements will become available in the next SQ3 release.
