### ISSUE TITLE
BioReaders error

### ISSUE THREAD

**Issue by apn83** [ConesaLab/SQANTI3#16]
HI,

I installed it as per instructions. When I run it, I get the following error:

`python sqanti3_qc.py -h
sqanti3_qc.py:19: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import defaultdict, Counter, namedtuple, Iterable
Traceback (most recent call last):
  File "sqanti3_qc.py", line 50, in <module>
    from err_correct_w_genome import err_correct
  File "/home/nagaraap/Downloads/Softwares/SQANTI2/cDNA_Cupcake/sequence/err_correct_w_genome.py", line 9, in <module>
    import BioReaders
  File "/home/nagaraap/Downloads/Softwares/SQANTI2/cDNA_Cupcake/sequence/BioReaders.py", line 419
    print "qStart:", self.qStart
                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("qStart:", self.qStart)?`

The python version is 3.7.6. How do I resolve it ?

Thanks.

**Comment by Magdoll** [comment]
Hi @gitarunprasanna83 ,
Are you using the latest version of Cupcake? It looks like you may have an earlier version of Cupcake scripts that were written in Python 2, not Python 3.
Please download the latest Cupcake and compile using `python setup.py build; python setup.py install`

-Liz

**Comment by gitarunprasanna83** [comment]
Hi Liz,
The git clone gets me the following:

Finished processing dependencies for cupcake==12.1.0. This seems to be latest. I still get the same error !

Thanks,
Arun

> Hi @gitarunprasanna83 ,
> Are you using the latest version of Cupcake? It looks like you may have an earlier version of Cupcake scripts that were written in Python 2, not Python 3.
> Please download the latest Cupcake and compile using `python setup.py build; python setup.py install`
> 
> -Liz

**Comment by Magdoll** [comment]
Hi @gitarunprasanna83 ,
Did you actually compile Cupcake after you download the latest version?
Does this error still exist?
-Liz

**Comment by Magdoll** [comment]
Closing unless OP opens again.
