### ISSUE TITLE
gmst.pl fails at ORF finding

### ISSUE THREAD

**Issue by maysonlin** [ConesaLab/SQANTI3#163]
Greetings, 
             I am currently using SQUANTI 3.0-5.0 to run quality control, but I have received some error messages:

```
`Reading genome fasta /home/slin023/Pregina.p_ctg.removedBac.fa....
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
Traceback (most recent call last):
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 2471, in <module>
    main()
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 2454, in main
    run(args)
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 1840, in run
    orfDict = correctionPlusORFpred(args, genome_dict)
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 597, in correctionPlusORFpred
    if subprocess.check_call(cmd, shell=True, cwd=gmst_dir)!=0:
  File "/home/slin023/.conda/envs/SQANTI3.env/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'perl /home/slin023/SQANTI3-5.0/utilities/gmst/gmst.pl -faa --strand direct --fnn --output /home/slin023/SQANTI3-5.0/GMST/GMST_tmp /home/slin023/SQANTI3-5.0/isoseq_corrected.fasta' returned non-zero exit status 1.` 
```

I tried to refer it back to [same issue post back in 2019](https://github.com/Magdoll/SQANTI2/issues/42) Here are lists of isoseq data, I am not sure which one is optimal for SQANTI3:
1. I have fasta isoseq out after "clustering" step using [Isoseq 3](https://github.com/PacificBiosciences/IsoSeq/blob/master/isoseq-clustering.md)

2. Isoseq fastq files 

3. Isoseq mapping to genome using GMAP .gff file

Here is my script:

```
module load miniconda3-4.5.11-gcc-8.2.0-oqs2mbg


cd /home/slin023/SQANTI3-5.0

source activate SQANTI3.env 


export PYTHONPATH=/home/slin023/cDNA_Cupcake/sequence/

python sqanti3_qc.py /home/slin023/SQANTI3-5.0/isoseq.gff  /home/slin023/SQANTI3-5.0/Trinity-GG.fasta.transdecoder.gff3 /home/slin023/Pregina.p_ctg.removedBac.fa --force_id_ignore --SR_bam /home/data/FLAG/PhormiaMaggotAging/aging/TrimMapping/trimSorted.out.bam --isoAnnotLite --gff3 /home/slin023/SQANTI3-5.0/Trinity-GG.fasta.transdecoder.gff3 -t 16
```

I don't have transcriptome .gtf as reference, so I use trandecoder output of gff3 file. I am not sure if it supports that. And I am using blowfly species. If there is any suggestion, please let me know. Thank you!

**Comment by aarzalluz** [comment]
Hi @maysonlin,

Thank you for using SQANTI3.

Regarding your first question (GMST errors), please see my answer to #11. As we are unable to fix GeneMark issues, I suggest running SQANTI3 with `--skipORF` to prevent these errors.

Regarding preferred data for running SQANTI3, we recommend running post-clustering or post-collapse data, that is, the output of IsoSeq3 clustering or the output of cDNA Cupcake. See our [recommended pre-processing workflow](https://github.com/ConesaLab/SQANTI3/wiki/Introduction-to-SQANTI3#workflow) section in the Wiki for details. We do recommend using a GTF, rather than FASTA sequences, as your input transcriptome -just like you are doing.

As for the reference GTF, please keep in mind that SQANTI3 is unable to work without a reference transcriptome annotation. If your species does not have one, SQ3 might not be the right fit for you to do quality control of your long read transcriptome.

I hope that helps.

Ángeles

**Comment by maysonlin** [comment]
Hi, 
      Thank you for the response! I actually saw the same issue post on GitHub before, so I should have mentioned I did try add `-skipORF`, but it shows something was missing:
```
      R scripting front-end version 4.1.3 (2022-03-10)
Error corrected FASTA /home/slin023/SQANTI3-5.0/isoseq_corrected.fasta already exists. Using it...
WARNING: Skipping ORF prediction because user requested it. All isoforms will be non-coding!
WARNING: All input isoforms were predicted as non-coding
/home/slin023/SQANTI3-5.0/Trinity-GG.fasta.transdecoder.gff3 doesn't appear to be a GTF file (GFF not supported by this program)
Write arguments to /home/slin023/SQANTI3-5.0/isoseq.params.txt...
**** Running SQANTI3...Transcriptome....
**** Parsing provided files....t):
Reading genome fasta /home/slin023/Pregina.p_ctg.removedBac.fa....odule>
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....3_qc.py", line 2454, in main
Traceback (most recent call last):
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 2471, in <module>
    main()exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, s  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 2454, in main
    run(args)/slin023/SQANTI3-5.0/sqanti3_qc.py", line 667, in reference_parser
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 1843, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene = reference_parser(args, list(genome_dict.keys()))
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 667, in reference_parser
    for r in genePredReader(referenceFiles):
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 137, in __init__
    self.f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/slin023/SQANTI3-5.0/refAnnotation_isoseq.genePred'
```
I am not if it's missing because of skipORF or not.

**Comment by aarzalluz** [comment]
Hi @maysonlin,

In this case, the error appears to be that the format of your reference transcriptome file is not correct, and SQ3 is therefore unable to convert it to genePred format (a step requried for isoform classification) -thus the first error message in your log:

```
/home/slin023/SQANTI3-5.0/Trinity-GG.fasta.transdecoder.gff3 doesn't appear to be a GTF file (GFF not supported by this program)
```

According to this and the call to SQ3 that you showed in your response above, you seem to be using a GFF3 file as your reference transcriptome, which is not correct -as mentioned extensively in the documentation, our tool works with GTF transcriptome annotation files. 

What species are you working on? If your species has a reference transcriptome, you should be able to find the GTF reference file in your preferred reference database.

Ángeles

**Comment by maysonlin** [comment]
Hi, 
      Thank you for the response! My species is Phormia regina, but the reference transcriptome link provided on the tutorial only has human and mouse. It does not include blowfly, so I downloaded  _Drosophila melanogaster_ transcriptome gtf as input file. I still shows the similar issue:

 ```
R scripting front-end version 4.1.3 (2022-03-10)
Error corrected FASTA /home/slin023/SQANTI3-5.0/isoseq_corrected.fasta already exists. Using it...
WARNING: Skipping ORF prediction because user requested it. All isoforms will be non-coding!
WARNING: All input isoforms were predicted as non-coding
WARNING: ref annotation contains chromosomes not in genome: X,mitochondrion_genome,3L,211000022278449,211000022280494,3R,211000022278436,Y_mapped_Scaffold_9_D15
73,4,211000022278978,211000022280703,Unmapped_Scaffold_8_D1580_D1567,211000022279188,2R,211000022280347,Unmapped_Scaffold_60_D1601,211000022278279,211000022279165,rDNA,211000022279681,2L,Unmapped_Scaffold_4_D1555_D1692,211000022280341,211000022280481,211000022279392,Y,211000022280328,211000022278760,211000022279264

**** Parsing Isoforms....
/home/slin023/SQANTI3-5.0/isoseq_corrected.gtf doesn't appear to be a GTF file (GFF not supported by this program)
Write arguments to /home/slin023/SQANTI3-5.0/isoseq.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /home/slin023/Pregina.p_ctg.removedBac.fa....
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
/home/slin023/SQANTI3-5.0/refAnnotation_isoseq.genePred already exists. Using it.
Traceback (most recent call last):
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 2471, in <module>
    main()
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 2454, in main
    run(args)
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 1846, in run
    isoforms_by_chr = isoforms_parser(args)
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 714, in isoforms_parser
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/home/slin023/.conda/envs/SQANTI3.env/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/slin023/SQANTI3-5.0/utilities/gtfToGenePred /home/slin023/SQANTI3-5.0/isoseq_corrected.gtf /home/slin023/SQANTI3-5.0/isoseq_corrected.genePred -genePredExt -allErrors -ignoreGroupsWithoutExons' returned non-zero exit status 255.
```

Here is my updated command:
`python sqanti3_qc.py /home/slin023/SQANTI3-5.0/isoseq.gtf  /home/slin023/SQANTI3-5.0/Drosophila_melanogaster.BDGP6.32.107.gtf /home/slin023/Pregina.p_ctg.removedBac.fa --force_id_ignore --SR_bam /home/data/FLAG/PhormiaMaggotAging/aging/TrimMapping/trimSorted.out.bam  --skipORF --isoAnnotLite --gff3 /home/slin023/SQANTI3-5.0/Trinity-GG.fasta.transdecoder.gff3 -t 16`

**Comment by aarzalluz** [comment]
Hi @maysonlin,

First, seems that you are running SQANTI3 in the same folder as your previous runs. Whenever found, SQANTI3 re-uses extant intermediate files. Since your previous runs did not complete/gave errors, could you delete everything in your SQANTI3 output folder and run the program again? Just to make sure that a corrupted intermediate file being used is not the source of the error.

Other than that, I see the following warning in your log:
`/home/slin023/SQANTI3-5.0/isoseq_corrected.gtf doesn't appear to be a GTF file (GFF not supported by this program)`

There might be something wrong with your file's format. Could you show the first few lines here?

Finally, watch out for this warning as well: `WARNING: ref annotation contains chromosomes not in genome`. You should make sure that at least some of the chromosomes in your reference genome match those in your GTF files, otherwise, SQ3 will be unable to perform the classification.

Best,

Ángeles

**Comment by maysonlin** [comment]
Hi Angeles, 
               Thank you for the reply. I removed all output files, reran again, but found the same errors:
               
               `R scripting front-end version 4.1.3 (2022-03-10)
WARNING: Skipping ORF prediction because user requested it. All isoforms will be non-coding!
WARNING: All input isoforms were predicted as non-coding
WARNING: ref annotation contains chromosomes not in genome: rDNA,211000022279681,Y,211000022278760,211000022278978,3L,211000022278449,Y_mapped_Scaffold_9_D1573,2R,211000022280328,211000022280347,211000022
280703,211000022278279,Unmapped_Scaffold_4_D1555_D1692,Unmapped_Scaffold_60_D1601,211000022279392,3R,Unmapped_Scaffold_8_D1580_D1567,211000022280341,211000022279264,211000022280494,211000022279165,2110000
22278436,4,211000022279188,2L,mitochondrion_genome,211000022280481,X

**** Parsing Isoforms....
invalid gffGroup detected on line: ptg000002l_1 b2h     exon    326127  326134  0.000000        .       .       gene_id "nbis-gene-1"; transcript_id "nbisL2-exon-1"; 
GFF/GTF group nbisL2-exon-1 on ptg000001l_1., this line is on ptg000002l_1., all group members must be on same seq and strand
1 errors
Write arguments to /home/slin023/SQANTI3-5.0/isoseq.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /home/slin023/Pregina.p_ctg.removedBac.fa....
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
Traceback (most recent call last):
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 2471, in <module>
    main()
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 2454, in main
    run(args)
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 1846, in run
    isoforms_by_chr = isoforms_parser(args)
  File "/home/slin023/SQANTI3-5.0/sqanti3_qc.py", line 714, in isoforms_parser
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/home/slin023/.conda/envs/SQANTI3.env/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/slin023/SQANTI3-5.0/utilities/gtfToGenePred /home/slin023/SQANTI3-5.0/isoseq_corrected.gtf /home/slin023/SQANTI3-5.0/isoseq_corrected.genePred -genePredExt -allErrors -ignoreGroupsWithoutExons' returned non-zero exit status 255.`
               
               
               
               
                Here are the few lines of "isoseq_corrected.gtf":
`##gtf-version 3
ptg000001l_1    b2h     gene    492     28136125        0       .       .       gene_id "nbis-gene-1"; ID "nbis-gene-1"; grp "m64140_210607_173521/15532832/ccs"; pri "4"; src "PB";
ptg000001l_1    b2h     transcript      492     28136125        0       .       .       gene_id "nbis-gene-1"; transcript_id "nbisL2-exon-1"; ID "nbisL2-exon-1"; Parent "nbis-gene-1"; grp "m64140_210607_173521/15532832/ccs"; original_biotype "rna"; pri "4"; src "PB";
ptg000291l_1    b2h     exon    492     662     0       .       .       gene_id "nbis-gene-1"; transcript_id "nbisL2-exon-1"; ID "exon-1990671"; Parent "nbisL2-exon-1"; grp "m64140_210607_173521/11731348/ccs"; pri "4"; src "PB";
ptg000039l_1    b2h     exon    1411    1823    0       .       .       gene_id "nbis-gene-1"; transcript_id "nbisL2-exon-1"; ID "exon-1084496"; Parent "nbisL2-exon-1"; grp "m64140_210607_173521/82904506/ccs"; pri "4"; src "PB";
ptg000039l_1    b2h     exon    1897    2037    0       .       .       gene_id "nbis-gene-1"; transcript_id "nbisL2-exon-1"; ID "exon-1084497"; Parent "nbisL2-exon-1"; grp "m64140_210607_173521/82904506/ccs"; pri "4"; src "PB";
ptg000039l_1    b2h     exon    2116    2282    0       .       .       gene_id "nbis-gene-1"; transcript_id "nbisL2-exon-1"; ID "exon-1084498"; Parent "nbisL2-exon-1"; grp "m64140_210607_173521/82904506/ccs"; pri "4"; src "PB";
ptg000095l_1    b2h     exon    2606    2630    0       .       .       gene_id "nbis-gene-1"; transcript_id "nbisL2-exon-1"; ID "exon-1784791"; Parent "nbisL2-exon-1"; grp "m64140_210607_173521/102106667/ccs"; pri "4"; src "PB";
ptg000126l_1    b2h     exon    2972    3103    0       .       .       gene_id "nbis-gene-1"; transcript_id "nbisL2-exon-1"; ID "exon-1902864"; Parent "nbisL2-exon-1"; grp "m64140_210607_173521/91750925/ccs"; pri "4"; src "PB";
`

Here are the lines of my command:
`python sqanti3_qc.py /home/slin023/SQANTI3-5.0/isoseq.gtf /home/slin023/SQANTI3-5.0/Drosophila_melanogaster.BDGP6.32.107.gtf /home/slin023/Pregina.p_ctg.removedBac.fa --force_id_ignore --SR_bam /home/data/FLAG/PhormiaMaggotAging/aging/TrimMapping/trimSorted.out.bam  --skipORF --isoAnnotLite -t 16  --gff3 /home/slin023/SQANTI3-5.0/Drosophila_melanogaster.BDGP6.32.107.gtf`

But I can see why those two  input file causes problem, so here are the list of my questions:

1. To make sure ref annotation contains chromosome in my genome, what will be appropriate gtf ref I can use and where I can download it? My species is Phormia regina, so it's diptera order. My genome is draft genome from PacBio HiFi reads library.
2. By flagging `--isoAnnotLite `, the manual says "a GFF3 file containing isoform-level functional annotations for a reference transcriptome (e.g. Ensembl) can also be supplied via the --gff3 flag.", so basically I have to find reference transcriptome GFF3 file from Ensembl  according to  the species of GTF input file ? I just try to find what and where will be appropriate for my model. 
                  I appreciate your patience and feedback. Any recommendation will be helpful for my analysis!

**Comment by aarzalluz** [comment]
Hi @maysonlin,

The information to answer both questions is available for users in the documentation, but I will try to give you some pointers here.

1. If you have built your own genome, I suppose you would need to find some sort of reference annotation that is built based on that genome -if not, you should use one of the reference genomes available in databases such as Ensembl, RefSeq, etc. which are generally accompanied by a matching reference transcriptome annotation. If these are not available for your species, you may be unable to run SQANTI3 -please keep in mind that SQ3 QC relies entirely on the reference annotation for both classification and to compute quality attributes.
2. Pre-annotated tappAS GFF3 files are only available for model organisms such as mouse, human, Drosophila, etc. The functional annotation GFF3 that we refer to is not equivalent to GFF3 files in reference databases. You can read more about this in the relevant SQ3 wiki sections.

Also, watch out for those `##` lines in your GTF, they may cause parsing problems as well. Those commented lines should be removed before using the file.

Given that the initial reason behind the issue (GMST problems) was addressed in one of my previous responses to this thread, I will close the issue now. Thank you for using SQANTI!

Best,

Ángeles
