### ISSUE TITLE
Please Update the Script in IsoAnnot Official Site

### ISSUE THREAD

**Issue by yueyaog** [ConesaLab/SQANTI3#171]
I appreciate you all created this amazing toolkit. I recently used the isoannot script that I downloaded from the [Tappas site](https://isoannot.tappas.org/isoannot-lite/). It has some very simply bugs. I fixed that for my own project. And I think your team might also fixed that in the [github repo](https://github.com/ConesaLab/SQANTI3/blob/master/utilities/IsoAnnotLite_SQ3.py). The website of  IsoAnnotLite were also referred by the acorde paper. I think you might want to update the download link to the updated script to avoid confusion from the users.

**Comment by psalguerog** [comment]
Hello @yueyaog, 

Thank you very much for bringing the problem to our attention. I have already updated the file.
If you have any questions, please do not hesitate to contact us.
