### ISSUE TITLE
A request for raw bed file of 16,104 transcripts in SQANTI paper

### ISSUE THREAD

**Issue by CrazyHsu** [ConesaLab/SQANTI3#172]
Hello,
Thanks for creating the amazing toolkit. I recently wanted to reproduce the pipeline you refered in the [SQANTI paper](https://genome.cshlp.org/content/28/3/396.full). But due to various software updates, I can't get the bed file of the 16,104 transcripts you mentioned in the article, can you provide one? Any help will appriciated.

**Comment by aarzalluz** [comment]
Hi @CrazyHsu,

While SQANTI3's development is based on the original SQANTI tool, it has grown to become a new, independent project. In addition, SQANTI has long been deprecated. As SQANTI3 developers, we are unable to provide what you are asking for.

My suggestion would be to email the authors of the original SQANTI paper to ask for files/recommendations on how to reproduce the pipeline.

Best,

Ángeles
