### ISSUE TITLE
Parameters used for internal STAR run

### ISSUE THREAD

**Issue by ryanpe13002** [ConesaLab/SQANTI3#173]
To whom it may concern,

We are wondering what internal parameters SQANTI3 uses when running STAR to get the *.SJ.out.tab and *BAM files. We are working on troubleshooting a pipeline we are building that uses SQANTI, and this info would be really helpful to us!

Thanks so much,
Ryan Englander

Anczukow lab, Jackson Laboratory

**Comment by aarzalluz** [comment]
Hi @ryanpe13002,

Thank you for using SQANTI3!

STAR is run internally by calling the [short_reads.py](https://github.com/ConesaLab/SQANTI3/blob/master/utilities/short_reads.py) script, located within the `utilites` folder. You can check the full STAR command there.

Tagging @FJPardoPalacios, who set up short-read data processing within SQANTI3 QC, in case he wants to add anything.

Best,

Ángeles

**Comment by FJPardoPalacios** [comment]
Hi @ryanpe13002 ,

SQANTI3 runs internally these commands:

1. To build the index (without using the reference annotation)

```
STAR --runThreadN <num cpus> --runMode genomeGenerate --genomeDir <index_dir> --genomeFastaFiles <fasta_genome> --outTmpDir <index_dir_tmp>

```

2. To map and get BAMS & SJ.out.tab files

```
STAR --runThreadN  <num cpus> --genomeDir <index_dir> --readFilesIn <read1> <read2> \
--outFileNamePrefix <sample_prefix> --alignSJoverhangMin  8 \
--alignSJDBoverhangMin 1 --outFilterType BySJout  --outSAMunmapped Within \
--outFilterMultimapNmax  20 --outFilterMismatchNoverLmax 0.04 \
--outFilterMismatchNmax 999 --alignIntronMin 20 --alignIntronMax 1000000 --alignMatesGapMax 1000000 \
--sjdbScore 1 --genomeLoad NoSharedMemory --outSAMtype BAM SortedByCoordinate --twopassMode Basic
```

The idea is to create a reference-independent index of the genome, so SJ detected won't be biased by prior annotations. For SJ detection we use the basic `--twopassMode`.

Bests,
Fran
