### ISSUE TITLE
Rescue candidate FASTA empty as no overlap between filtered isoforms fasta and rescue_candidates.tsv 

### ISSUE THREAD

**Issue by kudasonya** [ConesaLab/SQANTI3#176]
Hello SQANTI creators, 

Thank you for the tool. I am trying to run sqanti_rescue.py with 
```
sqanti3_rescue.py rules --isoforms 2022-08-sqanti3_out/filter_out/isoforms.filtered.fasta \
--gtf 2022-08-sqanti3_out/filter_out/isoforms.filtered.gtf \
-g $gencode_gtf -f $gencode_fa -k 2022-11-sqanti3_rescue_out/gencode.v40.annotation_classification.txt -o rescue_out \
-e none -d 2022-11-sqanti3_rescue_out --skip_report -j filter_tailored.json 2022-08-sqanti3_out/filter_out/isoforms.RulesFilter_result_classification.txt
```
but
`seqtk subseq 2022-08-sqanti3_out/filter_out/isoforms.filtered.fasta 2022-11-sqanti3_rescue_out/rescue_out_rescue_candidates.tsv > 2022-11-sqanti3_rescue_out/rescue_out_rescue_candidates.fasta` outputs an empty file, which I think is because there is no overlap between candidate ids and the ids in the isoforms fasta, however I don't understand how that can be. 

Kind regards, 

Sofia

**Comment by almart7** [comment]
Hello @kudasonya , we are working on your issue and will answer as soon as possible. Sorry for the inconvenience!

**Comment by aarzalluz** [comment]
Hi @kudasonya,

When running SQ3 rescue, you should always supply the `*.corrected.fasta` file to the `--isoforms` argument -that is, the FASTA output of SQ3 QC. 

The rescue algorithm uses this file to fetch the candidates sequences for mapping, where rescue candidates are artifacts that **did not pass** the filter and that SQ3 will try to rescue. Keep in mind that the `*.filtered.fasta` file only contains the isoforms that **passed** the filter, therefore, no rescue candidates can be found there. 

Could you try again and let me know if it works?

Best,

Ángeles

**Comment by kudasonya** [comment]
Hello Ángeles, 

I see my mistake now, that makes a lot of sense  :) Thank you very much for your clear explanation. sqanti3_rescue is working as expected. 

Kind regards, 

Sofia
