### ISSUE TITLE
Data frame SJ type error when running sqanti3_qc.py

### ISSUE THREAD

**Issue by dustyl259** [ConesaLab/SQANTI3#18]
I get this error when  `--skipORF` is implemented as well as when it is not. Here's my command:

`python /SQANTI3/sqanti3_qc.py m64120_200619_171832.collapsed.rep.fa ../annotations/Mus_musculus.GRCm38.100.gtf ../ref/GCA_000001635.9_GRCm39_genomic.fna`

Input fasta comes from cDNA_Cupcake 'collapse_isoforms_by_sam.py' (Pac Bio IsoSeq workflow) and reference annotation and reference genome are the latest mouse build Genbank accession GCA_000001635.9. 

Error is below:

`Error in `$<-.data.frame`(`*tmp*`, SJ_type, value = "__SJ") : 
  replacement has 1 row, data has 0
Calls: $<- -> $<-.data.frame
Execution halted
Traceback (most recent call last):
  File "/SQANTI3/sqanti3_qc.py", line 2289, in <module>
    main()
  File "/SQANTI3/sqanti3_qc.py", line 2273, in main
    run(args)
  File "/SQANTI3/sqanti3_qc.py", line 1892, in run
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/opt/conda/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/conda/envs/SQANTI3.env/bin/Rscript /SQANTI3/utilities//SQANTI3_report.R /scratch/newest_build_isoseq/m64120_200619_171832.collapsed.rep_classification.txt /scratch/newest_build_isoseq/m64120_200619_171832.collapsed.rep_junctions.txt /scratch/newest_build_isoseq/m64120_200619_171832.collapsed.rep.params.txt /SQANTI3/utilities/' returned non-zero exit status 1.`

Is this a data input issue or a SQANTI3 issue?

**Comment by Magdoll** [comment]
Hi @dustyl259 ,
Does this error still exist?

Can you confirm that the files `m64120_200619_171832.collapsed.rep_classification.txt`, `m64120_200619_171832.collapsed.rep_junctions.txt` are not empty?

-Liz

**Comment by dustyl259** [comment]
Hi Liz,

Yes, this error still exists. `m64120_200619_171832.collapsed.rep_classification.txt` is not empty but many of the fields are populated with "NA". `m64120_200619_171832.collapsed.rep_junctions.txt` only contains the header. It looks as though these files are waiting to be written to but the Rscript is throwing a data frame error.

Thanks for your response to this. Please let me know your thoughts.

-Dustin

**Comment by Magdoll** [comment]
Hi @dustyl259 ,
I see. the error is hence coming from the fact that `m64120_200619_171832.collapsed.rep_junctions.txt` file is empty. This definitely should not happen. Did any errors occur before this step? are you willing to share the input data `m64120_200619_171832.collapsed.rep.fa` for me to test? 
(it looks like your annotation + genome I can download from UCSC)

-Liz

**Comment by dustyl259** [comment]
Hi Liz,

No errors occurred before this step. Attached is my `m64120_200619_171832.collapsed.rep.fa` input file. Please let me know if you need anything else.

Thanks,
Dustin

[m64120_200619_171832.collapsed.rep.fa.txt](https://github.com/ConesaLab/SQANTI3/files/5031633/m64120_200619_171832.collapsed.rep.fa.txt)

**Comment by Magdoll** [comment]
Hi @dustyl259 ,
I have determined the cause to be because your annotation GTF and your reference genome do not match in coordinates.
You can tell because when you look at the classification files, nothing matches to the annotation.

I ended up using [mm10.fasta from UCSC ](https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/) and [Gencode vM25](https://www.gencodegenes.org/mouse/release_M25.html) and I got the results here:
https://www.dropbox.com/sh/5hlkgww57flwozk/AAAAF0Qt1kyV-1PYvQG2OR_Ua?dl=0

Let me know if you can replicate my result.

--Liz

**Comment by dustyl259** [comment]
Hi Liz,

Thanks for your response. What was your command? Which were the exact files you used (Comprehensive Gene Annotation? Basic? -- ALL?, CHR?, PRI?) I used mm10.fa.gz from UCSC and then the first and second Comprehensive annotations and got another error.

`Traceback (most recent call last):
  File "/SQANTI3/sqanti3_qc.py", line 2289, in <module>
    main()
  File "/SQANTI3/sqanti3_qc.py", line 2273, in main
    run(args)
  File "/SQANTI3/sqanti3_qc.py", line 1720, in run
    isoforms_info = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict)
  File "/SQANTI3/sqanti3_qc.py", line 1493, in isoformClassification
    isoform_hit = transcriptsKnownSpliceSites(refs_1exon_by_chr, refs_exons_by_chr, start_ends_by_gene, rec, genome_dict, nPolyA=args.window)
  File "/SQANTI3/sqanti3_qc.py", line 938, in transcriptsKnownSpliceSites
    seq_downTTS = str(genome_dict[trec.chrom].seq[pos_TTS:pos_TTS+nPolyA]).upper()
KeyError: 'CM000994.3'`

Here's one of my commands:

`python /SQANTI3/sqanti3_qc.py m64120_200619_171832.collapsed.rep.fa ../annotations/gencode.vM25.chr_patch_hapl_scaff.annotation.gtf ../ref/mm10.fa`

**Comment by dustyl259** [comment]
Hi Liz,

Nevermind, my problem was that I re-ran the command in the same directory that I previously did and because the "corrected" intermediate files (`Error corrected FASTA /scratch/newest_build_isoseq/m64120_200619_171832.collapsed.rep_corrected.fasta already exists. Using it...`) already existed, it used those. I created a new directory and ran this again and it worked. Thanks for your help with this. I understand it clearly says in the tutorial/documentation to "Make sure your annotation GTF is based on the correct ref genome version!"...I guess I just didn't know how to truly check for that. Thank you.
