### ISSUE TITLE
AssertionError with PolyA site data supplied

### ISSUE THREAD

**Issue by yuchen345** [ConesaLab/SQANTI3#181]
Hi
The polyA site BED file download  from the PolyASite atlas and pre-modified with your suggestion is supplied to sqanti3_qc.py via the --polyA_peak argument. 
Here is error
![图片](https://user-images.githubusercontent.com/71202087/217533877-295d0e67-f874-405f-b099-f599b4c3905b.png)
 
I did check the strand  symbol in this BED file and there is no feature labled with the ''. /unassigned''.
Any help would be greatly appreciated !

**Comment by aarzalluz** [comment]
Hi @yuchen345 -could you check whether any other of your input files has a `strand` field that could be undefined (for example, the input GTF)?

**Comment by yuchen345** [comment]
@aarzalluz  I checked my input GTF  and trimed off undefined strands. However, SQANTI3 failed while using --polyA_peak argument, but normaly ran without this argument .

**Comment by yuchen345** [comment]
@aarzalluz  I checked my input GTF  and trimed off undefined strands. However, SQANTI3 failed while using --polyA_peak argument, but normaly ran without this argument .

**Comment by FJPardoPalacios** [comment]
Hi @yuchen345 ,

Could you check if there is something that it's not a + or - in the strand column of the BED file?
Please, run this command and if anything else different to + or - appears, that's the problem...

```
cut -f6 your_polyA_file.bed | sort -u 
```

If SQ3 used to run without the --polyA_peak option the issue should be only in that file.

Fran

**Comment by yuchen345** [comment]
Thank you very much for your rapid replies!
The output is as follows:
![图片](https://user-images.githubusercontent.com/71202087/217557877-30ed1f0f-efdc-40c1-a025-87ae170aab9d.png)

**Comment by FJPardoPalacios** [comment]
Okey, that's weird because the error directly pointed to that problem but it seems that everything is fine...

Could you attach the complete error file in case there is something else we are missing?
Thanks

Fran

**Comment by aarzalluz** [comment]
> Okey, that's weird because the error directly pointed to that problem but it seems that everything is fine...
> 
> Could you attach the complete error file in case there is something else we are missing? Thanks
> 
> Fran

@yuchen345 In addition, please include your full SQANTI3 command -it helps us understand what the problem may be and should always be included when opening an issue.

**Comment by yuchen345** [comment]
Here is the command using SQANTI3(version 5.1.1):
![图片](https://user-images.githubusercontent.com/71202087/217717978-4901ae7e-308b-4b9a-8b66-9a59c60096ea.png)
and the complete error messages:
![图片](https://user-images.githubusercontent.com/71202087/217718222-2e99dd6e-45e7-40a3-9f70-5674e2f37967.png)
