### ISSUE TITLE
novel transcript/gene

### ISSUE THREAD

**Issue by xiaonalu** [ConesaLab/SQANTI3#182]
Hi, I wanted to ask how sqanti define a new discovery as a novel gene rather a novel transcript? or the novel transcript category only affiliated to known gene, while all the rest considered as novel gene? Thanks

**Comment by aarzalluz** [comment]
Hi @xiaonalu -as you said, any discovery will be considered to be a novel gene, while the novel transcript is a definition that is attached to known genes.
