### ISSUE TITLE
Error generating PDF/HTML report

### ISSUE THREAD

**Issue by riski-ped** [ConesaLab/SQANTI3#183]
Hi,
I got this error message:
`summarise()` has grouped output by 'lenCat'. You can override using the
You can override using the `.groups` argument.
 Error in `[<-.data.frame`(`*tmp*`, which(is.na(x$polyA_motif)), "Coverage_PolyA",: 
   Substitution is for 1 column, but data is for 0 column 
 Call: [<- -> [<-.data.frame
 Execution has stopped 
Traceback (most recent call last):
  File "/rshare1/ZETTAI_path_WA_slash_home_KARA/home/SQANTI3-5.1/sqanti3_qc.py", line 2490, in <module
    main()
  File "/rshare1/ZETTAI_path_WA_slash_home_KARA/home/SQANTI3-5.1/sqanti3_qc.py", line 2473, in main
    run(args)
  File "/rshare1/ZETTAI_path_WA_slash_home_KARA/home/SQANTI3-5.1/sqanti3_qc.py", line 2057, in run
    if subprocess.check_call(cmd, shell=True)! =0:
  File "/home/anaconda3/envs/SQANTI3.env/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/home/anaconda3/envs/SQANTI3.env/bin/Rscript /rshare1/ZETTAI_path_WA_slash_home_KARA /home/SQANTI3-5.1/utilities//report_qc/SQANTI3_report.R /home/SQANTI3-5.1/Output/MOLT3_classification.txt /home/SQANTI3-5.1/Output/MOLT3_ junctions.txt /home/SQANTI3-5.1/Output/MOLT3.params.txt /rshare1/ZETTAI_path_WA_ slash_home_KARA/SQANTI3-5.1/utilities False both' returned non-zero exit status 1.

Is it a problem with polyA motifs?

**Comment by aarzalluz** [comment]
Hi @riski-ped,

When opening a new issue, please try to provide as much information as possible about how you run SQANTI3 (input files, command, species, etc.). The error you posted is really vague, and although it seems related to the QC report, there is no way for us to know what the cause may be. Could you give us more details?

**Comment by riski-ped** [comment]
Thank you for the answer. I just found the answer, it's my mistake in writing the input command. so I will close this issue. thank you.
