### ISSUE TITLE
Obtaining all possibly associated transcripts for ISM transcripts

### ISSUE THREAD

**Issue by hd00ljy** [ConesaLab/SQANTI3#187]
When I examined the SQANTI result, I found that each ISM transcript is associated with only single known transcript.

But I would like to get all the possible known transcripts associated with each ISM transcript.

For example, if all of the junctions of novel transcript A match  those of 3 known transcripts(ENST1,ENST2,ENST3),
that is, novel transcript A is ISM as to ENST1,ENST2 and ENST3, I would like to get all the transcript IDs(ENST1,ENST2,ENST3) for novel transcript A. Not just one of ENST1,ENST2 or ENST3.

Could you suggest a way to do that?

**Comment by lkondratova** [comment]
Use argument  _--isoform_hits_ to record all FSM/ISM reference hits in a separate file '_isoform_hits.txt'

**Comment by aarzalluz** [comment]
> Use argument _--isoform_hits_ to record all FSM/ISM reference hits in a separate file '_isoform_hits.txt'

@lkondratova I'm documenting the new argument in the SQ3 QC wiki page for future user's reference.

**Comment by aarzalluz** [comment]
Hi @hd00ljy, the feature has been incorporated into SQANTI3 v5.1.2. You can download it [here](https://github.com/ConesaLab/SQANTI3/releases/tag/v5.1.2) -feel free to give it a go and let us know if it works!
