### ISSUE TITLE
Hard coded "PB." text in the rescue_by_mapping_rules.R 

### ISSUE THREAD

**Issue by aydemiro** [ConesaLab/SQANTI3#189]
Hi,

I think there is a bug in the rescue script that looks for the text "PB." to remove long read defined transcripts which does not work if the transcripts aren't coming from the Isoseq pipeline. For example, TAMA generated transcripts starting with G for me. I am not sure if this is really affecting the final GTF. I updated the script to look for the reference transcripts to keep instead of looking for LR transcripts to remove since the reference transcripts are available to the script anyway.

Another issue for me was that the helper function find_best_match_id was very slow. The rescue script would run for more than 8h and not finish. I was able to change the script to make it faster as well. I would be happy to provide a PR if needed.

Best,
Ozkan

**Comment by aarzalluz** [comment]
Hi @aydemiro,

Thank you for reporting this -and for making the improvements. Feel free to submit a PR! I'll be happy to test it out and incorporate your changes.

Best,

Ángeles

**Comment by aarzalluz** [comment]
This is just to notify that I just tested your changes to the rescue script (i.e. PR #190) and verified that they do provide a large improvement in speed, with no problems to the resulting output detected on my end -thanks for your contribution. I will implement these improvements to the `rescue_by_mapping_ML.R` shortly.

Best,

Ángeles
