### ISSUE TITLE
'conda env create -f SQANTI3.conda_env.yml' takes a long time

### ISSUE THREAD

**Issue by amdreamer** [ConesaLab/SQANTI3#192]
Hi,

I tried to instal the 5.1.1 version of sqanti3. However, creating the environment takes a long time~ 
Are there other ways to set the environment? 
(I have installed the old version of sqanti3, or can I just install the new version in the old environment?)

**Comment by aarzalluz** [comment]
Hi @amdreamer,

I'm sorry to hear about this -we are aware that SQANTI3 has as lot of dependencies and that the install process can be a little tedious. Some users have created Docker images (see issue #40 and PR #128), if you want to give that a try. 

We have not had a chance to test these yet, but the improvement of installation and dependency management is definitely in our to-do list.

Regarding the version change, you are welcome to try using the new version in the new environment, as there have not been any major dependency changes in the last releases, however, it is always adviseable to create the environment again to get the most updated version of the packages.

Hope that helps! Best,

Ángeles
