### ISSUE TITLE
Classification file showing wrong values for the dist_to_CAGE_peak and withing CAGE peak columns 

### ISSUE THREAD

**Issue by kudasonya** [ConesaLab/SQANTI3#193]
Hello, 

Thank you for the great tool. I have been trying to use SQANTI to filter isoforms by their position in relation to the CAGE peak using the output in columns **dist_to_CAGE_peak** and **within_CAGE_peak**. However, upon manual inspection in IGV I have noticed that for some of the filtered out isoforms that have >500nt and FALSE listed in the classification file, their first exon overlaps CAGE peaks in the human.refTSS_v3.1.hg38.bed file (on the same strand). I am using SQANTI (v5.0), and running it using: 
```
sqanti3_qc.py --cpus 20 --report pdf --force_id_ignore \
--polyA_motif_list $SQANTI3/data/polyA_motifs/mouse_and_human.polyA_motif.txt \
--CAGE_peak $SQANTI3/data/ref_TSS_annotation/human.refTSS_v3.1.hg38.bed \
--sites GTAG,GCAG,ATAC 
```

Could you please help me understand where this issue might arise from?

Kind regards, 

Sofia

**Comment by FJPardoPalacios** [comment]
Hi @kudasonya,

Thanks for using SQANTI3! I need a bit more of information to guess what could be wrong. 
**First:** Is everything filtered out wrong or they are just a some cases?
**Second:** Could you send a screenshot of IGV with an isoform catalogued as within_CAGE_peak=FALSE and dist_to_CAGE_peak > 500bp but overlaps a refTSS peak?
 
Bests,
Fran

**Comment by kudasonya** [comment]
Hello @FJPardoPalacios!

Thanks for a swift response. 
1) For the particular gene I was looking at, it was only some isoforms that were filtered out incorrectly. 
2) Here are the positions of the isoform exon and the CAGE peak. 
```
$ grep hg_123422.1 $SQANTI3/data/ref_TSS_annotation/human.refTSS_v3.1.hg38.bed
```
chr12	2054457	2054468	hg_123422.1	1	+	2054462	2054463	255,255,0
```
$ grep "G2123.64" transcriptome.filtered.expressed_classification.txt | awk '{print $1, $40, $41}'
```
G2123.64 883 FALSE
```
$ grep "G2123.64" transcriptome.filtered.expressed_corrected.gtf
```
chr12	PacBio	transcript	2054451	2692932	.	+	.	transcript_id "G2123.64"; gene_id "ENSG00000151067.23"
chr12	PacBio	exon	2054451	2054535	.	+	.	transcript_id "G2123.64"; gene_id "ENSG00000151067.23";

<img width="952" alt="CAGE_peak_exon" src="https://user-images.githubusercontent.com/97608186/235221830-929ea1ae-ff91-4f7d-9301-9fd753955fba.png">
Hope these details help. 

Best wishes, 
Sofia

**Comment by FJPardoPalacios** [comment]
Okey, I see it. The peak hg_123422.1 is 11bp long and it's located in between these coordinates 2054457-2054468. However, the first exon of G2123.64 starts at 2054451, which is upstream the refTSS peak. By just 6bp, but the TSS it's not within the peak...

**Comment by kudasonya** [comment]
Yes, you are right. I should have checked the positions better. I just saw the 883bp in the dist_to_CAGE_peak column and thought that maybe the TSS was compared to the CAGE peak upstream of it. My current filter is set to `"dist_to_CAGE_peak":[-25,25], `

**Comment by FJPardoPalacios** [comment]
The 883bp distance is because we only take into account peaks upstream the detected TSS, since we assume that degradation ia the cause of the difference between a detected TSS and the orthogonal evidence and it can only work in one direction (i.e. removing basepairs)

Great! Just remember that the `dist_to_CAGE_peak` metric will be measured to the mid-point of the refTSS peak. You can set 2 rules one with the `dist_to_CAGE_peak:[-25,25]` and a different one with the same requisites but changing that one by `within_CAGE_peak:TRUE`. That way you will capture any TSS in that 50bp range to the midpoint of any refTSS peak and TSS that are within a peak (even if the peak is huge).
