### ISSUE TITLE
Error creating pdf report

### ISSUE THREAD

**Issue by netanyak** [ConesaLab/SQANTI3#196]
Hello All,

I have two gtf files of transcripts that I am comparing with each other using SQANTI3 QC v.5.1.1. The script seems to run fine as I get output classifcation.txt and junctions.txt files with the expected number of rows. However, the pdf report is not generated with the below error. It seems to be similar to a previous issue ([#94](https://github.com/ConesaLab/SQANTI3/issues/94)) :

summarize
  
  The following object is masked from ‘package:Biobase’:
  
      combine
  
  The following objects are masked from ‘package:BiocGenerics’:
  
      combine, intersect, setdiff, union
  
  The following object is masked from ‘package:gridExtra’:
  
      combine
  
  The following object is masked from ‘package:reshape’:
  
      rename
  
  The following objects are masked from ‘package:stats’:
  
      filter, lag
  
  The following objects are masked from ‘package:base’:
  
      intersect, setdiff, setequal, union
  
  Warning message:
  package ‘dplyr’ was built under R version 4.2.3 
  Warning message:
  The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
  ℹ Please use the `linewidth` argument instead. 
  Warning message:
  Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
  ℹ Please use `linewidth` instead. 
  `summarise()` has grouped output by 'lenCat'. You can override using the
  `.groups` argument.
  Error in `[.data.frame`(t3.a.SJ, , c(1, 5, 6)) : 
    undefined columns selected
  Calls: rbind ... standardGeneric -> eval -> eval -> eval -> [ -> [.data.frame
  Execution halted
  Traceback (most recent call last):
    File "/apps/sqanti3/5.1.1/SQANTI3/sqanti3_qc.py", line 2490, in <module>
      main()
    File "/apps/sqanti3/5.1.1/SQANTI3/sqanti3_qc.py", line 2473, in main
      run(args)
    File "/apps/sqanti3/5.1.1/SQANTI3/sqanti3_qc.py", line 2057, in run
      if subprocess.check_call(cmd, shell=True)!=0:
    File "/apps/sqanti3/5.1.1/lib/python3.10/subprocess.py", line 369, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '/apps/sqanti3/5.1.1/bin/Rscript /apps/sqanti3/5.1.1/SQANTI3/utilities//report_qc/SQANTI3_report.R /blue/renne/nkeil/for_ritu/sqanti_rev_unind_24h_48h_ONT_02ndk/TRIMD_validated_vs_unind_classification.txt /blue/renne/nkeil/for_ritu/sqanti_rev_unind_24h_48h_ONT_02ndk/TRIMD_validated_vs_unind_junctions.txt /blue/renne/nkeil/for_ritu/sqanti_rev_unind_24h_48h_ONT_02ndk/TRIMD_validated_vs_unind.params.txt /apps/sqanti3/5.1.1/SQANTI3/utilities False pdf' returned non-zero exit status 1.

Any help that you can provide on this issue will be greatly appreciated!

**Comment by almart7** [comment]
Dear @netanyak,
This error message indicates that there might be a column missing in some dataframe. This can happen if you have 0 transcripts of any SQANTI3 category. Could you please send the command you used to discard other possible causes?

**Comment by netanyak** [comment]
Hi,
I had a look at the classification file and it looks like there aren't any transcripts classfied as 'antisense' in the classification file. (This is expected based on some filtering I did of the transcripts before running SQANTI3 QC) 

Here is the command used:
sqanti3_qc.py \
        --skipORF \
        --force_id_ignore \
        --dir ${SQANTI3} \
        --report pdf \
        -o ${COND} \
        ${IND}/${COND}_minimap2_filtered_flipped.gtf \
        ${REFGTF} \
        ${FASTA}

Is there anyway to still get the pdf with the charts in this case?

Thanks!!

**Comment by almart7** [comment]
Hello @netanyak,

You can try to modify and run manually the R script that creates the plots (https://github.com/ConesaLab/SQANTI3/blob/master/utilities/report_qc/SQANTI3_report.R), but there is no other solution at the moment. Sorry for the inconvenience.
