### ISSUE TITLE
SQANTI3 QC fail [Error on last system call, error code 256]

### ISSUE THREAD

**Issue by unique379r** [ConesaLab/SQANTI3#199]
Hi 
I am trying to run the sqanti3_v5.1.1, but somehow its failing. See bellow.

```
python $sqanti3lates/sqanti3_qc.py --CAGE_peak CAGE.bed --polyA_motif_list polyA_motif.txt -o sample -d MMSQANTI3Annotation --cpus 4 --report both -fl m64480e_230124_161455.demux.bc1001--bc1001.collapsed.min_fl_10.filtered.abundance.txt m64480e_230124_161455.demux.bc1001--bc1001.collapsed.min_fl_10.filtered.gff reference.gtf reference.fa

```
**ERROR**

**** Predicting ORF sequences...
error in command line
GeneMarkS: error on last system call, error code 256
Abort program!!!

**LOG**
cat GMST/gms.log

-------------------------------------------------
start time            : Wed Jun 21 14:03:18 2023
working directory     : MMSQANTI3Annotation/GMST
command line          : -faa --strand direct --fnn --output MMSQANTI3Annotation/GMST/GMST_tmp m64480e_230124_161455.demux.bc1001--bc1001_corrected.fasta
output file with predictions : MMSQANTI3Annotation/GMST/GMST_tmp
input sequence        : m64480e_230124_161455.demux.bc1001--bc1001_corrected.fasta
number of bins        : 0
filter                : 1
strand                : direct
markov chain order    : cod = 4, non = 2
genetic code          : 1
search for motif      : 1
motif width           : 12
prestart length       : 6
fixed motif position  : 1
off overlap           : 1
identity threshold    : 0.99
maximum iteration     : 10
gene overlap off      : 1
strand to predict on  : direct
GeneMarkS parameters  : /stornext/snfs4/next-gen/scratch/rupesh/All-Pipelines/pb-apps/SQANTI3-5.1.1/utilities/gmst/par_1.default
initial hmm model     :
output format         : LST
output nucleotides    : 1
output proteins       : 1
gibbs_version         : 3

run starts here:
prepare sequence
/stornext/snfs4/next-gen/scratch/rupesh/All-Pipelines/pb-apps/SQANTI3-5.1.1/utilities/gmst/probuild --par /stornext/snfs4/next-gen/scratch/rupesh/All-Pipelines/pb-apps/SQANTI3-5.1.1/utilities/gmst/par_1.default --clean_join sequence --seq /stornext/snfs5/next-gen/scratch/rupesh/All-Pipelines/testwithfastaOnly/Analysis/MMSQANTI3Annotation/m64480e_230124_161455.demux.bc1001--bc1001_corrected.fasta --log gms.log
Error on last system call, error code 256
Abort program!!!

**Comment by aarzalluz** [comment]
Similarly to what we have answered on all similar issues (e.g. see #104):

SQANTI3 currently runs GeneMark for ORF prediction, a tool that is unfortunately not maintained/updated. Errors related to GMST will therefore not be worked on, however, given the high amount of issues it is generating, we intend to find an alternative way to predict ORFs for future SQ3 releases as soon as we can.

In the meantime, the --skipORF argument can be used to avoid ORF prediction entirely and prevent SQANTI3 from crashing. We apologize for any inconveniences.

**Comment by unique379r** [comment]
Thank you for kind reply, its seem working now with the warnings:
```
WARNING: Skipping ORF prediction because user requested it. All isoforms will be non-coding!
WARNING: All input isoforms were predicted as non-coding
```

if all isoforms marked as non-coding, i think its not correct.

Also, i am wondering, with my old samples it worked without specifying the --skipORF arg, why so?

See my commands which worked perfectly fine and exactly tried with new sample but failed.

```
conda activate SQANTI3v5.env ; export PYTHONPATH="/stornext/snfs5/next-gen/scratch/rupesh/Apps/softwares/SQANTI3-5.0/cDNA_Cupcake/sequence:/stornext/snfs5/next-gen/scratch/rupesh/Apps/softwares/SQANTI3-5.0" ; /stornext/snfs5/next-gen/scratch/rupesh/Apps/envs/SQANTI3v5.env/bin/python /stornext/snfs5/next-gen/scratch/rupesh/Apps/softwares/SQANTI3-5.0/sqanti3_qc.py --CAGE_peak /stornext/snfs5/next-gen/scratch/rupesh/ProjectFritz/database/hg38uLTRA_index/reference.bed 	--polyA_motif_list /stornext/snfs5/next-gen/scratch/rupesh/ProjectFritz/database/hg38uLTRA_index/polyA_motif.txt -o HG002 -d /stornext/snfs5/next-gen/scratch/rupesh/All-Pipelines/pre-pipelineTest/Analysis/MMSQANTI3Annotation --cpus 4 --report both -fl /stornext/snfs5/next-gen/scratch/rupesh/All-Pipelines/pre-pipelineTest/Analysis/MMCupcake/HG002.collapsed.min_fl_10.filtered.abundance.txt /stornext/snfs5/next-gen/scratch/rupesh/All-Pipelines/pre-pipelineTest/Analysis/MMCupcake/HG002.collapsed.min_fl_10.filtered.gff /stornext/snfs5/next-gen/scratch/rupesh/ProjectFritz/database/hg38uLTRA_index/reference.gtf /stornext/snfs5/next-gen/scratch/rupesh/ProjectFritz/database/hg38uLTRA_index/reference.fa; conda deactivate
```

is this any differences with 5v1.1. vs v5 ? i checked its same parameters, let me know if i am missing something here. I tired with v5 but was failed again even i used the same command as above.

**Comment by aarzalluz** [comment]
My colleague @lkondratova pointed out that there was a [similar issue](https://github.com/Magdoll/SQANTI2/issues/26) in the SQANTI2 repo, where GeneMark failed (error code 256) due to long filenames. Perhaps you could give that a go?

Also, just a reminder that using the `--skipORF` flag will of course ignore ORF prediction step and therefore mark all isoforms as non-coding. It might not be correct, but it is the only way to deal with strange GMST issues at the moment. Unfortunately, as I said in my previous reply, since these are problems derived from GMST, we cannot do anything to debug them.

I hope that helps, and I'm sorry we cannot be of further assistance.

Ángeles
