### ISSUE TITLE
aligner if gff input?

### ISSUE THREAD

**Issue by BeatrizdeToledo** [ConesaLab/SQANTI3#2]
Good evening!
First of all, I am really happy that SQANTI3 was finally released! 
I wanted to use the GFF file output generated from cDNA_cupcake, does SQANTI3 accepts this input? If yes, it is written "If you provide the sequences of your transcripts, a mapping step will be performed initially with minimap2." is I use my GFF file, will it still happen an alignment?
Thank you
Beatriz

**Comment by FJPardoPalacios** [comment]
Hi Beatriz,

GFF file generated by cDNA_cupcake is fully compatible with SQANTI3. It is a GFF2 file, which is the same than the GTF format (GFF2=GTF). 

If you use your GFF file with the --gtf option, mapping won't take place. 

Fran

**Comment by BeatrizdeToledo** [comment]
Thank you! That's great
