### ISSUE TITLE
SQANTI3 output missing Intra−Priming Quality Check and Quality Controls

### ISSUE THREAD

**Issue by B10inform** [ConesaLab/SQANTI3#20]
Sqanti2 and SQANTI3 out put are different. "Intra−Priming Quality Check" and "Quality Controls" out put are both missing in SQANTI3.

Absent in the example out "SQANTI3/example/example_out/melanoma_chr13_sqanti_report.pdf" file.

Something is missing in SQANTI3?

**Comment by B10inform** [comment]
Any information about this would be really helpful for SQANTI (SQANTI3) users.

**Comment by Magdoll** [comment]
Hi @B10inform , this is on my backlog of SQANTI3 issues to address. Hope to get to it in 1-2 weeks.

**Comment by B10inform** [comment]
Hi @Magdoll.

Were you able to look into this issue. 
I have one more question. In the sqanti3 output.
     Unique Genes: 9300
     Unique Isoforms: 39457
 Does this mean 48757 total CDS? The output file has .aa and .fasta files (they seem to have same fasta sequence)?
How to separate genes and isoforms sequences?

**Comment by Magdoll** [comment]
Hi @B10inform ,

I just pushed SQANTI3 v1.0 to include the intrapriming figures back. Can you confirm it works now?

Not quite sure what you are asking about genes vs isoforms.  Where did you get the CDS number from?

-Liz

**Comment by B10inform** [comment]
Hi @Magdoll ,

It is same as sqanti3, it does not include the intrapriming figures back. 
On the 2nd page of pdf file, sqanti out put has:
![image](https://user-images.githubusercontent.com/66449329/92528316-6c951f00-f1dd-11ea-915f-021595d406d1.png)

Unique Genes: 9300, Unique Isoforms: 39457
Ho to separate the genes from isoforms?

Thanks

**Comment by Magdoll** [comment]
Hi @B10inform ,

Are you sure you are running SQANTI3 v1.0? Can you send me the classification and junction file so I can generate the SQANTI3 report and make sure it has intrapriming? (if yes, provide email so I can request file upload)

Re: isoforms and genes - you can look at the "associated_gene" and "associated_transcript" column in the classification file, which can be opened with Excel or any spreadsheet software.

-Liz

**Comment by B10inform** [comment]
Hi Liz,

sqanti3_qc.py is giving the intrapriming figure. 

I am getting errors with sqanti3_RulesFilter.py.
 
 sqanti3_RulesFilter.py: line 20: syntax error near unexpected token `('
sqanti3_RulesFilter.py: line 20: `utilitiesPath =  os.path.dirname(os.path.realpath(__file__))+"/utilities/"'

Stay safe, thanks

**Comment by Magdoll** [comment]
@B10inform , how are you running the `sqanti3_RulesFilter.py` script, what is the command you are using?

Can you try the following test

```
$ python ~/GitHub/SQANTI3/sqanti3_RulesFilter.py
R scripting front-end version 3.4.1 (2017-06-30)
usage: sqanti3_RulesFilter.py [-h] [--sam SAM] [--faa FAA] [-a INTRAPRIMING]
                              [-r RUNALENGTH] [-m MAX_DIST_TO_KNOWN_END]
                              [-c MIN_COV] [--filter_mono_exonic] [--skipGTF]
                              [--skipFaFq] [--skipJunction] [-v]
                              sqanti_class isoforms gtf_file
sqanti3_RulesFilter.py: error: the following arguments are required: sqanti_class, isoforms, gtf_file
```

Error looks odd (but looks like the kind that's easy to solve).

**Comment by B10inform** [comment]
It is working. sqanti3_RulesFilter.py *classification.txt *.renamed.fasta *corrected.gtf.

I had to add #!/usr/bin/env python in "sqanti3_RulesFilter.py" to run from my wo directory.

Have a good day.

**Comment by Magdoll** [comment]
Great!
