### ISSUE TITLE
Error Generating R Report when missing SC

### ISSUE THREAD

**Issue by ghost** [ConesaLab/SQANTI3#202]
Hello,

I could use your help troubleshooting this! Thank you so much!

****THE COMMAND I RAN FOR QC:**** 
`sqanti3_qc.py m64345e_220712_195752.gff genes.gtf GCA_000001405.15_GRCh38_no_alt_analysis_set.fna --report skip --force_id_ignore`

**THE ERROR LOG:** (Seems to have run through)
RUN!
/home/unix/thoutam/.conda/envs/SQANTI3.env/bin/python
Rscript (R) version 4.2.3 (2023-03-15)
FASTA index file /stanley/levin_dr/akshaya/projects/MASseq/SQANTI3-5.1.1/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.fai created.
WARNING: ref annotation contains chromosomes not in genome: 17,18,GL000213.1,5,9,KI270728.1,GL000218.1,GL000219.1,22,12,MT,KI270711.1,4,3,8,Y,GL000205.2,KI270734.1,X,KI270713.1,KI270721.1,2,19,11,20,GL000009.2,13,16,KI270726.1,KI270727.1,6,21,GL000194.1,KI270731.1,GL000195.1,10,1,15,14,7

**** Parsing Isoforms....
**** RT-switching computation....
Full-length read abundance files not provided.
Isoforms expression files not provided.
**** Writing output files....
Removing temporary files....
SQANTI3 complete in 1855.0199972419068 sec.
here
out
Write arguments to /stanley/levin_dr/akshaya/projects/MASseq/SQANTI3-5.1.1/m64345e_220712_195752.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /stanley/levin_dr/akshaya/projects/MASseq/SQANTI3-5.1.1/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna....
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
Splice Junction Coverage files not provided.
**** TSS ratio will not be calculated since SR information was not provided
**** Performing Classification of Isoforms....
Number of classified isoforms: 571450
DONE

****THE COMMAND I RAN FOR THE R REPORT:**** 
`Rscript SQANTI3_report.R ../../m64345e_220712_195752_classification.txt ../../m64345e_220712_195752_junctions.txt blank ../ True both`

**THE ERROR LOG:**
Warning message:
Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
i Please use `linewidth` instead. 
`summarise()` has grouped output by 'lenCat'. You can override using the `.groups` argument.
Error in `[<-.data.frame`(`*tmp*`, which(x$diff_to_gene_TSS <= 50), "Annotation",  : 
  replacement has 1 row, data has 0
Calls: [<- -> [<-.data.frame
Execution halted

Thank you so much!

**Comment by aarzalluz** [comment]
Hi @athoutam6,

I see that you used the `--report skip` flag and then you run the `SQANTI3_report.R` script independently -is there a reason for this? Did you try running SQANTI3 QC with `--report pdf`?

Ángeles

**Comment by athoutam6** [comment]
Hi @aarzalluz ,

I apologize if my previous reply was confusing. I was able to run `sqanti3_qc.py` without error. I am running into the issue while running `SQANTI3_report.R` or `sqanti3_qc.py --report pdf`

**Comment by aarzalluz** [comment]
Sorry about that -I thought it was fixed!

The report is very long and errors are prone to happen when the data has unexpected properties -are you missing transcripts in any of your categories?

**Comment by athoutam6** [comment]
@aarzalluz 

Yes, there seem to be quite a few NA values in the columns (ex. Intergenic, novel, etc.).

**Comment by aarzalluz** [comment]
Hi @athoutam6,

I'm certain that we've had this issue reported to us in the past -perhaps @FJPardoPalacios can give you some pointers, since he is used to dealing with this kind of problems?

**Comment by Fabian-RY** [comment]
I recently pushed changes to solve this issue in the report generation. As the original account that posted the error has been deleted and the problem has been addressed, i'm closing this issue.
