### ISSUE TITLE
pigeon report generating missing R scrips.

### ISSUE THREAD

**Issue by unique379r** [ConesaLab/SQANTI3#204]
Hi
I am trying to generate the output from pigeon and then plotting it with the help of your scripts. However, i found there are missing scripts for saturations, can you please updated your github or send these scripts to me. I am comparing the results between your tool and others like pigeon etc.

**Needed Missing scripts (plot.rarefaction.R, LR.rarefaction.R, readData_functions.R):**

```
if (saturation.curves=='True'){
  source(paste(utilities.path, "plot.rarefaction.R", sep = "/"))
  source(paste(utilities.path, "LR.rarefaction.R", sep = "/"))
  source(paste(utilities.path, "readData_functions.R", sep = "/"))
}
```

Thanks

**Comment by aarzalluz** [comment]
Hi @unique379r -I'm not sure I understand what you intend to do, however I can safely say that the saturation scripts are not missing. You can find them [in the utilities folder](https://github.com/ConesaLab/SQANTI3/tree/master/utilities/report_qc/saturation).

Hope that helps,

Ángeles

**Comment by unique379r** [comment]
Thank you Angeles but I was confused as these Rscript names are not the same as you have in the pigeon Rscript. That's why I asked for it. The names are completely different.

`The pigeon plotting script has "plot.rarefaction.R, LR.rarefaction.R, readData_functions.R" whereas has qc plotting script that you redirected has "LR_saturation.R,  plot_saturation.R, data_prep_saturation.R).`
