### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by gengbaobao** [ConesaLab/SQANTI3#210]
Hello,
When I run IsoAnnotLite_SQ3.py, I got the following error:

Traceback (most recent call last):
  File "/home/gbb/tools/SQANTI3-5.1.2/utilities/IsoAnnotLite_SQ3.py", line 3216, in <module>
    main()
  File "/home/gbb/tools/SQANTI3-5.1.2/utilities/IsoAnnotLite_SQ3.py", line 3059, in main
    run(args)
  File "/home/gbb/tools/SQANTI3-5.1.2/utilities/IsoAnnotLite_SQ3.py", line 3113, in run
    dc_GFF3, dc_GFF3exonsTrans, dc_GFF3transExons, dc_GFF3coding, dc_GFF3strand, dc_GFF3geneTrans, dc_GFF3transGene, dc_GFF3geneNameTrans, dc_GFF3_raw_annot, dc_gene_description = readGFF(gff3) #dc_GFF3exons is sorted
  File "/home/gbb/tools/SQANTI3-5.1.2/utilities/IsoAnnotLite_SQ3.py", line 322, in readGFF
    g_name = text[1][5:-1] #delete "NAME=" and final ";" == GENE
IndexError: list index out of range

My commond is:
 python ~/tools/SQANTI3-5.1.2/utilities/IsoAnnotLite_SQ3.py -gff3 /mnt/alamo01/users/gbb/Ref/pacbio/gencode.v44.chr_patch_hapl_scaff.annotation.gff3 -o BM002.isoAnno -stdout . -novel BM002.sqanti_corrected.gtf BM002.sqanti_classification.txt BM002.sqanti_junctions.txt

Anyone could help me?

**Comment by aarzalluz** [comment]
Hi @gengbaobao,

Reading your input command, it looks like you are not providing `-gff3` with the right GFF3 file -did you read through the [documentation](https://github.com/ConesaLab/SQANTI3/wiki/IsoAnnotLite#input-files)? Input GFF3 files are not standard-formatted GFF3 annotations, but tappAS-compatible files that we have pre-computed. 

At the moment, these are only available for human, mouse, Drosophila, Arabidopsis and maize. Follow the link to our wiki above for details.

Best,

Ángeles

**Comment by gengbaobao** [comment]
> Hi @gengbaobao,
> 
> Reading your input command, it looks like you are not providing `-gff3` with the right GFF3 file -did you read through the [documentation](https://github.com/ConesaLab/SQANTI3/wiki/IsoAnnotLite#input-files)? Input GFF3 files are not standard-formatted GFF3 annotations, but tappAS-compatible files that we have pre-computed.
> 
> At the moment, these are only available for human, mouse, Drosophila, Arabidopsis and maize. Follow the link to our wiki above for details.
> 
> Best,
> 
> Ángeles

**Comment by gengbaobao** [comment]
It works! Thanks.
