### ISSUE TITLE
"Transcript_id" and "gene_id" in sqanti_ccorrected.gtf

### ISSUE THREAD

**Issue by gengbaobao** [ConesaLab/SQANTI3#211]
Hello developer,

I follow this pacbio isoseq pipeline step by step (https://github.com/tay45/Iso-Seq_Analysis/blob/main/scripts/isoseq3.py), and then run SQANTI3. The commond is:

1. python ~/tools/SQANTI3-5.1.2/sqanti3_qc.py -t 20 --CAGE_peak hg38.cage_peak_phase1and2combined_coord.bed  \
--polyA_peak atlas.clusters.chr.GRCh38.96.bed  --polyA_motif_list mouse_and_human.polyA_motif.txt  \
-o BM002.sqanti -d BM002/out_sqanti  -fl BM002.collapse.abundance.tsv   \
--gff3 human_tappas_gencode_annotation_file.gff3  \
--coverage intropolis.v1.hg19_with_liftover_to_hg38.tsv.min_count_10.modified  \
--report both --genename --isoAnnotLite\
Pacbio_BM/BM002/BM002.collapse.gtf  gencode.v44.chr_patch_hapl_scaff.annotation.gtf GRCh38.p14.genome.fa

2. python ~/tools/SQANTI3-5.1.2/utilities/IsoAnnotLite_SQ3.py \
-gff3 human_tappas_gencode_annotation_file.gff3 \
-o BM002.isoAnno -stdout . -novel \
BM002.sqanti_corrected.gtf BM002.sqanti_classification.txt BM002.sqanti_junctions.txt

The output GTF file is like this:

chr1    PacBio  transcript      11872   29343   .       -       .       transcript_id "PB.1.1"; gene_id "PB.1"
chr1    PacBio  exon    11872   16765   .       -       .       transcript_id "PB.1.1"; gene_id "PB.1";
chr1    PacBio  exon    16858   17055   .       -       .       transcript_id "PB.1.1"; gene_id "PB.1";
chr1    PacBio  exon    29321   29343   .       -       .       transcript_id "PB.1.1"; gene_id "PB.1";
chr1    PacBio  transcript      14401   29356   .       -       .       transcript_id "PB.1.2"; gene_id "PB.1"
chr1    PacBio  exon    14401   15947   .       -       .       transcript_id "PB.1.2"; gene_id "PB.1";

However, I want to get transcript_id like "ENST XXX" and gene_id like "ENSG XXX", not "PB.X". What should I do?

**Comment by aarzalluz** [comment]
Hi @gengbaobao,

The correspondence between transcript and gene IDs is provided in the [classification file](https://github.com/ConesaLab/SQANTI3/wiki/Understanding-the-output-of-SQANTI3-QC#glossary-of-classification-file-columns-classificationtxt). This information is not included in the SQANTI3 output GTF, however, it is included in the IsoAnnotLite output GFF3, since it is required for tappAS. If you want to edit the GTF file, you will need to create a custom script/find other tools to help you.

Best,

Ángeles

**Comment by gengbaobao** [comment]
Hello Ángeles，

Thanks for your replying!
Is there any correspondence bwtween PacBio ID (PB.X.X) and the genome coordinate? Or just generated randomly.

Best,
Baobao

**Comment by aarzalluz** [comment]
I don't think it is indicative of anything in particular, no -I believe it is just generated randomly.

**Comment by gengbaobao** [comment]
Hello,
How can I calculate the genome coordinate of each isoform (each row) of the sample.sqanti_classification.txt file? Is that could be calculated?
