### ISSUE TITLE
FLAIR vs TAMA collapse for Nanopore long read data

### ISSUE THREAD

**Issue by MartinezRuiz-Carlos** [ConesaLab/SQANTI3#213]
Hi, this should hopefully just be a quick doubt to resolve.
I have a transcriptome from Nanopore cDNA data, which I ran through FLAIR correct/collapse/quantify. Throughout the manual it is clear that SQANTI3 is compatible with FLAIR, but in one of the warnings you specify that data should be run through either TAMA or cDNA_cupcake (which is geared towards PacBio) collapse prior to run with SQANTI3. 
My question is, having a transcriptome from FLAIR can I just run it through SQANTI3 or should I instead be using TAMA outputs?
Many thanks!

**Comment by AnaConesa** [comment]
Hi Carlos,

Running TAMA or cDNA_cupcake is recommended when you have too many redundant transcripts (same junction change but different 3' or 5'ends). You can run FLAIR as it is, without TAMA. In case you find too many redundant transcripts, you may want to consider further collapsing with TAMA.
Hope this helps

**Comment by aarzalluz** [comment]
Hi @MartinezRuiz-Carlos,

If you find it hard to make outputs across the different tools compatible, you might want to check out [flair collapse](https://flair.readthedocs.io/en/latest/modules.html#flair-collapse). I am not entirely familiar with the algorithm, but I believe it achieves the same as TAMACollapse and cDNA_Cupcake, which is, to merge very similar transcript models to reduce the number of redundant isoforms in the transcriptome.

Hope that helps!

Ángeles

**Comment by MartinezRuiz-Carlos** [comment]
Right yes, that was where my doubt was coming from. My understanding was that FLAIR collapse and TAMA collapse were trying to do the same thing. So in essence, if I have already run FLAIR collapse there should be no need to run TAMA collapse before getting into SQANTI3, right?

Thanks again!

**Comment by aarzalluz** [comment]
That's right -maybe play around with the flair collapse parameters, I don't know how much flexibility it allows, but I like to try out a few different configurations and run them through the QC module, just to be certain that I'm getting a good balance between redundancy and novelty, particularly for 5'ends. Other than that, I think it should be fine!

**Comment by MartinezRuiz-Carlos** [comment]
Excellent, muchas gracias!
