### ISSUE TITLE
OSError: [Errno 8] Exec format error: '/Users/sonyx/SQANTI3-5.1.2/utilities/gtfToGenePred'

### ISSUE THREAD

**Issue by sonyuna90** [ConesaLab/SQANTI3#214]
Hi, I am trying to run SQANTI3 with chained multi-sample counts for generating isoAnnotLite gff3 file. I am wondering if you can guide me what is wrong with my process. Thanks. 

python /Users/sonyx/SQANTI3-5.1.2/sqanti3_qc.py ./genes_cannonical_chr.gtf gencode.v38.chr_patch_hapl_scaff.annotation.gtf /Users/sonyx/SQANTI3-5.1.2/GRCh38.primary_assembly.genome.fa -o sqanti_out --dir SQANTI3_out/ --fl_count /Users/sonyx/Downloads/sq_test/merged_counts_total.tsv --isoAnnotLite --skipORF
Rscript (R) version 4.3.1 (2023-06-16)
Write arguments to /Users/sonyx/Downloads/SQANTI3_out/sqanti_out.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /Users/sonyx/SQANTI3-5.1.2/GRCh38.primary_assembly.genome.fa....
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
WARNING: Skipping ORF prediction because user requested it. All isoforms will be non-coding!
WARNING: All input isoforms were predicted as non-coding
**** Parsing Reference Transcriptome....
Traceback (most recent call last):
  File "/Users/sonyx/SQANTI3-5.1.2/sqanti3_qc.py", line 2537, in <module>
    main()
  File "/Users/sonyx/SQANTI3-5.1.2/sqanti3_qc.py", line 2520, in main
    run(args)
  File "/Users/sonyx/SQANTI3-5.1.2/sqanti3_qc.py", line 1873, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene = reference_parser(args, list(genome_dict.keys()))
  File "/Users/sonyx/SQANTI3-5.1.2/sqanti3_qc.py", line 659, in reference_parser
    subprocess.call([GTF2GENEPRED_PROG, args.annotation, referenceFiles, '-genePredExt', '-allErrors', '-ignoreGroupsWithoutExons', '-geneNameAsName2'])
  File "/Users/sonyx/opt/anaconda3/envs/SQANTI3.env/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Users/sonyx/opt/anaconda3/envs/SQANTI3.env/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/sonyx/opt/anaconda3/envs/SQANTI3.env/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/sonyx/SQANTI3-5.1.2/utilities/gtfToGenePred'

**Comment by aarzalluz** [comment]
Hi @sonyuna90,

You may not have downloaded the correct version of gtfToGenePred for your OS -please see the relevant section of the [installation instructions](https://github.com/ConesaLab/SQANTI3/wiki/Dependencies-and-installation#install3):

> For Linux users, the right version of gtfToGenePred is already in the utilities folder. However, if you are running SQANTI3 on MacOS, you must remove the utilities/gtfToGenePred file and download the Mac version [here](https://hgdownload.soe.ucsc.edu/admin/exe/macOSX.x86_64/).

Let us know if the error persists. Best, 

Ángeles

**Comment by sonyuna90** [comment]
Hi Sqanti3 team, 

I found that this was related to my MacOS issue. As Angeles suggested, I did install a different version of gtfToGenePred and give permission to the gtfToGenePred. It works now. Thank you for the help!

**Comment by aarzalluz** [comment]
Glad to hear it!
