### ISSUE TITLE
Any specific requirements for genome annotation

### ISSUE THREAD

**Issue by veravelasco** [ConesaLab/SQANTI3#22]
Hi,
I have installed SQANTI3 and successfully ran the example set. Thus, I have a working installation of SQANTI3.  However,  when I tried my own dataset, it gives me all kinds of error and an empty classification and junction outputs.  I am working on a non-model species with less than perfect genome assembly and annotation.  Does SQANTI3 have specific/minimum requirements for a genome annotation/assembly?  
Thanks.
Vera

**Comment by Magdoll** [comment]
Hi @veravelasco ,
Can you confirm that the reference genome and annotation are using the same chormosome naming? The same coordinate system?

Are you supplying an input fasta or input GTF? What is the full command used?

Can you print out the errors here?

**Comment by veravelasco** [comment]
Hi Elizabeth,

Yes. The reference genome and annotation are using the same chromosome and coordinate system.
My input is fasta.  Here is the command

Script:

mv all.fake_genome.fa all.fake_genome.fasta
python $SQANTI/sqanti3_qc.py all.fake_genome.fasta \
       Psme.1_0.gtf.gz \
       Psme_v1.0.5000.genome.masked.fa

Error:
Traceback (most recent call last):
  File "/home/CAM/vvelasco/Applications/SQANTI3/sqanti3_qc.py", line 2289, in <module>
    main()
  File "/home/CAM/vvelasco/Applications/SQANTI3/sqanti3_qc.py", line 2273, in main
    run(args)
  File "/home/CAM/vvelasco/Applications/SQANTI3/sqanti3_qc.py", line 1705, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene = reference_parser(args, list(genome_dict.keys()))
  File "/home/CAM/vvelasco/Applications/SQANTI3/sqanti3_qc.py", line 664, in reference_parser
    for r in genePredReader(referenceFiles):
  File "/home/CAM/vvelasco/Applications/SQANTI3/sqanti3_qc.py", line 132, in __init__
    self.f = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/labs/Wegrzyn/CoAdapTree_Douglasfir/Assembly_comparison/04_Sqanti/refAnnotation_all.fake_genome.genePred'


I also tried the collapsed.rep.fa output from cogent and did not succeed with similar errors.

Thank you for your help.

Cheers,

Vera

**Comment by Magdoll** [comment]
Close unless OP reopens.
