### ISSUE TITLE
version returned incorrect

### ISSUE THREAD

**Issue by mkostich** [ConesaLab/SQANTI3#220]
Hi all,

bug report:

Using sqanti3 v5.1.2
calling `sqanti3_qc.py --version`  
yields `SQANTI3 5.0`. 

Is there another way to report version automatically? 

Thanks for your help!

Mitch

**Comment by almart7** [comment]
Dear @mkostich thank you for letting us know! We will address this issue as soon as possible.

**Comment by aarzalluz** [comment]
Closing issue as it will be fixed in the upcoming release (SQANTI3 v.5.1.3).
