### ISSUE TITLE
Errors in generating Sqanti_report.R?

### ISSUE THREAD

**Issue by syjho1** [ConesaLab/SQANTI3#23]
Hi, 

Thanks for setting up sqanti3! 

I've been running sqanti3_qc.py on my samples. while I am able to reach the step *Writing output files*, 
I have been having 2 spots in my run that consistently fails: 

#1:  there seems to be an extra "/" added to the path when the SQANTI_report.R is called
the error generated is below:

**** Writing output files....
**** Generating SQANTI3 report....
Traceback (most recent call last):
  File "<path>/conda/SQANTI3/sqanti3_qc.py", line 2289, in <module>
    main()
  File "<path>/conda/SQANTI3/sqanti3_qc.py", line 2273, in main
    run(args)
  File "<path>/conda/SQANTI3/sqanti3_qc.py", line 1892, in run
    if subprocess.check_call(cmd, shell=True)!=0:
  File "<path>/.conda/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '<path>/.conda/envs/SQANTI3.env/bin/Rscript <path>/conda/SQANTI3/utilities//SQANTI3_report.R <path>/test_sqanti3/output/all_samples.chained.rep_classification.txt <path>/test_sqanti3/output/all_samples.chained.rep_junctions.txt <path>/test_sqanti3/output/all_samples.chained.rep.params.txt <path>/conda/SQANTI3/utilities/' returned non-zero exit status 1.

#2: SQANTI_report.R keeps terminating at the LR.rarefaction.R
If I take the output files and run it separately using SQANTI3_report.R, then I encounter another problem with the script where it stops at the LR.rarefaction.R.  There doesn't seem to be any problems plotting the other plots (p1, p2 etc.. ) 

my output --> 
`summarise()` regrouping output by 'lenCat' (override with `.groups` argument)
`summarise()` regrouping output by 'structural_category' (override with `.groups` argument)
`summarise()` ungrouping output (override with `.groups` argument)
`summarise()` regrouping output by 'structural_category' (override with `.groups` argument)
`summarise()` regrouping output by 'structural_category' (override with `.groups` argument)
`summarise()` regrouping output by 'structural_category' (override with `.groups` argument)
`summarise()` regrouping output by 'associated_transcript' (override with `.groups` argument)
`summarise()` regrouping output by 'associated_transcript' (override with `.groups` argument)
Error in base::rep(genes, data[, samples[s]]) : invalid 'times' argument
Calls: LR.rarefaction
Execution halted

I'm new at Isoseq analysis.. so I'm not sure if this is something on my side, or if there is a quick fix I can apply here.
Thank you!

Cheers,
sook

**Comment by syjho1** [comment]
Thank you Elizabeth!
Let me talk to my PI about the files (Sorry! I hope you understand...)
If it helps: I was running my scripts on the cluster, using bsub. Since my installed sqanti3 environment was in my own folder, I provided the full path when running the program (see attached script [bsub_Sqanti3_qc.txt](https://github.com/ConesaLab/SQANTI3/files/5125644/bsub_Sqanti3_qc.txt)). 
Do you think this may have affected the way the path was called?

I sort of overcame the first error I got by changing line 1891 in sqanti3_qc.py:

 if not args.skip_report:        
      print("**** Generating SQANTI3 report....", file=sys.stderr)       
      **utilitiesPath1 =  os.path.dirname(os.path.realpath(__file__))+"/utilities"**         
      cmd = RSCRIPTPATH + " {d}/{f} {c} {j} {p} {d}".format(d=**utilitiesPath1**, f=RSCRIPT_REPORT, c=outputClassPath, j=outputJuncPath, p=args.doc)       
      # cmd = RSCRIPTPATH + " {d}/{f} {c} {j} {p} {d}".format(d=utilitiesPath, f=RSCRIPT_REPORT, c=outputClassPath, j=outputJuncPath, p=args.doc)        

      if subprocess.check_call(cmd, shell=True)!=0:            
           print("ERROR running command: {0}".format(cmd), file=sys.stderr)            
           sys.exit(-1)

For the second error, I ended up commenting out the calls to LR.rarefaction in SQANTI3_report.R (lines 1802 to 1806). After that, everything went through smoothly, and I was still able to generate the report and output files for downstream analyses.

**Comment by Magdoll** [comment]
Hi @syjho1 ,
Yes it looks like this had something to do with the paths. Right now you need to call sqanti_qc3.py with `python <path_to>/sqanti_qc3.py` or there will be issues finding the `utilities` subdirectory.

Well...the rarefaction curve script is supposed to work and not just be skipped. Do you want me to still take a look at it?
-Liz

**Comment by Magdoll** [comment]
Rarefaction curve is currently disabled. Closing this issue unless OP reopens.
