### ISSUE TITLE
r-rcolorconesa not found during v5.2 yml environment installation

### ISSUE THREAD

**Issue by stambolliualen** [ConesaLab/SQANTI3#234]
Hi,

Thank you for SQUANTI3, it's super userful for my project.

I just wanted to inform about a little problem that I had during conda environment creation from yml file. It raises a problem related to r-rcolorconesa tool not found.

I've noticed that it's something that was changed in the last release (v5.2), so I've solved it by creating the environment from the yml in the previous release (v5.1.2) and then run the new version executable files. 

Best,
Alen

**Comment by aarzalluz** [comment]
Hi @stambolliualen -you're right, the R package RColorConesa is not yet available to be installed via conda. Sorry we missed that. I will fix right away.

Ángeles

**Comment by aarzalluz** [comment]
SQANTI3 v5.2 is now fixed -apologies for any inconveniences caused.

**Comment by stambolliualen** [comment]
No worries, I just wanted to let you know to avoid other users struggles during this transition version period.

Alen
