### ISSUE TITLE
Error in Pigeon Report Rscript.

### ISSUE THREAD

**Issue by unique379r** [ConesaLab/SQANTI3#236]
Hi
I am trying to make the report out of report Rscript but this gives me the error and the program crashed,  any idea ? However,  I used "--cage-peak" in pigeon classify. 

command:
```
Rscript $report_pigeon/pigeon_report.R $filt_class $junc_filt $report_pigeon False both
```

**Error:**
```
Error in FUN(X[[i]], ...) : object 'within_cage_peak' not found
Calls: generatePDFreport ... <Anonymous> -> f -> scales_add_defaults -> lapply -> FUN
In addition: Warning messages:
1: Using alpha for a discrete variable is not advised.
2: Using alpha for a discrete variable is not advised.
3: Using alpha for a discrete variable is not advised.
4: Using alpha for a discrete variable is not advised.
Execution halted

```

**Comment by almart7** [comment]
Dear @unique379r please contact @Magdoll for Pigeon related issues. Kind regards!

**Comment by unique379r** [comment]
Never mind, I found the bug, it pigeon new release > 1.0.0 has changed the name "cage" to "CAGE", which causes the issue to the script.
