### ISSUE TITLE
sqanti QC transcript_models_corrected.gtf

### ISSUE THREAD

**Issue by dawangran** [ConesaLab/SQANTI3#237]
hi～
I found that the generated gtf would be missing one line of gene information, only the transcript information. How can this be corrected?

input:
<img width="920" alt="image" src="https://github.com/ConesaLab/SQANTI3/assets/94769806/123c2087-2582-492d-8cb5-68c80cc76354">
output:
<img width="903" alt="image" src="https://github.com/ConesaLab/SQANTI3/assets/94769806/3a6dec2a-2752-4f21-8b46-6b1d2118f2d7">

Thanks~

**Comment by almart7** [comment]
Dear @dawangran, by definition, the corrected GTF contains the annotation for all transcripts supplied to SQANTI3, gene coordinates are not included in the output.
