### ISSUE TITLE
_classification_TPM.txt is unreadable by R

### ISSUE THREAD

**Issue by jackhump** [ConesaLab/SQANTI3#24]
Dear SQANTI3 authors,

Thanks for all your hard work in maintaining such a useful tool! I'm trying to using the TPM table for downstream analysis and I'm having a hard time reading in the _classification_TPM.txt 

There seem to be 2 issues:

1) the isoform name occurs twice but only has one column name, so I assume it was being used as a rowname before. This prevents it from being read by readr, and data.table complains about it.

2) I have a transcript classified as "Genic Genomic" but the space between "Genic" and "Genomic" is being interpreted as a newline character by less , read.table, readr and data.table.

For reference, I used the latest version of SQANTI3 as of 2 days ago to run the analysis.

**Comment by Magdoll** [comment]
@jackhump , can you read the .classification.txt file? (which is made *before* the TPM file)
If yes - then probably I did something wrong with the conversion to TPM.txt. Can try to fix.

**Comment by jackhump** [comment]
Hi Liz,

yes I should've clarified, the classification file reads in fine.

**Comment by Magdoll** [comment]
Fixed in SQANTI3 v1.1
