### ISSUE TITLE
v5.2 reports version as 5.1.2

### ISSUE THREAD

**Issue by mkostich** [ConesaLab/SQANTI3#240]
Hi all,

I'm running https://github.com/ConesaLab/SQANTI3/releases/download/v5.2/SQANTI3-5.2.tar.gz

version returned by:
sqanti3_qc.py --version

is:
SQANTI3 5.1.2

(should be 5.2.something)

Thanks for fixing previously reported issues!

Mitch

**Comment by almart7** [comment]
Hello @mkostich, thank you for leting us know! Kind regards.
