### ISSUE TITLE
Corrected gtf and fasta file not created

### ISSUE THREAD

**Issue by jchariker** [ConesaLab/SQANTI3#241]
Hi,
I'm running sqanti3_qc.py (v4.0) on a gtf file created in Expresso using the following command.

`sqanti3_qc.py --skipORF -o SQANTI3 -d SQANTI3_output --report both espresso.gtf Homo_sapiens.GRCh38.107.gtf hg38.p13.fa`

The output folder is created along with the genePred file for the reference annotation. However, the files for the corrected gtf and fasta are empty, and SQANTI3 stops with the following error. 

**** Parsing Isoforms....
/bio/home/julia/m6A/ESPRESSO/SQANTI3_output/SQANTI3_corrected.gtf doesn't appear to be a GTF file (GFF not supported by this program)
Traceback (most recent call last):
  File "/bio/bin/SQANTI3-4.0/sqanti3_qc.py", line 2486, in <module>
    main()
  File "/bio/bin/SQANTI3-4.0/sqanti3_qc.py", line 2470, in main
    run(args)
  File "/bio/bin/SQANTI3-4.0/sqanti3_qc.py", line 1869, in run
    isoforms_by_chr = isoforms_parser(args)
  File "/bio/bin/SQANTI3-4.0/sqanti3_qc.py", line 700, in isoforms_parser
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/usr/local/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/bio/bin/SQANTI3-4.0/utilities/gtfToGenePred /bio/home/julia/m6A/ESPRESSO/SQANTI3_output/SQANTI3_corrected.gtf /bio/home/julia/m6A/ESPRESSO/SQANTI3_output/SQANTI3_corrected.genePred -genePredExt -allErrors -ignoreGroupsWithoutExons' returned non-zero exit status 255.

I've compared the Espresso gtf with the reference annotation and they appear to be aligned with each other in terms of transcript start stop sites and names in column 9. The espresso gtf appears to have the correct format below. 

`1	annotated_isoform	transcript	30267	31109	.	+	.	gene_id "ENSG00000243485"; transcript_id "ENST00000469289";
1	annotated_isoform	exon	30267	30667	.	+	.	gene_id "ENSG00000243485"; transcript_id "ENST00000469289"; exon_number "1";
1	annotated_isoform	exon	30976	31109	.	+	.	gene_id "ENSG00000243485"; transcript_id "ENST00000469289"; exon_number "2";`

Can you provide any clue as to what might be the problem?
Thanks for your help!

**Comment by almart7** [comment]
Dear @jchariker, some problems have been reported due to the presence of white spaces in GTF files. Have you tried to run gtfToGenePred with this data subset on one hand and with some other lines that does execute successfully?

**Comment by jchariker** [comment]
Hi Alessandra,
I do not find any extra white spaces in the gtf, and gtfToGenePred runs successfully on the file outside of SQANTI3.  I don't think the problem is related to gtfToGenePred. The problem is that the corrected.gtf required as input to gtfToGenePred is not getting filled. Neither is the corrected.fasta I'm not getting any errors about it, but the files are empty, so gtfToGenePred gives the error.

I can successfully run SQANTI3 with the gff files produced as output from PacBio/cDNA Cupcake. However the problem occurs with the gtf produced by Minion/Espresso. Could it be that SQANTI3 expects the gene/transcript Ids to be formatted similarly to PacBio? 

Julia

**PacBio/cDNA Cupcake gff runs successfully**
1	PacBio	transcript	11749	16372	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
1	PacBio	exon	11749	11794	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
1	PacBio	exon	11919	12034	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
1	PacBio	exon	12373	12521	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
1	PacBio	exon	12795	12953	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";
1	PacBio	exon	13034	13135	.	+	.	gene_id "PB.1"; transcript_id "PB.1.1";

**Minion/Espresso gtf produces the error**
1	annotated_isoform	transcript	30267	31109	.	+	.	gene_id "ENSG00000243485"; transcript_id "ENST00000469289";
1	annotated_isoform	exon	30267	30667	.	+	.	gene_id "ENSG00000243485"; transcript_id "ENST00000469289"; exon_number "1";
1	annotated_isoform	exon	30976	31109	.	+	.	gene_id "ENSG00000243485"; transcript_id "ENST00000469289"; exon_number "2";
1	annotated_isoform	transcript	185217	195411	.	-	.	gene_id "ENSG00000279457"; transcript_id "ENST00000623083";
1	annotated_isoform	exon	185217	185350	.	-	.	gene_id "ENSG00000279457"; transcript_id "ENST00000623083"; exon_number "1";
1	annotated_isoform	exon	185491	185559	.	-	.	gene_id "ENSG00000279457"; transcript_id "ENST00000623083"; exon_number "2";
1	annotated_isoform	exon	186317	186469	.	-	.	gene_id "ENSG00000279457"; transcript_id "ENST00000623083"; exon_number "3";

**Comment by almart7** [comment]
I see. I have been able to run SQANTI for data with ENSG/ENST identifyers but without the exon_number information. Maybe you can delete that last field from the attributes and try again.

**Comment by jchariker** [comment]
Hi Alessandra,
I removed exon_number, but the problem still exists. Espresso can provide some minimal transcript classification, so I may have to rely on that. Just want you to know I really appreciate your help!
