### ISSUE TITLE
SQANTI3 QC fails when using sorted BAMs to calculate ratio TSS with splits enabled

### ISSUE THREAD

**Issue by ryanpe13002** [ConesaLab/SQANTI3#242]
To whom it may concern,

I have had an issue running SQANTI3 QC when trying to use sorted BAM files to calculate the ratio TSS. Error file is here:
[SQANTI3_QC.err.txt](https://github.com/ConesaLab/SQANTI3/files/13546709/SQANTI3_QC.err.txt)

For context, the way I structure these runs is to run STAR manually on my input FASTA files, and place all the *.SJ.out.tab files in one directory, and all the sorted BAM files in another directory. When I run SQANTI3 QC for the first time, it looks like what is happening is the program recognizes there is no "chr_order.txt" file in the sorted BAM directory, and so it tries to create one. When running the program with splits, it seems like the different threads are overwriting "chr_order.txt" while other threads are trying to access it, creating the error seen in lines 349-373 in the attached error file.

Could someone take a look at this and see if the order of commands can be altered such that the program determines if the "chr_order.txt" file exists right before using it, that might alleviate this problem. Alternatively, shifting the creation of that file to before threading is initiated might solve the problem too. Thanks so much, really appreciate you all and your wonderful work!!!

Kindest regards,
Ryan Englander

**Comment by almart7** [comment]
Hello @ryanpe13002 thanks for using SQANTI3. We will have a look at your problem as soon as possible!

**Comment by carolinamonzo** [comment]
Hi @ryanpe13002, this problem has just been fixed with the commit made by @lkondratova (beaf955), you will have to install the development version hosted on github to use it ;)
