### ISSUE TITLE
Parallelization Error

### ISSUE THREAD

**Issue by eprdz** [ConesaLab/SQANTI3#243]
Hi,
I tried to run SQANTI QC with a GTF file from IsoQuant as transcriptome input and the following error appeared when I tried to set `-n` option (number of parallel chunks) higher than 1:

```
WARNING: output directory /tmp already exists. Overwriting!
Traceback (most recent call last):
  File "/apps/SQANTI3-5.2/sqanti3_qc.py", line 2545, in <module>
    main()
  File "/apps/SQANTI3-5.2/sqanti3_qc.py", line 2534, in main
    split_dirs = split_input_run(args)
  File "/apps/SQANTI3-5.2/sqanti3_qc.py", line 2266, in split_input_run
    recs = [r for r in collapseGFFReader(args.isoforms)]
  File "/apps/SQANTI3-5.2/sqanti3_qc.py", line 2266, in <listcomp>
    recs = [r for r in collapseGFFReader(args.isoforms)]
  File "/env/SQANTI3-5.2/lib/python3.10/site-packages/cupcake-29.0.0-py3.10-linux-x86_64.egg/cupcake/io/GFF.py", line 419, in __next__
    return self.read()
  File "/env/SQANTI3-5.2/lib/python3.10/site-packages/cupcake-29.0.0-py3.10-linux-x86_64.egg/cupcake/io/GFF.py", line 590, in read
    assert raw[2] == 'transcript'
AssertionError

```
When I run it with `-n = 1`, everything works well.

I read [a similar issue](https://github.com/ConesaLab/SQANTI3/issues/188) but I am not running SQANTI3 in a high performance computing cluster. Can you give me any advice?

Thanks in advance.

**Comment by TianYuan-Liu** [comment]
Hi, It seems the issue arises when trying to run SQANTI QC in parallel mode with -n set to more than 1, and the error indicates a problem during the parsing of the GTF file by cupcake library. Specifically, the assertion error suggests that an expected 'transcript' entry in the GTF file does not match the actual entry read by the parser. This issue might not be directly related to running on a high-performance computing cluster but rather with how the GTF file is being parsed in parallel processing.
To better understand and diagnose the problem, it would be helpful if you could share the GTF file and other files you're using as input. This will allow me to reproduce the issue on my end and potentially identify a solution more effectively.
Please ensure that any sensitive or proprietary information is removed or anonymized before sharing the file. 
Looking forward to your response, and I'm here to help in any way I can.

**Comment by TianYuan-Liu** [comment]
Hi Enrique, after several productive discussions with Alejandro @alexpan00, we've successfully resolved the issue. You should now be able to run the process in parallel without any problems. Thanks for your patience!

**Comment by eprdz** [comment]
Thanks!

**Comment by Tang-pro** [comment]
Hi, @TianYuan-Liu @eprdz 

I am experiencing a similar problem. 
May I ask how it was resolved?

**Comment by pabloati** [comment]
Hi Tang,

Could you paste your error log and the version of SQANTI3 that you are using? Also, if you could, it would be great to have a sample of your input data to reproduce the error.

Best,
Pablo

**Comment by Tang-pro** [comment]
@pabloati 

the error is here [https://github.com/ConesaLab/SQANTI3/issues/409](https://github.com/ConesaLab/SQANTI3/issues/409) 
I think use the version of SQANTI3 is 5.3.5, I've installed 5.3.6, where there are indeed some software versions that are different, and I've been re-running the code. I'll keep you posted if there are still errors
Thanks!
