### ISSUE TITLE
The sign of diff_to_TSS and diff_to_TTS seem to be flipped

### ISSUE THREAD

**Issue by ryanpe13002** [ConesaLab/SQANTI3#244]
The description for these variables on [https://github.com/ConesaLab/SQANTI3/wiki/Understanding-the-output-of-SQANTI3-QC](https://github.com/ConesaLab/SQANTI3/wiki/Understanding-the-output-of-SQANTI3-QC) reads as follows:

diff_to_TSS: distance of query isoform 5' start to reference transcript start end. Negative value means query starts downstream of reference.
diff_to_TTS: distance of query isoform 3' end to reference annotated end site. Negative value means query ends upstream of reference.

However, when I manually compare FSM isoforms on the UCSC genome browser, every example I can find shows the opposite. It seems like the signs have been flipped, for both diff_to_TSS and diff_to_TTS. This is fine, but if it's correct, perhaps the descriptions might be updated on the website!

Thanks a bunch, and sorry for the pedantry - just caused me some confusion!

**Comment by TianYuan-Liu** [comment]
Hi,
 thank you for bringing this to our attention and for the detailed observation regarding the **diff_to_TSS** and **diff_to_TTS** variables as described on the [SQANTI3 QC output documentation page](https://github.com/ConesaLab/SQANTI3/wiki/Understanding-the-output-of-SQANTI3-QC). Your meticulous comparison using the UCSC genome browser is invaluable.
Before we proceed with updating the documentation, I'd like to understand if this observation is specific to FSM isoforms or if it extends to other isoform categories as well, such as ISM. Could you possibly provide an example where an FSM and ISM isoforms display the pattern regarding the **diff_to_TSS** and **diff_to_TTS** descriptions? This will help us ensure that the documentation accurately reflects all scenarios and assists users in interpreting the output correctly.
Thanks again for your contribution to improving SQANTI3's documentation. Looking forward to your response!
