### ISSUE TITLE
Isoforms originating from exon and intron regions are annotated as intergenic

### ISSUE THREAD

**Issue by ZhangHaibo-777** [ConesaLab/SQANTI3#245]
Hello, 
I used SQANTI3 to annotate isoforms on the provided gtf files, but I found that some isoforms derived from the exon and intron regions of the genome will be annotated as intergenic, may I ask why such a result occurs?

Best wishes.

# Input gtf
chr17   FLAIR   transcript      43296032        43296615        .       -       .       gene_id "chr17:43296000"; transcript_id "TB10000B47-202312082242101_20231209082352_00269_028600928-0";
chr17   FLAIR   exon    43296032        43296615        .       -       .       gene_id "chr17:43296000"; transcript_id "TB10000B47-202312082242101_20231209082352_00269_028600928-0"; exon_number "0";

# _classification.txt
TB10000B47-202312082242101_20231209082352_00269_028600928-0     chr17   -       584     1       intergenic      novelGene_8_74  novel   NA      NA      NA      NA      NA      NA      mono-exon       FALSE   NA      NA      NA      NA      NA      NA    NA       NA      NA      NA      NA      NA      A       non_coding      NA      NA      NA      NA      NA      NA      NA      0.0     CTCTCTCTGTCTCTCTCTCT    NA      FALSE   NA      NA      NA      NA      FALSE   NA      NA

# _corrected.gtf
chr17   PacBio  transcript      43296032        43296615        .       -       .       transcript_id "TB10000B47-202312082242101_20231209082352_00269_028600928-0"; gene_id "chr17:43296000"
chr17   PacBio  exon    43296032        43296615        .       -       .       transcript_id "TB10000B47-202312082242101_20231209082352_00269_028600928-0"; gene_id "chr17:43296000";

# IGV
<img width="1492" alt="image" src="https://github.com/ConesaLab/SQANTI3/assets/97860252/c1b63f72-dd59-44f9-9486-b798bf70b3f8">

**Comment by carolinamonzo** [comment]
Hi @ZhangHaibo-777, I'm intrigued about this. Is it happening only on short mono-exonic transcripts?

**Comment by ZhangHaibo-777** [comment]
Thank you for your replay @carolinamonzo, this doesn't just happen with short mono-exon isoforms, the two examples I show below can prove this point.

** Input gtf**
chr16   FLAIR   transcript      56643705        56644786        .       +       .       gene_id "ENSG00000205361.8"; transcript_id "ENST00000463480.6";
chr16   FLAIR   exon    56643705        56643752        .       +       .       gene_id "ENSG00000205361.8"; transcript_id "ENST00000463480.6"; exon_number "0";
chr16   FLAIR   exon    56644111        56644176        .       +       .       gene_id "ENSG00000205361.8"; transcript_id "ENST00000463480.6"; exon_number "1";
chr16   FLAIR   exon    56644710        56644786        .       +       .       gene_id "ENSG00000205361.8"; transcript_id "ENST00000463480.6"; exon_number "2";
chr1    FLAIR   transcript      235957879       235971825       .       -       .       gene_id "ENSG00000229291.1"; transcript_id "ENST00000443207.1";
chr1    FLAIR   exon    235957879       235958003       .       -       .       gene_id "ENSG00000229291.1"; transcript_id "ENST00000443207.1"; exon_number "0";
chr1    FLAIR   exon    235971761       235971825       .       -       .       gene_id "ENSG00000229291.1"; transcript_id "ENST00000443207.1"; exon_number "1";

**_classification.txt**
ENST00000443207.1       chr1    -       190     2       intergenic      novelGene_0_12  novel
ENST00000463480.6       chr16   +       191     3       intergenic      novelGene_2_5   novel

Best wishes.

**Comment by carolinamonzo** [comment]
Hi @ZhangHaibo-777,

By default, SQANTI3 has a minimum length of transcripts of 200nt. Any reads below that threshold are classified as intergenic. You can set a --min_ref_len 0, so it classifies short reads as well into their corresponding structural categories.

Best wishes,
Carolina.
