### ISSUE TITLE
ployA tail

### ISSUE THREAD

**Issue by dawangran** [ConesaLab/SQANTI3#246]
Hello,
 I want to calculate ployA tail, transcript_models_classification. There is ployA_dist in this file. Is this the distance from the end of 3 '? Or is there any way you can calculate the ployA tail? Thank you very much！

**Comment by aarzalluz** [comment]
Hi @dawangran,

You may want to check the [SQANTI3 wiki](https://github.com/ConesaLab/SQANTI3/wiki/Understanding-the-output-of-SQANTI3-QC#classifcols) for details regarding the interpretation of the quality attributes in the classification file. 

Specifically, these are the attributes related to the TTS (3' end) and the polyA site:

> polyA_dist: if --polyA_motif_list is given, shows the location of the last base of the hexamer. Position 0 is the putative poly(A) site. This distance is hence always negative because it is upstream.
> dist_to_polyA_site: distance to the closest polyA site, based on polyA site data (e.g. Quant-seq).
> diff_to_TTS: distance of query isoform 3' end to reference annotated end site. Negative value means query ends upstream of reference.
> diff_to_gene_TTS: distance of query isoform 3' end to the closest end of any transcripts of the matching gene. Negative value means query ends upstream of reference.

You can use the `diff_to_TTS` and `diff_to_gene_TTS` columns to see if you have alternative polyadenylation, if that is what you want to do, although your exact aim is not clear from your question. Note that the polyA tail is generally removed during long-read pre-processing, so it is not included in the transcript models.

Hope that helps,

Ángeles
