### ISSUE TITLE
ImportError: cannot import name 'mean' from 'scipy' 

### ISSUE THREAD

**Issue by mianlee** [ConesaLab/SQANTI3#249]
Dear author:

I have successfully installed SQNTI3 and cDNA_cake, but when run sqanti3_qc.py, I had the following error.

```
(SQANTI3.env) mli@ca496d1fda31:~$ sqanti3_qc.py 
Traceback (most recent call last):
  File "/mnt/data/home/mli/Desktop/Software/SQANTI3-5.2/sqanti3_qc.py", line 20, in <module>
    from scipy import mean
ImportError: cannot import name 'mean' from 'scipy' (/mnt/data/home/mli/miniforge-pypy3/envs/SQANTI3.env/lib/python3.10/site-packages/scipy/__init__.py)
```

Thank you for your help!

Best
Mian

**Comment by mianlee** [comment]
Is it caused by the python version, python3.10? Thanks !

**Comment by mianlee** [comment]
I tested the  python version, python =3.8.18 worked for me.

I modified the [SQANTI3.conda_env.yml](https://github.com/ConesaLab/SQANTI3/blob/master/SQANTI3.conda_env.yml),

in line 29 from ```- python>=3.7.6``` to ``` -python = 3.8.18```.

I remove the previous environment by using:

```
$ conda env remove --name SQANTI3.env
```

and then re-run:

```
$  conda env create -f SQANTI3.conda_env.yml
```

It worked for me！

Best
Mian

**Comment by carolinamonzo** [comment]
Hi @mianlee ! Awesome! I'm glad you managed to fix it. Thanks a lot for documenting the process!

**Comment by aowenson-imm** [comment]
I too get this error. I tried specifying `python =3.8.18`, but then get another error when attempting to install cDNA_Cupcake:
```
  File "/tmp/easy_install-v8_au_rg/scikit-learn-1.4.1.post1/setup.py", line 629, in setup_package
RuntimeError: Scikit-learn requires Python 3.9 or later.
```

Modifying cDNA_Cupcake to install `scikit-learn<1.4` allowed install to complete. But I'm not qualified to say if this breaks something unexpected, I don't have capability to test all execution paths.

**Comment by carolinamonzo** [comment]
Hi @aowenson-imm, cDNA_cupcake is no longer a dependency from SQANTI as of v5.2.1. Also SQANTI's conda environment installs the correct version of the packages to avoid compatibility issues.
