### ISSUE TITLE
ERROR: gtf "chr1" chromosome not found in genome reference file.

### ISSUE THREAD

**Issue by mianlee** [ConesaLab/SQANTI3#250]
Hello :

I install the SQANTI3, and I can run the example successfully ! However, when I run the ```collapsed.gff ``` from ```isoseq colleapse```. I got the following error.

```
(SQANTI3.env) mli@ca496d1fda31:~/Desktop/pb_isoseq$ sqanti3_qc.py human_80K.collapsed.gff human_ref/GRCh38.fa human_ref/GRCh38.gtf \
 -o 80K -d SQANTI3_80K_output -fl human_80K.collapsed.flnc_count.txt\
 --isoAnnotLite --gff3 human_ref/human_tappas_gencode_annotation_file.gff3 \
 --report both
Rscript (R) version 4.3.1 (2023-06-16)
Write arguments to /mnt/data/home/mli/Desktop/pb_isoseq/SQANTI3_80K_output/80K.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /mnt/data/home/mli/Desktop/pb_isoseq/human_ref/GRCh38.gtf....
Skipping aligning of sequences because GTF file was provided.

ERROR: gtf "chr1" chromosome not found in genome reference file.

```

ERROR: gtf "chr1" chromosome not found in genome reference file.

I checked my reference .fa .gff  from gencode , they looks fine. 

Do you happen to know how I can fix this !

Best
Mian

**Comment by mianlee** [comment]
It looks like have to run the sqanti3_qc.py in the SQANTI3-5.2 folder.....it worked!

**Comment by carolinamonzo** [comment]
Hi @mianlee, yes, you have to run sqanti from the instalation directory unless you put it all in your $PATH variable to call it from other locations in your computer. I'm glad you managed to troubleshoot it!
