### ISSUE TITLE
reads/isoforms to isoforms compatibility matrix

### ISSUE THREAD

**Issue by houlinyu** [ConesaLab/SQANTI3#256]
Hi there,

I wonder if there is an option that SQUANTI3 can output a matrix that contains reads/isoforms (from our processed data) to isoforms (reference) compatibility- considering one read/isoform can FSM to one isoform but can be ISM to multiple other (longer) isoforms, etc.

Thanks,
Houlin

**Comment by lkondratova** [comment]
Hi Houlin, 
Although SQANTI is not specifically intended for aligning reads to isoforms, you can still utilize the --isoform_hits parameter. This will generate a separate file reporting all FSM/ISM hits for each read/isoform.

**Comment by houlinyu** [comment]
@lkondratova  Many thanks!!
