### ISSUE TITLE
illumna short reads

### ISSUE THREAD

**Issue by tky199996** [ConesaLab/SQANTI3#258]
Hello, I have been using SQANTI3 for analysis recently, I have full-length transcriptome data for 7 tissues, but my short-read sequencing data is only for 5 tissues, is this in line with the requirements of SQANTI3 run?

**Comment by carolinamonzo** [comment]
Hi @tky199996 that's up to you and your biological question. You can use sample-paired short and long-reads data, or public short reads with your long-reads data. This is not a SQANTI issue, it depends on your research aims.
