### ISSUE TITLE
Regarding use of reference genome for SQANTI3

### ISSUE THREAD

**Issue by Upendra19993** [ConesaLab/SQANTI3#261]
Hi, 

When using the reference genome for the SQANTI3 as an input, should we use the masked genome or the unmasked genome? And does it affect the result?

Many thanks, 
Upendra.

**Comment by carolinamonzo** [comment]
Hi @Upendra19993 that's up to you and your biological question. 
This is not a SQANTI issue, it depends on your research aims.

If you start your analysis from FASTQs, SQANTI3 will use minimap2 to map to the genome you give it.
