### ISSUE TITLE
no report output when use --report both

### ISSUE THREAD

**Issue by JXAUDZF** [ConesaLab/SQANTI3#266]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [x] I have loaded the SQANTI3.env conda environment

### Problem description

no report result--html or pdf file as output

### Code sample

singularity exec /home/Singusoft/sqanti3\:.sif ${python3} ~/software/SQANTI3-5.2/sqanti3_qc.py ${gtf} ${Refgtf} ${Reference} -o isoquant -d ./isoquant_sqanti3_output  --isoform_hits  --cpus 8 --report both

### Error

<img width="605" alt="image" src="https://github.com/ConesaLab/SQANTI3/assets/115453641/820a4345-a0ee-4f17-afb5-3a4f17325b74">

**Comment by alexpan00** [comment]
Hi @JXAUDZF 

Apparently, SQANTI3 crashed during the execution, that's why the report was not generated and the tmp files were not removed. However, without the error message, it is impossible to know where the error happened.

ALejandro.

**Comment by JXAUDZF** [comment]
Hi @alexpan00 
<img width="734" alt="image" src="https://github.com/ConesaLab/SQANTI3/assets/115453641/3ef05a41-79fc-4fcd-b51e-e3ad448cad5c">
This is error message,please help me to solve the problem.

**Comment by JXAUDZF** [comment]
<img width="1444" alt="image" src="https://github.com/ConesaLab/SQANTI3/assets/115453641/fa726d76-0113-485e-beda-d8510c3e317f">
<img width="557" alt="image" src="https://github.com/ConesaLab/SQANTI3/assets/115453641/5967212c-999a-49d8-b61a-e701d6c0c3b6">
<img width="1609" alt="image" src="https://github.com/ConesaLab/SQANTI3/assets/115453641/82866f6f-2399-472d-afdd-161948b809ec">

**Comment by alexpan00** [comment]
Hi @JXAUDZF, 

Regarding your first comment, it looks like you have some transcripts that don't have strand on your GTF file. That is what is causing the error.

Is the pdf report that was generated empty? Could you generate the HTML report in other runs? The problem seems to arise when the HTML file is created.

Alejandro

**Comment by JXAUDZF** [comment]
Hi @Alejandro,
Thank you for answering my questions!The pdf report is full and right ,what is more,I can not generate HTML report in other runs,only pdf report,therefore it is very strange.
JXAUDZF

**Comment by carolinamonzo** [comment]
Hi @JXAUDZF since your PDF reports are correctly generated, could you check if you can knit html files in your server? We have discussed it and we think you may have some sort of restrictions in your setup.

**Comment by carolinamonzo** [comment]
Closed since there's no response from the user and it looks like it's due to restrictions in his computing cluster, not an error of SQANTI.
