### ISSUE TITLE
Getting error message when running sqanti3 quality control step

### ISSUE THREAD

**Issue by Upendra19993** [ConesaLab/SQANTI3#267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [ ] I have loaded the SQANTI3.env conda environment

### Problem description

Hi, 

I wanted to run sqanti3 quality control step. Using the command below, I ran the job. its gives some errors which I mentioned below. Kindly request your help to resolve this issue.

### Code sample

sqanti3_qc.py --fasta clustering_clustered_hq_lq_279057_CD-Hit0.99.fasta Neelam_transcript-mRNA_gtfinfo_NIPB01022023QU_AGAT_FromBioBamMarta.gtf Neelam-Genome_Inv-corrected_Chr_QL_NIPB260822.fasta -o Neelum_HPC4 -d Neelum_HPC4 --short_reads RNA_seq_Neelum.fofn --cpus 24 --report pdf --force_id_ignore

### Error

Traceback (most recent call last):
  File "/sw/local/rocky8/noarch/qcif/software/SQANTI3-5.2/sqanti3_qc.py", line 2542, in <module>
    main()
  File "/sw/local/rocky8/noarch/qcif/software/SQANTI3-5.2/sqanti3_qc.py", line 2525, in main
    run(args)
  File "/sw/local/rocky8/noarch/qcif/software/SQANTI3-5.2/sqanti3_qc.py", line 1888, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/sw/local/rocky8/noarch/qcif/software/SQANTI3-5.2/sqanti3_qc.py", line 1719, in isoformClassification
    isoform_hit.CDS_genomic_start = m[isoform_hit.CDS_start-1] + 1  # make it 1-based
KeyError: 1087

### Anything else?

These are the output files I get. Classification and junction ffiles are saved as temp files. 
![image](https://github.com/ConesaLab/SQANTI3/assets/95351185/10e309c7-0af9-4148-bebc-08b6f0572cd2)

**Comment by carolinamonzo** [comment]
Hi @Upendra19993 the _tmp.txt files are there because the SQANTI run didn't finish due to the error. We have seen this error before in issue [#91](https://github.com/ConesaLab/SQANTI3/issues/91 ), it seems you have coding exons of 1bp long. Please try fixing your problems using the suggestions from the issue mentioned above.
Closing since this is a data-related issue, not a SQANTI issue.
