### ISSUE TITLE
cdna_cupcake fusion_collate_info.py

### ISSUE THREAD

**Issue by tky199996** [ConesaLab/SQANTI3#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [X] I have loaded the SQANTI3.env conda environment

### Problem description

I'm running fusion_collate_info.py script and I'm getting the fol

### Code sample

python ~/cDNA_Cupcake/cupcake/tofu/fusion_collate_info.py brain.fusion aligned.brain.sorted.sam.fusion_classification.txt ../../../../FL_ref20230605/12.ref/genes.gtf --genome aligned.brain.sorted.sam.fusion.rep.fa 

### Error

/home/tianky/cDNA_Cupcake/cupcake/tofu/fusion_collate_info.py:171: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  'ReadCountScore': count_d[pbid]*(10**6)/total_fl_count  if count_d[pbid] is not 'NA' else 'NA',
Finished reading reference genome aligned.brain.sorted.sam.fusion.rep.fa.
Reading ../../../../FL_ref20230605/12.ref/genes.gtf to extract gene name to ENSG ID mapping...
Traceback (most recent call last):
  File "/home/tianky/cDNA_Cupcake/cupcake/tofu/fusion_collate_info.py", line 229, in <module>
    collate_info(args.fusion_prefix, args.class_filename, args.gtf_filename,
  File "/home/tianky/cDNA_Cupcake/cupcake/tofu/fusion_collate_info.py", line 88, in collate_info
    seq_dict = dict((r.id.split('|')[0], r.seq) for r in SeqIO.parse(open(fusion_prefix + '.rep.fa'),'fasta'))
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'brain.fusion.rep.fa'

**Comment by carolinamonzo** [comment]
Hi @tky199996, is this an error from your SQANTI run? if so, could you share the sqanti command?

**Comment by carolinamonzo** [comment]
SQANTI3 no longer uses cDNA_cupcake as of v5.2.1
