### ISSUE TITLE
various errors when running sqanti3_qc

### ISSUE THREAD

**Issue by julienlag** [ConesaLab/SQANTI3#27]
Hello!
long-time long-read lover but first-time SQANTI user here... thanks for developing this tool and making it available to the community!
I'm running SQANTI on a GTF like so:

```
conda activate SQANTI3.env
export PYTHONPATH=$PYTHONPATH:$HOME/bin/SQANTI3/cDNA_Cupcake/sequence/
export PYTHONPATH=$PYTHONPATH:$HOME/bin/SQANTI3/cDNA_Cupcake/

python ~/bin/SQANTI3/sqanti3_qc.py --gtf --skipORF -d tmp tmp/isoforms.gff annotation.gff hg38.fa &> err.txt

```

[err.txt](https://github.com/ConesaLab/SQANTI3/files/5244664/err.txt) (abridged/edited for clarity)

SQANTI crashes while generating the report because of some R package install errors.

I subsequently installed the missing packages with conda/mamba (note that all commands following are issued under SQANTI3.env) :

```
mamba install -c bioconda bioconductor-noiseq
```

Relaunched SQANTI:

```
python ~/bin/SQANTI3/sqanti3_qc.py --gtf --skipORF -d tmp tmp/isoforms.gff annotation.gff hg38.fa &> err2.txt
```

[err2.txt](https://github.com/ConesaLab/SQANTI3/files/5244779/err2.txt)

Re-installed `ggplotify` as requested:

```
mamba install -c conda-forge r-ggplotify 

```

Relaunched SQANTI:

```
python ~/bin/SQANTI3/sqanti3_qc.py --gtf --skipORF -d tmp tmp/isoforms.gff annotation.gff hg38.fa &> err3.txt
```

[err3.txt](https://github.com/ConesaLab/SQANTI3/files/5244929/err3.txt)

I think this is something I won't be able to fix myself this time. Any help would be greatly appreciated!
Greetings,
Julien

**Comment by Magdoll** [comment]
Hi @julienlag ,

First off I assume you have updated to SQANTI3 v1.1 (I think you have based on the print out messages)?

Second, you can save some time to test *just* the Rscript part by calling

```
Rscript <path_to>/utilities/SQANTI3_report.R output_classification.txt output_junctions.txt
```

The other thing is we should try troubleshooting R packages first;


If you just launch R and type the following - any errors?
```
library(ggplot2)
library(ggplotify)
library(scales)
library(reshape)
library(gridExtra)
library(grid)
library(dplyr)
library(NOISeq)
```

```

**Comment by julienlag** [comment]
Hi Liz,

Thanks for looking into this. The R libraries are loading fine. In fact I've reinstalled SQANTI3 from scratch using a clean, up-to-date conda and I didn't run into the issues reported above in [err.txt](https://github.com/ConesaLab/SQANTI3/files/5244664/err.txt) and [err2.txt](https://github.com/ConesaLab/SQANTI3/files/5244779/err2.txt). 
However I'm still running into the last issue ([err3.txt](https://github.com/ConesaLab/SQANTI3/files/5244929/err3.txt).
I'll close this and open another more specific bug report
