### ISSUE TITLE
short_reads.py is. not robust

### ISSUE THREAD

**Issue by diekhans** [ConesaLab/SQANTI3#272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [X] I have loaded the SQANTI3.env conda environment

### Problem description

short_reads.py call os.system without checking error status.  Call subprocess are commented out when suprocess is the preferred method.

Also, a failed kallisto run could leave incomplete abundance_file to be reused later.

See me about the joy of atomic file creation

**Comment by carolinamonzo** [comment]
Solved by @lkondratova in commit [08da9b8](https://github.com/ConesaLab/SQANTI3/commit/08da9b81ecd60d92073d6bf9f95e0088c32829ff)
