### ISSUE TITLE
[BUG]  list index out of range

### ISSUE THREAD

**Issue by dawangran** [ConesaLab/SQANTI3#284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [X] I have loaded the SQANTI3.env conda environment

### Problem description

hello，
An error occurred when I was running qc. How can I solve it.

### Code sample

python sqanti3_qc.py merge.novel.transcript_models.gtf /media/AnalysisTempDisk2/Wangxue/project/15.cyclone_paper/00.data/ref/zebrafish/genes.gtf /media/AnalysisTempDisk2/Wangxue/project/15.cyclone_paper/00.data/ref/zebrafish/genome.fasta  --report pdf -d sqanti_report 

### Error

Rscript (R) version 4.3.1 (2023-06-16)
Write arguments to /media/AnalysisTempDisk2/Wangxue/project/tools/SQANTI3/sqanti_report/merge.novel.transcript_models.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /media/AnalysisTempDisk2/Wangxue/project/15.cyclone_paper/00.data/ref/zebrafish/genome.fasta....
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
**** Parsing Isoforms....
Splice Junction Coverage files not provided.
**** TSS ratio will not be calculated since SR information was not provided
**** Performing Classification of Isoforms....
Traceback (most recent call last):
  File "/media/AnalysisTempDisk2/Wangxue/project/tools/SQANTI3/sqanti3_qc.py", line 2546, in <module>
    main()
  File "/media/AnalysisTempDisk2/Wangxue/project/tools/SQANTI3/sqanti3_qc.py", line 2529, in main
    run(args)
  File "/media/AnalysisTempDisk2/Wangxue/project/tools/SQANTI3/sqanti3_qc.py", line 1874, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/media/AnalysisTempDisk2/Wangxue/project/tools/SQANTI3/sqanti3_qc.py", line 1614, in isoformClassification
    isoform_hit = associationOverlapping(isoform_hit, rec, junctions_by_chr)
  File "/media/AnalysisTempDisk2/Wangxue/project/tools/SQANTI3/sqanti3_qc.py", line 1346, in associationOverlapping
    if da_pairs[j][0] <= trec.txStart <= trec.txEnd <= da_pairs[j][1]:
IndexError: list index out of range

**Comment by alexpan00** [comment]
Hi, 

This bug should be fixed with the last commit, could you do git pull and try to run SQANTI again?

Alejandro
