### ISSUE TITLE
How are fusions defined by SQANTI

### ISSUE THREAD

**Issue by tky199996** [ConesaLab/SQANTI3#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [X] I have loaded the SQANTI3.env conda environment

### Problem description

Recently I was looking for fusion genes, I found fusion genes using pbfusion, but I found that there seems to be a fusion structure type in the SQANTI3, I looked at the corresponding annotated genes, and found that the results of the two software are completely different, I want to know if the genes corresponding to the fusion transcripts that SQANTI3 this software is looking for are different from the fusion genes that pbfusion is looking for?

**Comment by carolinamonzo** [comment]
Closing since this is not a SQANTI issue and there's an open discussion [#286](https://github.com/ConesaLab/SQANTI3/discussions/286) to comment on how SQANTI defines fusions.
