### ISSUE TITLE
Sam files missing header if genome too large

### ISSUE THREAD

**Issue by sarahhp** [ConesaLab/SQANTI3#29]
Hi there, 

I was getting the following error when running squanti3_qc.py with the hg38 genome fasta (supplying isoforms as fastq, not gtf):
![image](https://user-images.githubusercontent.com/43327001/94014425-cbe15a80-fdab-11ea-89fb-402fe6649f06.png)

And I noticed that minimap2 was giving the following warning earlier in the output: 
![image](https://user-images.githubusercontent.com/43327001/94014399-c2f08900-fdab-11ea-8db9-f457e3b133b9.png)

Sure enough, the all_samples.chained.rep_corrected.sam file in the output dir won't open with samtools because its missing the header.  

Luckily, I can switch to just using chr12, which fixed this for me, but other users may run into trouble with this if they're supplying large genomes.  Perhaps an option to supply your own sam file of isoforms aligned to the genome would help with this?

**Comment by Magdoll** [comment]
Hi @sarahhp ,
I'm pretty sure SQANTI3 has issues when you supply input isoforms or SAM files.
Right now - I strongly suggest users input just GFF3/GTF. I'm seriously considering removing the alignment support - I think it's not really good form that SQANTI3 has to make decisions on how to run aligners.

-Liz

**Comment by sarahhp** [comment]
@Magdoll Yeah that also makes sense.  I haven't tried with the GFF/GTF function.  Say can SQANTI3 use the gff format output by cupcake?

**Comment by Magdoll** [comment]
Hi @sarahhp  yes the cupcake output GFF will go into SQANTI3 just fine.
