### ISSUE TITLE
[BUG] squanti qc

### ISSUE THREAD

**Issue by dawangran** [ConesaLab/SQANTI3#295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [X] I have loaded the SQANTI3.env conda environment

### Problem description

Warning message:
package 'dplyr' was built under R version 4.3.2 
Warning message:
The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
i Please use the `linewidth` argument instead. 
Warning message:
Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
i Please use `linewidth` instead. 
Warning message:
A numeric `legend.position` argument in `theme()` was deprecated in ggplot2 3.5.0.
i Please use the `legend.position.inside` argument of `theme()` instead. 
`summarise()` has grouped output by 'lenCat'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'associated_transcript'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'associated_transcript'. You can override using the `.groups` argument.
[[1]]

[[1]]

[[1]]

[[1]]

Hello, there was an error when I was running qc. I'm not sure where I want to go. How can I solve it?

Error in ans[ypos] <- rep(yes, length.out = len)[ypos] : 
  replacement has length zero
Calls: generatePDFreport ... expand_limits_discrete_trans -> expand_limits_continuous_trans -> ifelse
In addition: Warning messages:
1: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
i Please use `after_stat(count)` instead. 
2: In rep(yes, length.out = len) : 'x' is NULL so the result will be NULL
Execution halted
Traceback (most recent call last):
  File "/SQANTI3/sqanti3_qc.py", line 2525, in <module>
    main()
  File "/SQANTI3/sqanti3_qc.py", line 2508, in main
    run(args)
  File "/SQANTI3/sqanti3_qc.py", line 2089, in run
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/usr/local/envs/SQANTI3.env/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/usr/local/envs/SQANTI3.env/bin/Rscript /SQANTI3/utilities//report_qc/SQANTI3_report.R /data/work/qc_report/OUT.novel.extended_annotation_classification.txt /data/work/qc_report/OUT.novel.extended_annotation_junctions.txt /data/work/qc_report/OUT.novel.extended_annotation.params.txt /SQANTI3/utilities False pdf' returned non-zero exit status 1.

**Comment by carolinamonzo** [comment]
Hi, can you share the command you used to run SQANTI3?

**Comment by alexpan00** [comment]
could you run this command to check if R produces a more informative error? 
`/usr/local/envs/SQANTI3.env/bin/Rscript /SQANTI3/utilities//report_qc/SQANTI3_report.R /data/work/qc_report/OUT.novel.extended_annotation_classification.txt /data/work/qc_report/OUT.novel.extended_annotation_junctions.txt /data/work/qc_report/OUT.novel.extended_annotation.params.txt /SQANTI3/utilities False pdf`

**Comment by alexpan00** [comment]
close due to inactivity

**Comment by camelest** [comment]
Hi, I have essentially the same error. I was trying to perform SQANTI3 QC on reference annotation for SQANTI3 rescue using SQANTI3 v5.2.1.

```
python sqanti3_qc.py \
gencode.vM25.primary_assembly.annotation.gtf \
gencode.vM25.primary_assembly.annotation.gtf \
GRCm38.fa \
-o genconde.vM25 -d SQANTI3_gencodevM25_output \
-fl abundance.txt --cpus 4 --report both
```

If I perform the R command you mentioned above, it gives

```
Warning message:
The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead. 
Warning message:
Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead. 
Warning message:
A numeric `legend.position` argument in `theme()` was deprecated in ggplot2 3.5.0.
ℹ Please use the `legend.position.inside` argument of `theme()` instead. 
`summarise()` has grouped output by 'lenCat'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'associated_transcript'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'associated_transcript'. You can override using the `.groups` argument.
[[1]]

Error in ans[ypos] <- rep(yes, length.out = len)[ypos] : 
  replacement has length zero
Calls: generatePDFreport ... expand_limits_discrete_trans -> expand_limits_continuous_trans -> ifelse
In addition: Warning messages:
1: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(count)` instead. 
2: Removed 55487 rows containing non-finite outside the scale range (`stat_boxplot()`). 
3: In rep(yes, length.out = len) : 'x' is NULL so the result will be NULL
Execution halted
```

Thank you so much for your help.

**Comment by alexpan00** [comment]
Hi, 

this is an error in the generation of the report. It is caused by everything being classified as FSM, which doesn't get along well with some of the plots in the report. You can use the outputs of this run, but to avoid this error in the future you can use --report skip option while running the reference against itself.

Alejandro
