### ISSUE TITLE
Issue generating rules filter report.

### ISSUE THREAD

**Issue by tinatucci** [ConesaLab/SQANTI3#304]
Hi,

I am able to filter all my qc files with the rules filter just fine, however the filter report doesn't generate.

Reading Rules result classification table...
Loading required package: ggplot2
Warning message:
package ‘ggplot2’ was built under R version 4.3.3 
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
Calls: suppressMessages ... withCallingHandlers -> install.packages -> startsWith -> contrib.url
Execution halted

I saw a similar issue in another post (below) however I'm not sure how to resolve this issue. I haven't used the argument --skip_report either.

              Hello @aarzalluz, thank you for your quick response.

I checked the log and it reported that the ML filter finished successfully.  When creating the report it reports a warning about ggplot:

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Loading required package: ggplot2
Warning message:
package ‘ggplot2’ was built under R version 4.3.3 
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
Calls: suppressMessages ... withCallingHandlers -> install.packages -> startsWith -> contrib.url
Execution halted

I guess this caused the problem. However, I followed the installation instructions on the wiki.

_Originally posted by @klenhart in https://github.com/ConesaLab/SQANTI3/issues/301#issuecomment-2129478372_

**Comment by alexpan00** [comment]
The solution on #259 has been implemented in the filter report script https://github.com/ConesaLab/SQANTI3/commit/96397a98fa8f6d36b9ad1e940bf85e89f0b30a36. Therefore, this shouldn't be a problem anymore.
