### ISSUE TITLE
[BUG] Error running qc

### ISSUE THREAD

**Issue by nkliutx** [ConesaLab/SQANTI3#309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [X] I have loaded the SQANTI3.env conda environment

### Problem description

I'm running sqanti3_qc.py, and it cannot generate full report files. I ran the command below to reproduce the error. It seems like no ism found caused this error. 

### Code sample

/usr/bin/Rscript /home/bio/data2/ovseqs/longread/sqanti3/SQANTI3/utilities//report_qc/SQANTI3_report.R /home/bio/data2/ovseqs/longread/sqanti3/SQANTI3/result/bambu/bam_classification.txt /home/bio/data2/ovseqs/longread/sqanti3/SQANTI3/result/bambu/bam_junctions.txt /home/bio/data2/ovseqs/longread/sqanti3/SQANTI3/result/bambu/bam.params.txt /home/bio/data2/ovseqs/longread/sqanti3/SQANTI3/utilities True both

### Error

Warning message:
The `size` argument of `element_line()` is deprecated as of ggplot2 3.4.0.
ℹ Please use the `linewidth` argument instead.
Warning message:
Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.
Warning message:
A numeric `legend.position` argument in `theme()` was deprecated in ggplot2 3.5.0.
ℹ Please use the `legend.position.inside` argument of `theme()` instead.
`summarise()` has grouped output by 'lenCat'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'associated_transcript'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'associated_transcript'. You can override using the `.groups` argument.
[[1]]

[[1]]
NULL

[[1]]

[[1]]

[[1]]

[[1]]

[[1]]

[[1]]

[[1]]

[[1]]
NULL

[[1]]
NULL

[[1]]
NULL

[[1]]
NULL

[[1]]
NULL

[[1]]
NULL

[[1]]

[[1]]

[1] "SQANTI3 report successfully generated!"
In addition: There were 11 warnings (use warnings() to see them)

processing file: SQANTI3_report.Rmd
  |................        |  66% [unnamed-chunk-31]
Quitting from lines 884-912 [unnamed-chunk-31] (SQANTI3_report.Rmd)
Error in `ans[ypos] <- rep(yes, length.out = len)[ypos]`:
! replacement has length zero
Backtrace:
  1. ggplotly(cage_hist_ISM) %>% ...
  4. plotly:::ggplotly.ggplot(cage_hist_ISM)
  5. plotly::gg2list(...)
  6. plotly (local) ggplotly_build(p)
  7. layout$setup_panel_params()
     ...
 15. ggplot2:::expand_limits_scale(scale, expansion, limits, coord_limits = coord_limits)
 16. ggplot2:::expand_limits_discrete(...)
 17. ggplot2:::expand_limits_discrete_trans(...)
 18. ggplot2:::expand_limits_continuous_trans(...)
 19. base::ifelse(is.na(coord_limits), limits, coord_limits)

### Anything else?

This is the classfication.txt
     35 antisense
  37202 full-splice_match
     11 fusion
     13 genic
     11 genic_intron
    438 intergenic
    319 novel_in_catalog
    193 novel_not_in_catalog
      1 structural_category

**Comment by alexpan00** [comment]
Hi,

yes, some of the plots assume that you have a particular structural category, in this case, ISM, and when the SC is not present it can crash. We are working to avoid this kind of crash, but is not a priority. You can comment those lines in the SQANTI3_report.R and it should work. If you have used polyA motifs it may also crash there.

Sorry for the inconvenience,
Alejandro
