### ISSUE TITLE
document skip_report option

### ISSUE THREAD

**Issue by julienlag** [ConesaLab/SQANTI3#31]
I've skimmed through SQANTI code to see if it was possible to skip the PDF report generation altogether (i.e., produce only text files). This is very useful because in my experience this is by far the most memory- and CPU-hungry part of the run and not everybody's interested in SQANTI's PDF reports. I found out that there actually is such an option (`--skip_report`), except it's hidden in the code and not documented in SQANTI's help.

**Comment by Magdoll** [comment]
ah, yes, I'll make sure that option is documented. i'll close this tix when it's doc-ed

**Comment by aarzalluz** [comment]
Just wanted to add that it would indeed be really helpful to have this reported in the documentation. I was running SQANTI3 and tried to check whether there was a `--skip_report` option available, but wouldn't have found out that it existed if it weren't for this issue.

**Comment by aarzalluz** [comment]
The `--report` argument now accepts four options: `html` `pdf` `both` or `skip`. Providing `--report skip` two SQANTI3 therefore means that no report will be generated.
