### ISSUE TITLE
The installation of SQANTI3-5.2.1 encountered an error

### ISSUE THREAD

**Issue by biochristmas** [ConesaLab/SQANTI3#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [X] I have loaded the SQANTI3.env conda environment

### Problem description

Hi, I recently installed SQANTI3, and when I executed the code “conda env create -f SQANTI3.conda_env.yml”, an error occurred. The error message was

### Code sample

Here’s the command I used to install the software: 
wget https://github.com/ConesaLab/SQANTI3/archive/refs/tags/v5.2.1.tar.gz
tar -xf v5.2.1.tar.gz
cd SQANTI3-5.2.1
conda env create -f SQANTI3.conda_env.yml

### Error

[error.txt](https://github.com/user-attachments/files/15958255/error.txt)

**Comment by weiwei4396** [comment]
I have the same problem

**Comment by biochristmas** [comment]
> Hi,
> 
> This is caused by some problems with the latest Python version, if you force it to be <= 3.11 it should work. In the yml replace the Python line with this:
> 
> * python>=3.7.6,<=3.11
> 
> Alejandro

Thank you for your prompt response. The error has been resolved after modifying the Python version
