### ISSUE TITLE
sqanti3 out put: same sequences with different ID

### ISSUE THREAD

**Issue by B10inform** [ConesaLab/SQANTI3#33]
Hi, 

Sqanti3 gives similar sequences with different ID. How can i select single sequence.
Here is an example:

>PB.3.1-gene_1|GeneMark.hmm|459_aa|+|3033|4412
MAGELVEFEEGTIGIALNLESTNVGVVLMGDGLMIQEGSSVKATGKIAQIPVSEAYLGRVINALAKPIDGRGEISASESRLIESPAPGIISRRSVYEPLQTGLIAIDSMIPIGRGQRELIIGDRQTGKTAVATDTILNQQGQNVICVYVAIGQKASSVAQVVNTFQERGAMDYTIVVAETADSPATLQYLAPYTGAALAEYFMYRERHTLIIYDDPSKQAQAYRQMSLLLRRPPGREAYPGDVFYLHSRLLERAAKLGSQLGEGSMTALPIVETQSGDVSAYIPTNVISITDGQIFLSADLFNAGIRPAINVGISVSRVGSAAQIKAMKQVAGKLKLELAQFAELEAFAQFASDLDKATQNQLARGQRLRELLKQAQAAPLTVEEQIMTIYTGTNGYLDSLEIGQVRKFLVELRTYLKTNKPQFQEIISSTKIFTEEAEALLQEAIQEQKERFLLQEQF
>PB.3.2-gene_3|GeneMark.hmm|459_aa|+|2238|3617
MAGELVEFEEGTIGIALNLESTNVGVVLMGDGLMIQEGSSVKATGKIAQIPVSEAYLGRVINALAKPIDGRGEISASESRLIESPAPGIISRRSVYEPLQTGLIAIDSMIPIGRGQRELIIGDRQTGKTAVATDTILNQQGQNVICVYVAIGQKASSVAQVVNTFQERGAMDYTIVVAETADSPATLQYLAPYTGAALAEYFMYRERHTLIIYDDPSKQAQAYRQMSLLLRRPPGREAYPGDVFYLHSRLLERAAKLGSQLGEGSMTALPIVETQSGDVSAYIPTNVISITDGQIFLSADLFNAGIRPAINVGISVSRVGSAAQIKAMKQVAGKLKLELAQFAELEAFAQFASDLDKATQNQLARGQRLRELLKQAQAAPLTVEEQIMTIYTGTNGYLDSLEIGQVRKFLVELRTYLKTNKPQFQEIISSTKIFTEEAEALLQEAIQEQKERFLLQEQF
>PB.3.3-gene_4|GeneMark.hmm|459_aa|+|2006|3385
MAGELVEFEEGTIGIALNLESTNVGVVLMGDGLMIQEGSSVKATGKIAQIPVSEAYLGRVINALAKPIDGRGEISASESRLIESPAPGIISRRSVYEPLQTGLIAIDSMIPIGRGQRELIIGDRQTGKTAVATDTILNQQGQNVICVYVAIGQKASSVAQVVNTFQERGAMDYTIVVAETADSPATLQYLAPYTGAALAEYFMYRERHTLIIYDDPSKQAQAYRQMSLLLRRPPGREAYPGDVFYLHSRLLERAAKLGSQLGEGSMTALPIVETQSGDVSAYIPTNVISITDGQIFLSADLFNAGIRPAINVGISVSRVGSAAQIKAMKQVAGKLKLELAQFAELEAFAQFASDLDKATQNQLARGQRLRELLKQAQAAPLTVEEQIMTIYTGTNGYLDSLEIGQVRKFLVELRTYLKTNKPQFQEIISSTKIFTEEAEALLQEAIQEQKERFLLQEQF
>PB.3.4-gene_6|GeneMark.hmm|459_aa|+|1128|2507
MAGELVEFEEGTIGIALNLESTNVGVVLMGDGLMIQEGSSVKATGKIAQIPVSEAYLGRVINALAKPIDGRGEISASESRLIESPAPGIISRRSVYEPLQTGLIAIDSMIPIGRGQRELIIGDRQTGKTAVATDTILNQQGQNVICVYVAIGQKASSVAQVVNTFQERGAMDYTIVVAETADSPATLQYLAPYTGAALAEYFMYRERHTLIIYDDPSKQAQAYRQMSLLLRRPPGREAYPGDVFYLHSRLLERAAKLGSQLGEGSMTALPIVETQSGDVSAYIPTNVISITDGQIFLSADLFNAGIRPAINVGISVSRVGSAAQIKAMKQVAGKLKLELAQFAELEAFAQFASDLDKATQNQLARGQRLRELLKQAQAAPLTVEEQIMTIYTGTNGYLDSLEIGQVRKFLVELRTYLKTNKPQFQEIISSTKIFTEEAEALLQEAIQEQKERFLLQEQF
>PB.3.5-gene_7|GeneMark.hmm|459_aa|+|997|2376
MAGELVEFEEGTIGIALNLESTNVGVVLMGDGLMIQEGSSVKATGKIAQIPVSEAYLGRVINALAKPIDGRGEISASESRLIESPAPGIISRRSVYEPLQTGLIAIDSMIPIGRGQRELIIGDRQTGKTAVATDTILNQQGQNVICVYVAIGQKASSVAQVVNTFQERGAMDYTIVVAETADSPATLQYLAPYTGAALAEYFMYRERHTLIIYDDPSKQAQAYRQMSLLLRRPPGREAYPGDVFYLHSRLLERAAKLGSQLGEGSMTALPIVETQSGDVSAYIPTNVISITDGQIFLSADLFNAGIRPAINVGISVSRVGSAAQIKAMKQVAGKLKLELAQFAELEAFAQFASDLDKATQNQLARGQRLRELLKQAQAAPLTVEEQIMTIYTGTNGYLDSLEIGQVRKFLVELRTYLKTNKPQFQEIISSTKIFTEEAEALLQEAIQEQKERFLLQEQF
>PB.3.6-gene_8|GeneMark.hmm|351_aa|+|192|1247
MIPIGRGQRELIIGDRQTGKTAVATDTILNQQGQNVICVYVAIGQKASSVAQVVNTFQERGAMDYTIVVAETADSPATLQYLAPYTGAALAEYFMYRERHTLIIYDDPSKQAQAYRQMSLLLRRPPGREAYPGDVFYLHSRLLERAAKLGSQLGEGSMTALPIVETQSGDVSAYIPTNVISITDGQIFLSADLFNAGIRPAINVGISVSRVGSAAQIKAMKQVAGKLKLELAQFAELEAFAQFASDLDKATQNQLARGQRLRELLKQAQAAPLTVEEQIMTIYTGTNGYLDSLEIGQVRKFLVELRTYLKTNKPQFQEIISSTKIFTEEAEALLQEAIQEQKERFLLQEQF
>PB.3.8-gene_9|GeneMark.hmm|247_aa|+|226|969
MNVLSCSMNTLRGLYDISGVEVGQHFYWQIGGFQVHAQVLITSWVVIAILLGSAFIAVRNPQTVPTATQNFFEYVLEFIRDVSKTQIGEEYGPWVPFIGTLFLFIFVSNWSGALLPWKIIELPHGELAAPTNDINTTVALALLTSIAYFYAGLSKKGLGYFSKYIQPTPILLPINILEDFTKPLSLSFRLFGNILADELVVVVLVSLVPLVVPIPVMFLGLFTSGIQALIFATLAAAYIGESMEGHH

**Comment by B10inform** [comment]
Hi Liz,

Since the predicted ORFs (AA) are same (transcripts sequence are different), and have same functional annotation, how to classify them? There are thousands of such transcripts.

So you think these transcripts are not quintuple (they have exact same AA sequence but different nucleotide sequence)? 
PB.3.1-gene_1|GeneMark.hmm|459_aa|+|3033|4412
PB.3.2-gene_3|GeneMark.hmm|459_aa|+|2238|3617
PB.3.3-gene_4|GeneMark.hmm|459_aa|+|2006|3385
PB.3.4-gene_6|GeneMark.hmm|459_aa|+|1128|2507
PB.3.5-gene_7|GeneMark.hmm|459_aa|+|997|2376

Thanks

**Comment by Magdoll** [comment]
@B10inform  - they can have different nucleotide sequences with the same AA sequence - that is certainly not unusual. They can also differ in UTR exons which seems to be the case for the examples you pointed out - they all have different lengths.
