### ISSUE TITLE
[BUG] IndexError: list index out of range

### ISSUE THREAD

**Issue by YIGUIz** [ConesaLab/SQANTI3#334]
### Problem description
I have loaded the SQANTI3.env conda environment

The same question have been reported in https://github.com/ConesaLab/SQANTI3/issues/329. I tried it with the new version and failed to solve this problem. Besides, the *corrected.gtf file exists and is normal.

corrected.gtf:
![image](https://github.com/user-attachments/assets/db34a1d3-ba1f-40d4-a19c-16a1fa33b512)

### Code sample

Here is the command: 
`/00bin/SQANTI3-5.2.2/sqanti3_qc.py adipose_final.gtf GCF_002263795.3_ARS-UCD2.0_genomic.gtf GCF_002263795.3_ARS-UCD2.0_genomic.fna --force_id_ignore --dir ./ --cpus 20 --short_reads test_short_reads.fofn --skipORF --report both --ignore-report-errors`

_No response_

### Error
![image](https://github.com/user-attachments/assets/b9546ea8-a18d-4da4-8840-31df7928e732)

Looking forward to your reply.

Qi

**Comment by Fabian-RY** [comment]
Hi @YIGUIz thanks for reaching us out

I can see that you're using StringTie in your screenshot. @alexpan00 and I noticed that there are some transcripts in your data that do not have an strand value in your corrected gtf (it is a '.' instead of '+' or '-'). That is making SQANTI fail due to how BCBio_GFF parses the file.

I will work on a fix for the next release.

Thanks

**Comment by carolinamonzo** [comment]
In the meantime, you can refer to [#21](https://github.com/ConesaLab/SQANTI3/issues/21), [#56](https://github.com/ConesaLab/SQANTI3/issues/56), [#142](https://github.com/ConesaLab/SQANTI3/issues/142) or [#235](https://github.com/ConesaLab/SQANTI3/issues/235) for details and suggestions on how to solve this problem.

**Comment by YIGUIz** [comment]
> Hi @YIGUIz thanks for reaching us out
> 
> I can see that you're using StringTie in your screenshot. @alexpan00 and I noticed that there might be some transcripts in your data that do not have an strand value in your corrected gtf (it is a '.' instead of '+' or '-'). That is making SQANTI fail due to how BCBio_GFF parses the file.
> 
> I will work on a fix for the next release.
> 
> Thanks

Thank you! I have other questions. If I collect hundreds and thousands of public SR RNA-seq to validate, how can I perform it quickly?  Can I get Long read coverage of transcripts by SQANTI3？
