### ISSUE TITLE
[BUG] An error occurred while installing package bioconda::bioconductor-genomeinfodbdata-1.2.11-r43hdfd78af_1

### ISSUE THREAD

**Issue by emsisson** [ConesaLab/SQANTI3#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [X] I have loaded the SQANTI3.env conda environment

### Problem description

Using Miniconda3-py39_4.12.0 and running command
```
conda env create -f SQANTI3.conda_env.yml
```
failed with message
```
ERROR conda.core.link:_execute(952): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.11-r43hdfd78af_1'.
```

### Anything else?

After much experimenting I traced the problem to the version of Conda package **libnghttp2**. Conda installed the latest version, 1.58.0, but forcing installation of previous version 1.55.1 allowed the installation to complete successfully. I edited file **SQANTI3.conda_env.yml** to add the following line to section **dependencies:**
```
- libnghttp2=1.55.1
```

This solved my problem, so this issue can be closed. I am posting this for the benefit of others.

**Comment by Fabian-RY** [comment]
Hi @emsisson 

Thanks for your contribution. I've recreated the Conda environment in different installations of conda, and the environments are created correctly without any error with
