### ISSUE TITLE
Issues in final report generation

### ISSUE THREAD

**Issue by JieqiongDai** [ConesaLab/SQANTI3#34]
I got an error when running SQANTI3 with some of my samples at the final step of summary report generation. 
I beleive that is because I used data with collapsed isoforms of targed genes. There is no ">=6" or even "4-5" nIso in my data. 
Could you please fix the related code in SQANTI3_report.R or add the option to skip summary report generation?
Thanks!

> Error in cut.default(isoPerGene$nIso, breaks = c(0, 1, 3, 5, max(isoPerGene$nIso) +  : 
  'breaks' are not unique
Calls: cut -> cut.default
Execution halted

> subprocess.CalledProcessError:` Command '/home/daij/miniconda2/envs/SQANTI3.env/bin/Rscript /gpfs/gsfs10/users/DCEG_RTEL/references/SQANTI3/utilities//SQANTI3_report.R /gpfs/gsfs10/users/DCEG_RTEL/DJQ/sqanti3/test_isoseq3_sqanti3/sqanti_r2/lima_output.lbc73--lbc73.collapsed.filtered.rep_classification.txt /gpfs/gsfs10/users/DCEG_RTEL/DJQ/sqanti3/test_isoseq3_sqanti3/sqanti_r2/lima_output.lbc73--lbc73.collapsed.filtered.rep_junctions.txt /gpfs/gsfs10/users/DCEG_RTEL/DJQ/sqanti3/test_isoseq3_sqanti3/sqanti_r2/lima_output.lbc73--lbc73.collapsed.filtered.rep.params.txt /gpfs/gsfs10/users/DCEG_RTEL/references/SQANTI3/utilities/' returned non-zero exit status 1.

**Comment by Magdoll** [comment]
This should be fixed in SQANTI3 v1.6 now. Plz check.
-Liz
