### ISSUE TITLE
[BUG] SQANTI filter not producing output 

### ISSUE THREAD

**Issue by sparthib** [ConesaLab/SQANTI3#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [X] I have loaded the SQANTI3.env conda environment

### Problem description

SQANTI filter mode not filtering both in rules or ML mode. 
I tried the very basic command on just the classification text file, in my log file I see  `"Running SQANTI3 filtering..."`
In the next step, it immediately seems to look for the  `inclusion-list.txt` instead of running the rules or ML filter. 

### Code sample

`python $SQANTI_DIR/sqanti3_filter.py rules $INPUT_DIR/all_samples_classification.txt`
`python $SQANTI_DIR/sqanti3_filter.py ml $INPUT_DIR/all_samples_classification.txt`

### Error

```
Running SQANTI3 filtering...

Traceback (most recent call last):
  File "/users/sparthib/SQANTI3-5.2.1/sqanti3_filter.py", line 292, in <module>
    main()
  File "/users/sparthib/SQANTI3-5.2.1/sqanti3_filter.py", line 288, in main
    ids, inclusion_file = run_rules(args)
  File "/users/sparthib/SQANTI3-5.2.1/sqanti3_filter.py", line 146, in run_rules
    seqs_to_keep = set(line.strip() for line in open(inclusion_list))
FileNotFoundError: [Errno 2] No such file or directory: 'path_to_output/all_samples/sqanti3_qc/all_samples_inclusion-list.txt'
**** Job ends ****
```

**Comment by Fabian-RY** [comment]
Hi @sparthib , thank you for using SQANTI3.

According to the error, it seems that at least one of the subdirectories in your path does not exist. Can you please check if the path and the file mentioned in the error exist ("path_to_output/all_samples/all_samples_inclusion-list.txt")? I

Thanks

**Comment by sparthib** [comment]
the issue turned out to be that the R script `SQANTI3_rules_filter.R` couldn't find the `optparse` library and I had to reinstall it in the environment. Thanks!
