### ISSUE TITLE
Missing associated_gene for some "antisense" isoforms

### ISSUE THREAD

**Issue by avnanni** [ConesaLab/SQANTI3#35]
I am trying to use SQANTI3 QC to classify isoforms and identify the associated reference genes from a reference annotation. No errors occurred in the generation of the output files, but one of the chromosomes (named MtDNA) seems to have some isoforms that are not properly classified (all were classified as "antisense" despite some having no overlap with reference genes) and did not have an associated_gene value. Below are the arguments I used for SQANTI3 QC. Attached are 1) a subset of the reference gtf file used with all MtDNA elements (MtDNA.gtf.txt), 2) the lines of the classification file that do not have an associated_gene value (adult_combine_no_associated_gene_classification.txt), and 3) the lines from the isoform gtf file that did not get an associated_gene value (adult_combine_no_associated_gene.gtf.txt).
This set of isoforms contains mostly mono-exon and a few multi-exon isoforms, but these are not the only isoforms from this chromosome. Other mono-exon and multi-exon isoforms seem to be properly classified and assigned an associated_gene so it does not look to be the chromosome itself causing the issue.

I would appreciate any advice on how to fix this issue if it is possible. Thank you!

python $SCRIPTS/SQANTI3/sqanti3_qc.py \
                --gtf \
                --skipORF \
                --force_id_ignore \
                --dir ${OUTDIR}/${NAME} \
                -o ${NAME} \
                ${SAMPLEGTF} \
                ${REFGTF} \
                ${FA}

[MtDNA.gtf.txt](https://github.com/ConesaLab/SQANTI3/files/5692356/MtDNA.gtf.txt)
[adult_combine_no_associated_gene_classification.txt](https://github.com/ConesaLab/SQANTI3/files/5692368/adult_combine_no_associated_gene_classification.txt)
[adult_combine_no_associated_gene.gtf.txt](https://github.com/ConesaLab/SQANTI3/files/5692428/adult_combine_no_associated_gene.gtf.txt)

**Comment by Magdoll** [comment]
Hi @avnanni ,
I believe that may be a classification error on SQANTI3's part! Can you update to v1.5. and see if this is corrected now?
Thanks,
-Liz

**Comment by avnanni** [comment]
Liz,

Yes, updating to v1.5 has corrected the issue.

Thank you!
