### ISSUE TITLE
[BUG]  No such file or directory

### ISSUE THREAD

**Issue by handesome** [ConesaLab/SQANTI3#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [X] I have loaded the SQANTI3.env conda environment

### Problem description

I‘m the beginner there,when I run the code below,it gets an error。could anyone give me a hand？ Thanks！！

### Code sample

sqanti3_qc.py /data/work/temp2/gtf_talon.gtf /data/work/gencode.v46.primary_assembly.basic.annotation.gtf /data/work/GRCh38.primary_assembly.genome.fa \
--CAGE_peak /opt/SQANTI3/data/ref_TSS_annotation/human.refTSS_v3.1.hg38.bed \
--polyA_motif_list /opt/SQANTI3/data/polyA_motifs/mouse_and_human.polyA_motif.txt \
--coverage /data/work/pass2/pass2SJ.out.tab\
--force_id_ignore \
--skipORF \
--report pdf \
--dir /data/work/temp2/sqan \
--output ./output

### Error

mustOpen: Can't open /data/work/temp2/sqan/refAnnotation_./output.genePred to write: No such file or directory
Traceback (most recent call last):
  File "/opt/SQANTI3/sqanti3_qc.py", line 2627, in <module>
    main()
  File "/opt/SQANTI3/sqanti3_qc.py", line 2610, in main
    run(args)
  File "/opt/SQANTI3/sqanti3_qc.py", line 1896, in run
    refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene = reference_parser(args, list(genome_dict.keys()))
                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/SQANTI3/sqanti3_qc.py", line 676, in reference_parser
    for r in genePredReader(referenceFiles):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/SQANTI3/sqanti3_qc.py", line 124, in __init__
    self.f = open(filename)
             ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/work/temp2/sqan/refAnnotation_./output.genePred'

**Comment by alexpan00** [comment]
Hi @handesome 

in the --output flag you put output, not ./output. If you want to wirtite the sqant/output folder include output in the --dir argument, i.e. `--dir /data/work/temp2/sqan/output --output output`

Alejandro

**Comment by handesome** [comment]
Thank you for the quick reply！！I got it！Thanks again！
