### ISSUE TITLE
sqanty_read :: invalid sheebang

### ISSUE THREAD

**Issue by EricDeveaud** [ConesaLab/SQANTI3#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [ ] I have loaded the SQANTI3.env conda environment

### Problem description

Hello.

sheebang on squanty_read.py is incorrect.
see: https://github.com/ConesaLab/SQANTI3/blob/aaeb9070bddacd2e0dfbc2f6add6ec10bfa42bc2/sqanti_reads.py#L1

regards

Eric

**Comment by carolinamonzo** [comment]
Hi @EricDeveaud, Thanks for using sqanti-reads and pointing out this error. It's now fixed by PR #356.
