### ISSUE TITLE
merge multiple sampels' classification results

### ISSUE THREAD

**Issue by sunshine-lp0** [ConesaLab/SQANTI3#36]
Hi,
Thanks for very very useful tool for isoform characterization. 
How to merge multiple sampels' classification results and generate one report pdf file? The most important promblem is how to consider the boundary of exons in isoforms. 

Best wishes,
ping

**Comment by Magdoll** [comment]
Hi @sunshine-lp0 ,
Best way is probably to chain the isoforms first using [Cupcake chaining](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#chain) or [TAMA merge](https://github.com/GenomeRIK/tama/wiki/Tama-Merge).

SQANTI3 can accept `--fl_count` that is a multi-sample count file.

Alternatively you can go the other way around - after running SQANTI3 on various samples, you now have the GTF/GFF3 for each sample, you can just use Cupcake chain or TAMA merge on the per-sample GTF/GFF3 and manually combine the SQANTI3 results into a single classification.txt and junctions.txt file

-Liz

**Comment by sunshine-lp0** [comment]
> Hi @sunshine-lp0 ,
> Best way is probably to chain the isoforms first using [Cupcake chaining](https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step#chain) or [TAMA merge](https://github.com/GenomeRIK/tama/wiki/Tama-Merge).
> 
> SQANTI3 can accept `--fl_count` that is a multi-sample count file.
> 
> Alternatively you can go the other way around - after running SQANTI3 on various samples, you now have the GTF/GFF3 for each sample, you can just use Cupcake chain or TAMA merge on the per-sample GTF/GFF3 and manually combine the SQANTI3 results into a single classification.txt and junctions.txt file
> 
> -Liz

Thank you very much!
