### ISSUE TITLE
[BUG] Error in `dplyr::filter()`: ℹ In argument: `isoform %in% classif_ism_fsm$isoform`.

### ISSUE THREAD

**Issue by yerry77** [ConesaLab/SQANTI3#367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you loaded the SQANTI3.env conda environment?

- [X] I have loaded the SQANTI3.env conda environment

### Problem description

The file does contain a column named 'isoform', but I don't know why it's still throwing an error. I was able to run it normally with the hg38 version of the reference, but now I'm getting this error message when using the T2T version of the reference.

### Code sample
python /data/p/SQANTI3/SQANTI3-5.2.1/sqanti3_rescue.py rules \
--isoforms /XCLabServer003_fastIO/20241218SQANTI3_T2T_long_read/QC_result/long_read_T2T_corrected.fasta \
--gtf /XCLabServer003_fastIO/20241218SQANTI3_T2T_long_read/filtered_result/long_read_T2T.filtered.gtf \
-g /data1/pub/genome/Human/humanT2T/GCF_009914755.1-RS_2023_03/GCF_009914755.1_T2T-CHM13v2.0_genomic.gtf \
-f /data1/pub/genome/Human/humanT2T/chm13v2.0.fa \
-k /XCLabServer003_fastIO/20241218SQANTI3_T2T_long_read/QC_result/long_read_T2T_classification.txt \
-e all \
--mode full \
-o long_read_T2T \
-d /XCLabServer003_fastIO/20241218SQANTI3_T2T_long_read/rescue_result \
-j /data/p/SQANTI3/SQANTI3-5.2.1/utilities/filter/filter_default.json \
/XCLabServer003_fastIO/20241218SQANTI3_T2T_long_read/filtered_result/long_read_T2T_RulesFilter_result_classification.txt

### Error

Error in `dplyr::filter()`:
ℹ In argument: `isoform %in% classif_ism_fsm$isoform`.
Caused by error:
! object 'isoform' not found
Backtrace:
     ▆
  1. ├─rescue %>% ...
  2. ├─dplyr::filter(., isoform %in% classif_ism_fsm$isoform)
  3. ├─dplyr:::filter.data.frame(., isoform %in% classif_ism_fsm$isoform)
  4. │ └─dplyr:::filter_rows(.data, dots, by)
  5. │   └─dplyr:::filter_eval(...)
  6. │     ├─base::withCallingHandlers(...)
  7. │     └─mask$eval_all_filter(dots, env_filter)
  8. │       └─dplyr (local) eval()
  9. ├─isoform %in% classif_ism_fsm$isoform
 10. └─base::.handleSimpleError(...)
 11.   └─dplyr (local) h(simpleError(msg, call))
 12.     └─rlang::abort(message, class = error_class, parent = parent, call = error_call)
Execution halted
Traceback (most recent call last):
  File "/data/p/SQANTI3/SQANTI3-5.2.1/sqanti3_rescue.py", line 660, in <module>
    main()
  File "/data/p/SQANTI3/SQANTI3-5.2.1/sqanti3_rescue.py", line 557, in main
    auto_result = run_automatic_rescue(args)
  File "/data/p/SQANTI3/SQANTI3-5.2.1/sqanti3_rescue.py", line 59, in run_automatic_rescue
    if subprocess.check_call(auto_cmd, shell = True) != 0:
  File "/data/p/anaconda3/envs/SQANTI3.env/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/data/p/anaconda3/envs/SQANTI3.env/bin/Rscript /data/p/SQANTI3/SQANTI3-5.2.1/utilities/rescue/automatic_rescue.R -c /XCLabServer003_fastIO/20241218SQANTI3_T2T_long_read/filtered_result/long_read_T2T_RulesFilter_result_classification.txt -o long_read_T2T -d /XCLabServer003_fastIO/20241218SQANTI3_T2T_long_read/rescue_result -u /data/p/SQANTI3/SQANTI3-5.2.1/utilities   -g /XCLabServer003_fastIO/20241218stringtie_T2T_short_read/GCF_009914755.1_T2T-CHM13v2.0_genomic_fixed.gtf -e all -m full' returned non-zero exit status 1.

**Comment by lilif99** [comment]
Hello, how was this resolved- I'm having the same issue
