### ISSUE TITLE
Difference in number of genes in SQANTI report and fasta file

### ISSUE THREAD

**Issue by Sameerpython** [ConesaLab/SQANTI3#37]
Hi,

I have the PacBio Isoseq data and  I used SQANTI for the analysis. After performing sqanti_qc analysis, in the report it is mentioned as the number of unique gene is 23758 and unique isoforms is 102367. But counting the transcripts in GFF file, the number is 12911.

So why is the number different between the report and gff file?

Thanks!!

**Comment by Magdoll** [comment]
Hi @Sameerpython 
Can you show the exact filenames you used to count the # of transcripts?
This should not happen. Maybe some incomplete run?
-Liz

**Comment by Magdoll** [comment]
Closing unless OP reopens.
