### ISSUE TITLE
Suggested README addition

### ISSUE THREAD

**Issue by wheelern** [ConesaLab/SQANTI3#4]
Thanks for working on this merge (and removing the reliance upon GMAP).

I'm working on re-doing some old analysis and immediately got an error about reads not being in PB.X.Y format. I found in `sqanti3_qc.py` the option `--force_id_ignore` and using that worked. I think it would be good to add that requirement (and option) to the README; I don't currently see it.

**Comment by FJPardoPalacios** [comment]
Thank you for the suggestion, you are totally right!
Now the `--force_id_ignore` option is visible and it available in the README.
