### ISSUE TITLE
Invalid input IDs on custom fasta

### ISSUE THREAD

**Issue by dpaudel** [ConesaLab/SQANTI3#42]
I am trying to run sqanti3_qc on custom clustered isoforms and it throws the following error:
`Invalid input IDs! Expected PB.X.Y or PB.X.Y|xxxxx or PBfusion.X format but saw m54217_190408_162523/31458270/ccs instead. Abort!`
Should I rename the fasta file or is there an option to specify custom files?

**Comment by sbaheijmcdkhoaj** [comment]
The ID name of the input file must be PB.X.Y.    Maybe your input file is not from cDNA_cupcake or TAMA?

**Comment by Magdoll** [comment]
For future, you can add `--force_id_ignore` to ignore required ID formats.

**Comment by CCBenne** [comment]
I am having this same issue. But I have also supplied the -fl argument which is in PB nomenclature. If I use the --froce_id_ignore argument I get "m64277e_221226_194658/78906085/ccs not found in FL count file. Assign count as 0." Or if I don not supply the --force_id_ignore argument then I get "Invalid input IDs! Expected PB.X.Y or PB.X.Y|xxxxx or PBfusion.X format but saw m64277e_221226_194658/2/ccs instead. Abort!".

My question is there anyway to input a .fastq file with PB nomenclature?
