### ISSUE TITLE
Problem assert strand == '+' or strand == '-'

### ISSUE THREAD

**Issue by BeatrizdeToledo** [ConesaLab/SQANTI3#43]
Good afternoon,
I have beed trying to run sqanti using the gtf of pacbio transcripts merged with additional transcripts identified by stringtie. But is not working. 

This is the code
singularity exec -B /group/calegari_beatrizepi/combinedgtf /projects/globalscratch/sqanti3.sif sqanti3_qc.py   stringtie.all.noG20cov.mergedrename.gtf Mus_musculus.GRCm38.101.gtf Mus_musculus.GRCm38.dna.primary_assembly.fa --cage_peak mm10_fair_new_CAGE_peaks_phase1and2.bed --polyA_motif_list PolyA_motif_List_mm10.txt --gtf -fl hq.rn2.collapse_capped_trans_read.mapped_fl_count.txt -o PP_DP_N_merged -c DP_L356_twopassSJ.out.tab,DP_L223_twopassSJ.out.tab,DP_L394_twopassSJ.out.tab,N_L357_twopassSJ.out.tab,N_L224_twopassSJ.out.tab,N_L395_twopassSJ.out.tab,PP_L355_twopassSJ.out.tab,PP_L222_twopassSJ.out.tab,PP_L393_twopassSJ.out.tab --skip_report

This is the head of the stringtie gtf file
1       StringTie       transcript      3214482 3671498 .       -       .       gene_id MSTRG.1; transcript_id MSTRG.1.1; 
1       StringTie       exon    3214482 3216968 .       -       .       gene_id MSTRG.1; transcript_id MSTRG.1.1; exon_number 1; 
1       StringTie       exon    3421702 3421901 .       -       .       gene_id MSTRG.1; transcript_id MSTRG.1.1; exon_number 2; 
1       StringTie       exon    3670552 3671498 .       -       .       gene_id MSTRG.1; transcript_id MSTRG.1.1; exon_number 3; 

This is the message.
**** Performing Classification of Isoforms....
Number of classified isoforms: 49533
Traceback (most recent call last):
  File "/SQANTI3/sqanti3_qc.py", line 2267, in <module>
    main()
  File "/SQANTI3/sqanti3_qc.py", line 2260, in main
    run(args)
  File "/SQANTI3/sqanti3_qc.py", line 1713, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/SQANTI3/sqanti3_qc.py", line 424, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/cDNA_Cupcake/cupcake/io/GFF.py", line 408, in __next__
    return self.read()
  File "/cDNA_Cupcake/cupcake/io/GFF.py", line 592, in read
    rec = gmapRecord(chr, coverage=None, identity=None, strand=strand, seqid=seqid, geneid=geneid)
  File "/cDNA_Cupcake/cupcake/io/GFF.py", line 324, in __init__
    assert strand == '+' or strand == '-'
AssertionError

**Comment by Magdoll** [comment]
Hi @BeatrizdeToledo 

pretty sure it's becuz the GTF format is not conforming to the expected format. or something was off in the GTF --> genePred conversion

SQANTI3 expects Gencode style GTF
https://www.gencodegenes.org/pages/data_format.html

I think you need a "gene" record followed by a "transcript" record then a bunch of "exon" records

**Comment by BeatrizdeToledo** [comment]
the gtf file I used was previously generated by hisat2/strigtie + Pacbio data.
Apparently some of the transcripts had no strand specified, was "." instead of "+" or "-". So i just deleted the ones with "." on the strand collumn and worked
