### ISSUE TITLE
Error when running sqanti3_qc.py (possibly an error from R package?)

### ISSUE THREAD

**Issue by stanleyroche** [ConesaLab/SQANTI3#48]
I am getting an error message when I am trying to run sqanti3_qc.py. I have posted what I am seeing on my end. I am not sure where the error is coming from but it may have something to do with R?

(SQANTI3.env) [hos28@lb021login ~]$ python3 SQANTI3/sqanti3_qc.py --gtf dedup.5merge.collapsed.gff genes.gtf genome.fa
R scripting front-end version 3.6.1 (2019-07-05)
Write arguments to /home/hos28/dedup.5merge.collapsed.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /home/hos28/genome.fa....
Error corrected FASTA /home/hos28/dedup.5merge.collapsed_corrected.fasta already exists. Using it...
**** Predicting ORF sequences...
ORF file /home/hos28/dedup.5merge.collapsed_corrected.faa already exists. Using it....
**** Parsing Reference Transcriptome....
/home/hos28/refAnnotation_dedup.5merge.collapsed.genePred already exists. Using it.
**** Parsing Isoforms....
Splice Junction Coverage files not provided.
**** Performing Classification of Isoforms....
Number of classified isoforms: 1
**** RT-switching computation....
Full-length read abundance files not provided.
Isoforms expression files not provided.
**** Writing output files....
**** Generating SQANTI3 report....
Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang

Attaching package: ‘dplyr’

The following object is masked from ‘package:gridExtra’:

    combine

The following object is masked from ‘package:reshape’:

    rename

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: Biobase
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union

The following object is masked from ‘package:gridExtra’:

    combine

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: splines
Loading required package: Matrix

Attaching package: ‘Matrix’

The following object is masked from ‘package:reshape’:

    expand

Error in `$<-.data.frame`(`*tmp*`, SJ_type, value = "__SJ") : 
  replacement has 1 row, data has 0
Calls: $<- -> $<-.data.frame
Execution halted
Traceback (most recent call last):
  File "SQANTI3/sqanti3_qc.py", line 2291, in <module>
    main()
  File "SQANTI3/sqanti3_qc.py", line 2275, in main
    run(args)
  File "SQANTI3/sqanti3_qc.py", line 1894, in run
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/home/hos28/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/hos28/miniconda3/envs/SQANTI3.env/bin/Rscript /home/hos28/SQANTI3/utilities//SQANTI3_report.R /home/hos28/dedup.5merge.collapsed_classification.txt /home/hos28/dedup.5merge.collapsed_junctions.txt /home/hos28/dedup.5merge.collapsed.params.txt /home/hos28/SQANTI3/utilities/' returned non-zero exit status 1.

**Comment by Magdoll** [comment]
Check the files
```
wc -l /home/hos28/dedup.5merge.collapsed_classification.txt 
wc -l /home/hos28/dedup.5merge.collapsed_junctions.txt 
```
Are they largely empty?

**Comment by stanleyroche** [comment]
Yes, the classification.txt only has one entry and collapsed_junctions has nothing

**Comment by Magdoll** [comment]
Hi @stanleyroche  in that case it's not about R errors. It's because the actual SQANTI3 classification produced no results.
YOu may want to verify that your input and genome annotation are in the right format.

Also, I noticed the lines

```
dedup.5merge.collapsed_corrected.fasta already exists.
```

You appear to have run this before which can result in re-using old files that cause errors.
Please run SQANTI3 in a new, clean directory.

-Liz

**Comment by stanleyroche** [comment]
I see, you are right, after removing the files from a previous run, the script works. I tried to filter the artifacts but then another error appeared:

R scripting front-end version 3.6.1 (2019-07-05)

Running SQANTI3 filtering...

3109 isoforms read from /home/hos28/test/dedup.5merge.collapsed_classification.txt. 73 to be kept.
Output written to: /home/hos28/test/dedup.5merge.collapsed_classification.filtered_lite.fasta
Output written to: /home/hos28/test/dedup.5merge.collapsed_classification.filtered_lite_classification.txt
Output written to: /home/hos28/test/dedup.5merge.collapsed_classification.filtered_lite_junctions.txt
Output written to: /home/hos28/test/dedup.5merge.collapsed_classification.filtered_lite.gtf
**** Generating SQANTI3 report....
Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang

Attaching package: ‘dplyr’

The following object is masked from ‘package:gridExtra’:

    combine

The following object is masked from ‘package:reshape’:

    rename

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: Biobase
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union

The following object is masked from ‘package:gridExtra’:

    combine

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: splines
Loading required package: Matrix

Attaching package: ‘Matrix’

The following object is masked from ‘package:reshape’:

    expand

Error in cut.default(isoPerGene$nIso, breaks = c(0, 1, 3, 5, max(isoPerGene$nIso) +  : 
  'breaks' are not unique
Calls: cut -> cut.default
Execution halted
Traceback (most recent call last):
  File "/home/hos28/SQANTI3/sqanti3_RulesFilter.py", line 222, in <module>
    main()
  File "/home/hos28/SQANTI3/sqanti3_RulesFilter.py", line 217, in main
    sqanti_filter_lite(args)
  File "/home/hos28/SQANTI3/sqanti3_RulesFilter.py", line 162, in sqanti_filter_lite
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/home/hos28/.pyenv/versions/3.7.2/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/hos28/miniconda3/envs/SQANTI3.env/bin/Rscript /home/hos28/SQANTI3/utilities//SQANTI3_report.R /home/hos28/test/dedup.5merge.collapsed_classification.filtered_lite_classification.txt /home/hos28/test/dedup.5merge.collapsed_classification.filtered_lite_junctions.txt mock /home/hos28/SQANTI3/utilities/' returned non-zero exit status 1.

**Comment by FJPardoPalacios** [comment]
Hi @stanleyroche ,

I think that you found a bug on our SQANTI3_report.R script. I think it is failing because of this line:

```
cut.default(isoPerGene$nIso, breaks = c(0, 1, 3, 5, max(isoPerGene$nIso) +
```

In your filtered transcriptome it seems that the maximum number of isoforms per gene is 5 (or 1 or 3). I assume that this error didn't happen when running sqanti3_qc.py and the report was created, but after filtering the maximum number of isoforms per gene changed to 5 (or 1 or 3) and it breaked the code. Sorry for the inconvenient bug.

I will try to fix the bug on the SQANTI3_report.R script and I'll let you know when it's ready

**Comment by stanleyroche** [comment]
Ok I see, thank you, and yes please let me know when the bug is fixed.

**Comment by stanleyroche** [comment]
Hello. Is there an update on this potential bug?

**Comment by aarzalluz** [comment]
Apologies for not updating the issue -this bug has loon been fixed. Please update to the last version of SQANTI3.
