### ISSUE TITLE
No CDS entries in output GTF

### ISSUE THREAD

**Issue by DidrikOlofsson** [ConesaLab/SQANTI3#58]
Hi and thanks for a very useful tool!

I have a pipeline that runs sqanti3_qc.py and sqanti3_RulesFilter.py which works and gives no errors. However, the file `*_corrected.gtf.cds.gff` that is in the example_out folder is not being generated. The file `*_classification.txt` contains information about CDS start/stop/etc so the ORF prediction step seems to be working, the information is just not transferred to an output GTF. I am running the following commands:
````
sqanti3_qc.py \
        --gtf \
        $lrAnnotation \
        $refAnnotation \
        $genome \
        --polyA_motif_list $motifs \
        --expression $counts \
        -c '*.SJ.out.tab' \
        -t 16 \
        -n 4 \
        --isoAnnotLite

sqanti3_RulesFilter.py \
        $classification \
        $fasta \
        $gtf
````

I am running sqanti3 via the docker container provided in one of the repository issues here. The sqanti3 version 2.0.0. Not sure if this is an issue with the software or if I'm doing something wrong. Thanks in advance!

**Comment by Magdoll** [comment]
Hi @DidrikOlofsson  can you check that after you ran `sqanti_qc3.py` that a `_corrected.faa` file was generated?

**Comment by DidrikOlofsson** [comment]
Hi @Magdoll,  the `_corrected.faa` was created without errors.

**Comment by Magdoll** [comment]
Hi @DidrikOlofsson  did you check the "_corrected.gtf" file to see if it contains CDS information?
-Liz

**Comment by Magdoll** [comment]
Close unless OP reopens.
