### ISSUE TITLE
adding whether novel transcript has an annotated TTS

### ISSUE THREAD

**Issue by jackhump** [ConesaLab/SQANTI3#59]
Hi all,

I love SQANTI, thanks for all your hard work. I'm working on filtering out some novel transcripts as I'm observing a lot of potential intrapriming transcripts.  
One thing I've noticed is that just filtering on A-richness in the downstream 20bp flags a number of FSM transcripts.  I want to keep all these FSMs but I don't want to then remove novel transcripts that use the same "annotated" TTS.

Therefore what I'd like to do is for SQANTI to check whether a novel transcript shares a TTS (transcript end site) with a known transcript for that gene, using the provided (GENCODE etc) annotation.  

Do you think this would be possible to implement?

best wishes,

Jack

**Comment by FJPardoPalacios** [comment]
Hi Jack!

I think that it may help you the column `diff_to_gene_TTS` column of the classification file, which is already implemented. This is its description:
- `diff_to_gene_TTS`: distance of query isoform 3' end to the closest end of any transcript of the matching gene. Negative value means query ends upstream of reference.

That means that any of your NIC and NNC isoforms with a TTS shared with an already known transcript of the same gene should have a `diff_to_gene_TTS` of 0 or close to it (remember that transcription ending can be a bit fuzzy)

Best,

Fran

**Comment by jackhump** [comment]
damn, of course I missed it, apologies!
