### ISSUE TITLE
tappas annotation gff3 only in 'splits' folder

### ISSUE THREAD

**Issue by rsalz** [ConesaLab/SQANTI3#6]
The tappas_annot_from_sqanti3.gff3 files were present in the intermediary 'splits' file, but once the program is complete, they are nowhere to be found. Could it be that they just got deleted with the splits file after the program completes? Or is there something else going wrong?

**Comment by FJPardoPalacios** [comment]
You're right, that was a bug that occurred when --gff3 option wasn't used. 

Now it's fixed, thank you!

**Comment by rsalz** [comment]
> You're right, that was a bug that occurred when --gff3 option wasn't used.
> 
> Now it's fixed, thank you!

Sorry to bring this up again, but it's not fixed. I was using the --gff3 option the whole time. My 'final result' was published to splits/0/x.tappas_annot_from_sqanti3.gff3, which gets deleted after the program finishes.

**Comment by FJPardoPalacios** [comment]
I'm sorry for that, I didn't realize that you were using -n option and that was the reason isoAnnot was not working.

I believe that I have fixed the bug, please download the updated sqanti3_qc.py script and give it a try. 

I'm reopening the issue. If everything works properly, let me know and I will re-close it.

**Comment by rsalz** [comment]
So I pulled the repository and tried again with the exact same files/command.

With '-n' option (like before): Now it doesn't generate the tappas_annot_from_sqanti3.gff3 at all. Additionally, I get the error with all my isoforms that the fl counts are not found in the provided fasta.

Without '-n' option, otherwise same command: i get no errors but the tappas_annot_from_sqanti3.gff3 does not get generated.

**Comment by rsalz** [comment]
> So I pulled the repository and tried again with the exact same files/command.
> 
> With '-n' option (like before): Now it doesn't generate the tappas_annot_from_sqanti3.gff3 at all. Additionally, I get the error with all my isoforms that the fl counts are not found in the provided fasta.
> 
> Without '-n' option, otherwise same command: i get no errors but the tappas_annot_from_sqanti3.gff3 does not get generated.

Update- it actually appears to be working (i'm running without -n). The gff3 is produced after the sqanti_report.
