### ISSUE TITLE
CDS annotation in gff output

### ISSUE THREAD

**Issue by morellr** [ConesaLab/SQANTI3#64]
Hi,
The CDS annotation in the *.collapsed_corrected.gtf.cds.gff file (output of sqanti3_qc.py) has an error. The last CDS of each novel isoform always includes the translation termination codon. In standard reference gtf files (e.g. GENCODE) the CDS ends with the last base of the last coding codon and does not include the translation termination codon (i.e. the last CDS is always 3 bp too long in the sqanti3_qc.py output). This inconsistency makes it cumbersome to globally compare the CDS annotations of novel isoforms with reference isoforms:   every isoform has at least one novel CDS exon; the last one.

**Comment by morellr** [comment]
I should clarify a little. In the GENCODE gtf files the termination codon is listed as a separate feature, and the coordinates are not included in any CDS feature. I tried fixing this by adding the "-impliedStopAfterCds" parameter in the call to gtfToGenePred, but it did not change the resulting gff file. Thanks in advance.

**Comment by Magdoll** [comment]
Thanks...I'll put this on a to-fix note.

**Comment by aarzalluz** [comment]
Closing as working on this is not planned ATM -will reopen if major problems stemming from this issue are reported.
