### ISSUE TITLE
SQANTI3 Saturation curves reads over-sampling ?

### ISSUE THREAD

**Issue by uqktiwar** [ConesaLab/SQANTI3#69]
Hi,

I am a little confused about the saturation curves produced by SQANTI3. 
The total number of FLNC reads I started with were 4,098,069. However, in the saturation curves produced, the x-axis ranges from 0 - 6 M reads - does this mean that the reads are both under- and over-sampled or is something going wrong during the execution?

Thank you,
Kanu

**Comment by FJPardoPalacios** [comment]
Hi Kanu,

You're not doing nothing wrong. Reads are both under- and over-sampled, so based on the behaviour observed, SQANTI3 plots the expected results of a deeper sequencing.

Bests,
Fran

**Comment by uqktiwar** [comment]
Thanks :)
