### ISSUE TITLE
filter problem

### ISSUE THREAD

**Issue by BeatrizdeToledo** [ConesaLab/SQANTI3#7]
Good morning,
After completely running sqanti qc I decided to run sqanti3_RulesFilter.py

However I had a problem when running it. (we  used a container with up-to-date linux system and all the tools bundled together)

singularity exec -B /group/calegari_beatrizepi/SQANTI3 /projects/globalscratch/sqanti3.sif sqanti3_RulesFilter.py gmap1_cup_PP_sqanti_classification.txt gmap1_cup_PP_sqanti_corrected.fasta gmap1_cup_PP_sqanti_corrected.gtf
/SQANTI3/sqanti3_RulesFilter.py: 1: __author__: not found
/SQANTI3/sqanti3_RulesFilter.py: 2: __version__: not found
/SQANTI3/sqanti3_RulesFilter.py: 11: 
Lightweight filtering of SQANTI by using .classification.txt output

Only keep Iso-Seq isoforms if:
The isoform is FSM, ISM, or NIC and (does not have intrapriming or has polyA_motif)
The isoform is NNC, does not have intrapriming/or polyA motif, not RT-switching, and all junctions are either all canonical or short-read-supported
The isoform is antisense, intergenic, genic, does not have intrapriming/or polyA motif, not RT-switching, and all junctions are either all canonical or short-read-supported
: not found
/SQANTI3/sqanti3_RulesFilter.py: 13: import: not found
/SQANTI3/sqanti3_RulesFilter.py: 14: import: not found
/SQANTI3/sqanti3_RulesFilter.py: 15: from: not found
/SQANTI3/sqanti3_RulesFilter.py: 16: from: not found
/SQANTI3/sqanti3_RulesFilter.py: 17: from: not found
/SQANTI3/sqanti3_RulesFilter.py: 18: from: not found
/SQANTI3/sqanti3_RulesFilter.py: 20: Syntax error: "(" unexpected

**Comment by mestia** [comment]
It seems that the script `sqanti3_RulesFilter.py` doesn't have python shebang and is run as a bash script...
