### ISSUE TITLE
Errors on output

### ISSUE THREAD

**Issue by ricyoung** [ConesaLab/SQANTI3#72]
can someone help me with the following errors please.

Thank you 
-

**** Parsing Isoforms....
Splice Junction Coverage files not provided.
**** Performing Classification of Isoforms....
Number of classified isoforms: 390238
**** RT-switching computation....
Full-length read abundance files not provided.
Isoforms expression files not provided.
**** Writing output files....
**** Generating SQANTI3 report....

Attaching package: ‘dplyr’

The following object is masked from ‘package:gridExtra’:

    combine

The following object is masked from ‘package:reshape’:

    rename

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: Biobase
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union

The following object is masked from ‘package:gridExtra’:

    combine

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: splines
Loading required package: Matrix

Attaching package: ‘Matrix’

The following object is masked from ‘package:reshape’:

    expand

Error in `$<-.data.frame`(`*tmp*`, SJ_type, value = "__SJ") : 
  replacement has 1 row, data has 0
Calls: $<- -> $<-.data.frame
Execution halted
Traceback (most recent call last):
  File "sqanti3_qc.py", line 2408, in <module>
    main()
  File "sqanti3_qc.py", line 2392, in main
    run(args)
  File "sqanti3_qc.py", line 2006, in run
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/home/ric/miniconda3/envs/SQANTI3.env/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/ric/miniconda3/envs/SQANTI3.env/bin/Rscript /home/ric/SQANTI3/utilities/SQANTI3_report.R /home/ric/SQANTI3/0627_isoform_collapse.collapsed_classification.txt

**Comment by FJPardoPalacios** [comment]
Hi!

It seems that SQANTI3 failed creating the report, so the classification and junctions files should be there. Would it be possible to have a look to the first 10 lines of those 2 files?

Thank you in advance,
Fran

**Comment by ricyoung** [comment]
Yes. I can also email if that is easier.

Classification txt
--
(SQANTI3.env) [ric@Sleipnir SQANTI3]$ head -n 10 0627_isoform_collapse.collapsed_classification.txt
isoform	chrom	strand	length	exons	structural_category	associated_gene	associated_transcript	ref_length	ref_exons	diff_to_TSS	diff_to_TTS	diff_to_gene_TSS	diff_to_gene_TTS	subcategory	RTS_stage	all_canonical	min_sample_cov	min_cov	min_cov_pos	sd_cov	FL	n_indels	n_indels_junc	bite	iso_exp	gene_exp	ratio_exp	FSM_class	coding	ORF_length	CDS_length	CDS_start	CDS_end	CDS_genomic_start	CDS_genomic_end	predicted_NMD	perc_A_downstream_TTS	seq_A_downstream_TTS	dist_to_cage_peak	within_cage_peak	dist_to_polya_site	within_polya_site	polyA_motifpolyA_dist	ORF_seq
PB.1.1	NC_000067.7	+	4208	2	intergenic	novelGene_21	novel	NA	NA	NA	NA	NA	NA	multi-exon	FALSE	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	A	non_coding	NA	NA	NA	NA	NA	NA	NA	50.0	AAAACCCATCAAAATACCCT	NA	NA	NA	NA	NA	NA	NA
PB.10.1	NC_000067.7	-	2997	1	intergenic	novelGene_37	novel	NA	NA	NA	NA	NA	NA	mono-exon	FALSE	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	A	non_coding	NA	NA	NA	NA	NA	NA	NA	80.0	AAAATGGAAAAAAGAAAAAA	NA	NA	NA	NA	NA	NA	NA
PB.10.2	NC_000067.7	-	652	1	intergenic	novelGene_38	novel	NA	NA	NA	NA	NA	NA	mono-exon	FALSE	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	A	non_coding	NA	NA	NA	NA	NA	NA	NA	70.0	AAACAAAACAGAACTATAAA	NA	NA	NA	NA	NA	NA	NA
PB.100.1	NC_000067.7	+	4815	22	intergenic	novelGene_951	novel	NA	NA	NA	NA	NA	NA	multi-exon	FALSE	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	A	coding	8702613	668	3280	12856751	12929066	FALSE	10.0	TCTCTCTGTGCTTGCTAGAT	NA	NA	NA	NA	NA	NA	MKYSLWALLLAVLGTQLLGSLCSTVRSQRFRGRIQQERKNIRPNIILVLTDDQDVELGSLQVMNKTRKIMEQGGATFTNAFVTTPMCCPSRSSMLTGKYVHNHNVYTNNENCSSPSWQAMHEPRTFAVYLNNTGYRTAFFGKYLNEYNGSYIPPGWREWLGLIKNSRFYNYTVCRNGIKEKHGFDYAKDYFTDLITNESINYFKMSKRMYPHRPIMMVISHAAPHGPEDSAPQFSKLYPNASQHITPSYNYAPNMDKHWIMQYTGPMLPIHMEFTNVLQRKRLQTLMSVDDSVERLYNMLVESGELDNTYIIYTADHGYHIGQFGLVKGKSMPYDFDIRVPFFIRGPSIEPGSIVPQIVLNIDLAPTILDIAGLDSPSDVDGKSVLKLLDLEKPGNRFRTNKKAKIWRDTFLVERGKFLRKKEESGKNIQQSNHLPKYERVKELCQQARYQTACEQPGQNWQCIEDTSGKLRIHKCKGPSDLLTVRQNARNLYSRGLHDKDKECHCRDSGYRSSRSQRKNQRQFLRNKGTPKYKPRFVHTRQTRSLSVEFEGEIYDINLEEEELQVLPPRSIAKRHDEGHQGFIGHQAAAGDIRNEMLADSNNAVGLPATVRVTHKCFILPNDTIHCERELYQSARAWKDHKAYIDKEIEVLQDKIKNLREVRGHLKKRKPEECGCGDQSYYNKEKGVKRQEKLKSHLHPFKEAAAQEVDSKLQLFKEHRRRKKERKEKKRQRKGEECSLPGLTCFTHDNNHWQTAPFWNLGSFCACTSSNNNTYWCLRTVNETHNFLFCEFATGFLEYFDMNTDPYQLTNTVHTVERSILNQLHIQLMELRSCQGYKQCNPRPKSLDIGAKEGGNYDPHRGQLWDGWEG
PB.100.10	NC_000067.7	+	5270	21	intergenic	novelGene_960	novel	NA	NA	NA	NA	NA	NA	multi-exon	FALSE	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	A	coding	1093276	432	3707	12856751	12929853	FALSE	35.0	TACTCGTTTCAGAGAAATGA	NA	NA	NA	NA	NA	NA	MKYSLWALLLAVLGTQLLGSLCSTVRSQRFRGRIQQERKNIRPNIILVLTDDQDVELGSLQVMNKTRKIMEQGGATFTNAFVTTPMCCPSRSSMLTGKYVHNHNVYTNNENCSSPSWQAMHEPRTFAVYLNNTGYRTAFFGKYLNEYNGSYIPPGWREWLGLIKNSRFYNYTVCRNGIKEKHGFDYAKDYFTDLITNESINYFKMSKRMYPHRPIMMVISHAAPHGPEDSAPQFSKLYPNASQHITPSYNYAPNMDKHWIMQYTGPMLPIHMEFTNVLQRKRLQTLMSVDDSVERLYNMLVESGELDNTYIIYTADHGYHIGQFGLVKGKSMPYDFDIRVPFFIRGPSIEPGSIVPQIVLNIDLAPTILDIAGLDSPSDVDGKSVLKLLDLEKPGNRFRTNKKAKIWRDTFLVERGKFLRKKEESGKNIQQSNHLPKYERVKELCQQARYQTACEQPGQNWQCIEDTSGKLRIHKCKGPSDLLTVRQNARNLYSRGLHDKDKECHCRDSGYRSSRSQRKNQRQFLRNKGTPKYKPRFVHTRQTRSLSVEFEGEIYDINLEEEELQVLPPRSIAKRHDEGHQGFIGHQAAAGDIRNEMLADSNNAVGLPATVRVTHKCFILPNDTIHCERELYQSARAWKDHKAYIDKEIEVLQDKIKNLREVRGHLKKRKPEECGCGDQSYYNKEKGVKRQEKLKSHLHPFKEAAAQEVDSKLQLFKEHRRRKKERKEKKRQRKGEECSLPGLTCFTHDNNHWQTAPFWNLGSFCACTSSNNNTYWCLRTVNETHNFLFCEFATGFLEYFDMNTDPYQELKKEETMTRTEDSYGMDGKVSQSNITSDTSWQGLEELSGASNIDEYRSNPRLSLEDWTNYLRAVYRAFALLNSHPDPNKANGTPTTQGGDFLVTSAERLVPAEMASAESGEDPSHVVGETPPLTLPVNLQTLHLNRPTLSPERKLEWDNDIPEVNHLNSEHWRKTEKQIGWEELHHPEGDVVSGNGMTELLPQSHLGHQLTSQHQQKCSQDVETEKDAFEDQLRPLVHSDRTPVHRVFDVSRVEQPLHSSHTERMLAKMGQSDTKEWLPNLEGSASAPVISA
PB.100.11	NC_000067.7	+	4603	23	intergenic	novelGene_961	novel	NA	NA	NA	NA	NA	NA	multi-exon	FALSE	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	A	coding	8702613	481	3093	12856751	12929066	FALSE	65.0	AATAAATAAAGCAAGAATGA	NA	NA	NA	NA	NA	NA	MKYSLWALLLAVLGTQLLGSLCSTVRSQRFRGRIQQERKNIRPNIILVLTDDQDVELGSLQVMNKTRKIMEQGGATFTNAFVTTPMCCPSRSSMLTGKYVHNHNVYTNNENCSSPSWQAMHEPRTFAVYLNNTGYRTAFFGKYLNEYNGSYIPPGWREWLGLIKNSRFYNYTVCRNGIKEKHGFDYAKDYFTDLITNESINYFKMSKRMYPHRPIMMVISHAAPHGPEDSAPQFSKLYPNASQHITPSYNYAPNMDKHWIMQYTGPMLPIHMEFTNVLQRKRLQTLMSVDDSVERLYNMLVESGELDNTYIIYTADHGYHIGQFGLVKGKSMPYDFDIRVPFFIRGPSIEPGSIVPQIVLNIDLAPTILDIAGLDSPSDVDGKSVLKLLDLEKPGNRFRTNKKAKIWRDTFLVERGKFLRKKEESGKNIQQSNHLPKYERVKELCQQARYQTACEQPGQNWQCIEDTSGKLRIHKCKGPSDLLTVRQNARNLYSRGLHDKDKECHCRDSGYRSSRSQRKNQRQFLRNKGTPKYKPRFVHTRQTRSLSVEFEGEIYDINLEEEELQVLPPRSIAKRHDEGHQGFIGHQAAAGDIRNEMLADSNNAVGLPATVRVTHKCFILPNDTIHCERELYQSARAWKDHKAYIDKEIEVLQDKIKNLREVRGHLKKRKPEECGCGDQSYYNKEKGVKRQEKLKSHLHPFKEAAAQEVDSKLQLFKEHRRRKKERKEKKRQRKGEECSLPGLTCFTHDNNHWQTAPFWNLGSFCACTSSNNNTYWCLRTVNETHNFLFCEFATGFLEYFDMNTDPYQLTNTVHTVERSILNQLHIQLMELRSCQGYKQCNPRPKSLDIGAKEGGNYDPHRGQLWDGWEG
PB.100.12	NC_000067.7	+	4405	21	intergenic	novelGene_962	novel	NA	NA	NA	NA	NA	NA	multi-exon	FALSE	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	A	coding	1093276	381	3656	12856751	12929853	FALSE	15.0	CTCTCTGTGCTTGCTAGATA	NA	NA	NA	NA	NA	NA	MKYSLWALLLAVLGTQLLGSLCSTVRSQRFRGRIQQERKNIRPNIILVLTDDQDVELGSLQVMNKTRKIMEQGGATFTNAFVTTPMCCPSRSSMLTGKYVHNHNVYTNNENCSSPSWQAMHEPRTFAVYLNNTGYRTAFFGKYLNEYNGSYIPPGWREWLGLIKNSRFYNYTVCRNGIKEKHGFDYAKDYFTDLITNESINYFKMSKRMYPHRPIMMVISHAAPHGPEDSAPQFSKLYPNASQHITPSYNYAPNMDKHWIMQYTGPMLPIHMEFTNVLQRKRLQTLMSVDDSVERLYNMLVESGELDNTYIIYTADHGYHIGQFGLVKGKSMPYDFDIRVPFFIRGPSIEPGSIVPQIVLNIDLAPTILDIAGLDSPSDVDGKSVLKLLDLEKPGNRFRTNKKAKIWRDTFLVERGKFLRKKEESGKNIQQSNHLPKYERVKELCQQARYQTACEQPGQNWQCIEDTSGKLRIHKCKGPSDLLTVRQNARNLYSRGLHDKDKECHCRDSGYRSSRSQRKNQRQFLRNKGTPKYKPRFVHTRQTRSLSVEFEGEIYDINLEEEELQVLPPRSIAKRHDEGHQGFIGHQAAAGDIRNEMLADSNNAVGLPATVRVTHKCFILPNDTIHCERELYQSARAWKDHKAYIDKEIEVLQDKIKNLREVRGHLKKRKPEECGCGDQSYYNKEKGVKRQEKLKSHLHPFKEAAAQEVDSKLQLFKEHRRRKKERKEKKRQRKGEECSLPGLTCFTHDNNHWQTAPFWNLGSFCACTSSNNNTYWCLRTVNETHNFLFCEFATGFLEYFDMNTDPYQELKKEETMTRTEDSYGMDGKVSQSNITSDTSWQGLEELSGASNIDEYRSNPRLSLEDWTNYLRAVYRAFALLNSHPDPNKANGTPTTQGGDFLVTSAERLVPAEMASAESGEDPSHVVGETPPLTLPVNLQTLHLNRPTLSPERKLEWDNDIPEVNHLNSEHWRKTEKQIGWEELHHPEGDVVSGNGMTELLPQSHLGHQLTSQHQQKCSQDVETEKDAFEDQLRPLVHSDRTPVHRVFDVSRVEQPLHSSHTERMLAKMGQSDTKEWLPNLEGSASAPVISA
PB.100.13	NC_000067.7	+	5229	22	intergenic	novelGene_963	novel	NA	NA	NA	NA	NA	NA	multi-exon	FALSE	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	A	coding	6161851	1029	2879	12887590	12929066	FALSE	35.0	TACTCGTTTCAGAGAAATGA	NA	NA	NA	NA	NA	NA	MDKHWIMQYTGPMLPIHMEFTNVLQRKRLQTLMSVDDSVERLYNMLVESGELDNTYIIYTADHGYHIGQFGLVKGKSMPYDFDIRVPFFIRGPSIEPGSIVPQIVLNIDLAPTILDIAGLDSPSDVDGKSVLKLLDLEKPGNRFRTNKKAKIWRDTFLVERGKFLRKKEESGKNIQQSNHLPKYERVKELCQQARYQTACEQPGQNWQCIEDTSGKLRIHKCKGPSDLLTVRQNARNLYSRGLHDKDKECHCRDSGYRSSRSQRKNQRQFLRNKGTPKYKPRFVHTRQTRSLSVEFEGEIYDINLEEEELQVLPPRSIAKRHDEGHQGFIGHQAAAGDIRNEMLADSNNAVGLPATVRVTHKCFILPNDTIHCERELYQSARAWKDHKAYIDKEIEVLQDKIKNLREVRGHLKKRKPEECGCGDQSYYNKEKGVKRQEKLKSHLHPFKEAAAQEVDSKLQLFKEHRRRKKERKEKKRQRKGEECSLPGLTCFTHDNNHWQTAPFWNLGSFCACTSSNNNTYWCLRTVNETHNFLFCEFATGFLEYFDMNTDPYQLTNTVHTVERSILNQLHIQLMELRSCQGYKQCNPRPKSLDIGAKEGGNYDPHRGQLWDGWEG
PB.100.14	NC_000067.7	+	4821	22	intergenic	novelGene_964	novel	NA	NA	NA	NA	NA	NA	multi-exon	FALSE	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	NA	A	coding	8702613	674	3286	12856751	12929066	FALSE	10.0	TCTCTCTGTGCTTGCTAGAT	NA	NA	NA	NA	NA	NA	MKYSLWALLLAVLGTQLLGSLCSTVRSQRFRGRIQQERKNIRPNIILVLTDDQDVELGSLQVMNKTRKIMEQGGATFTNAFVTTPMCCPSRSSMLTGKYVHNHNVYTNNENCSSPSWQAMHEPRTFAVYLNNTGYRTAFFGKYLNEYNGSYIPPGWREWLGLIKNSRFYNYTVCRNGIKEKHGFDYAKDYFTDLITNESINYFKMSKRMYPHRPIMMVISHAAPHGPEDSAPQFSKLYPNASQHITPSYNYAPNMDKHWIMQYTGPMLPIHMEFTNVLQRKRLQTLMSVDDSVERLYNMLVESGELDNTYIIYTADHGYHIGQFGLVKGKSMPYDFDIRVPFFIRGPSIEPGSIVPQIVLNIDLAPTILDIAGLDSPSDVDGKSVLKLLDLEKPGNRFRTNKKAKIWRDTFLVERGKFLRKKEESGKNIQQSNHLPKYERVKELCQQARYQTACEQPGQNWQCIEDTSGKLRIHKCKGPSDLLTVRQNARNLYSRGLHDKDKECHCRDSGYRSSRSQRKNQRQFLRNKGTPKYKPRFVHTRQTRSLSVEFEGEIYDINLEEEELQVLPPRSIAKRHDEGHQGFIGHQAAAGDIRNEMLADSNNAVGLPATVRVTHKCFILPNDTIHCERELYQSARAWKDHKAYIDKEIEVLQDKIKNLREVRGHLKKRKPEECGCGDQSYYNKEKGVKRQEKLKSHLHPFKEAAAQEVDSKLQLFKEHRRRKKERKEKKRQRKGEECSLPGLTCFTHDNNHWQTAPFWNLGSFCACTSSNNNTYWCLRTVNETHNFLFCEFATGFLEYFDMNTDPYQLTNTVHTVERSILNQLHIQLMELRSCQGYKQCNPRPKSLDIGAKEGGNYDPHRGQLWDGWEG

**Comment by ricyoung** [comment]
junctions ( looks like it is missing stuff)
-
(SQANTI3.env) [ric@Sleipnir SQANTI3]$ head -n 10 0627_isoform_collapse.collapsed_junctions.txt
isoform	chrom	strand	junction_number	genomic_start_coord	genomic_end_coord	transcript_coord	junction_category	start_site_category	end_site_category	diff_to_Ref_start_site	diff_to_Ref_end_site	bite_junction	splice_site	canonical	RTS_junction	indel_near_junct	phyloP_start	phyloP_end	sample_with_cov	total_coverage_unique	total_coverage_multi

**Comment by ricyoung** [comment]
also just in case the parm
-
head  0627_isoform_collapse.collapsed.params.txt 
Version	3.3
Input	0627_isoform_collapse.collapsed.gff
Annotation	gencode.vM27.annotation.gtf
Genome	GCF_000001635.27_GRCm39_genomic.fna
Aligner	minimap2
FLCount	NA
Expression	NA
Junction	NA
CagePeak	NA
PolyA	NA

**Comment by FJPardoPalacios** [comment]
It's weird that the junctions file is empty and at the same time you have some isoforms labeled as "multi-exon". I realized that you are running version 3.3, would it be possible to update SQANTI3 scripts with the current version and try again?

Bests,
Fran

**Comment by FJPardoPalacios** [comment]
Okey, maybe I have a clue about what is going on. Could you check if your isoforms map to chromosomes without nothing annotated on the reference? 
For example, do you have any entry on your reference GTF related to the NC_000067.7 chromosome? And I mean with that exact chromosome ID, not "chr1".

Bests,
Fran

**Comment by ricyoung** [comment]
can you explain - I am sorry ( generally what file should I grep to look at for the NC_000067.7) - I am not sure what your asking - I am going to try to update this to the new version tomorrow.

I got the files from a isoseq run -> processed via smrtlink -> then cupcake.

I am using an annotation file from gencode -> https://www.gencodegenes.org/mouse

**Comment by FJPardoPalacios** [comment]
I was asking if you have any gene or transcript annotated in your reference GTF (the one from Gencode) mapping to the NC_000067.7 chromosome. If I'm right, you don't have any. That chromosome doesn't exist for Gencode.

Gencode annotation uses the nomenclature chr1, chr2, chr3... meanwhile your reference genome is coming probably from RefSeq. RefSeq uses a different way of calling the chromosomes: NC_000067.7 is chromosome 1, NC_000068.8 is chromosome 2 and so on. Check here the entire list: https://www.ncbi.nlm.nih.gov/genome/?term=txid10090

SQANTI3 cannot do that relationship between RefSeq IDs and Gencode IDs. If you are using as reference genome the one from RefSeq, you should use a reference annotation file coming also from RefSeq, not from Gencode.

Bests,
Fran

**Comment by ricyoung** [comment]
Fran,

thank you for noticing and the different names - - FIXED - that is a great catch - again thank you. 
I am still having issues.

tomorrow I will update to the newest version and see if I continue to have issues.

-
scripting front-end version 3.6.3 (2020-02-29)
Write arguments to /home/ric/SQANTI3/0713_testrun.params.txt...
**** Running SQANTI3...
**** Parsing provided files....
Reading genome fasta /home/ric/SQANTI3/ry_ref/ncbi-genomes-2021-06-13/GCF_000001635.27_GRCm39_genomic.fna....
Skipping aligning of sequences because GTF file was provided.

Indels will be not calculated since you ran SQANTI3 without alignment step (SQANTI3 with gtf format as transcriptome input).
**** Predicting ORF sequences...
**** Parsing Reference Transcriptome....
**** Parsing Isoforms....
Splice Junction Coverage files not provided.
**** Performing Classification of Isoforms....
Number of classified isoforms: 390238
**** RT-switching computation....
Full-length read abundance files not provided.
Isoforms expression files not provided.
**** Writing output files....
**** Generating SQANTI3 report....

Attaching package: ‘dplyr’

The following object is masked from ‘package:gridExtra’:

    combine

The following object is masked from ‘package:reshape’:

    rename

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Loading required package: Biobase
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union

The following object is masked from ‘package:gridExtra’:

    combine

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: splines
Loading required package: Matrix

Attaching package: ‘Matrix’

The following object is masked from ‘package:reshape’:
   intersect, setdiff, setequal, union

Loading required package: Biobase
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following objects are masked from ‘package:dplyr’:

    combine, intersect, setdiff, union

The following object is masked from ‘package:gridExtra’:

    combine

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which, which.max, which.min

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: splines
Loading required package: Matrix

Attaching package: ‘Matrix’

The following object is masked from ‘package:reshape’:

    expand

Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
Warning messages:
1: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
2: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
`summarise()` has grouped output by 'lenCat'. You can override using the `.groups` argument.
Warning messages:
1: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
2: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead. 
`summarise()` has grouped output by 'structural_category'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'structural_category'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'structural_category'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'associated_transcript'. You can override using the `.groups` argument.
`summarise()` has grouped output by 'associated_transcript'. You can override using the `.groups` argument.
Warning messages:
1: Using alpha for a discrete variable is not advised. 
2: Using alpha for a discrete variable is not advised. 
3: Using alpha for a discrete variable is not advised. 
4: Using alpha for a discrete variable is not advised. 
null device 
          1 
[1] "SQANTI3 report successfully generated!"
Removing temporary files....
SQANTI3 complete in 3521.00244287285 sec.

**Comment by FJPardoPalacios** [comment]
Don't worry about the Warnings (that's my fault, we have to clean them). Everything seems to run properly and you should have generated a report.

Fran

**Comment by ricyoung** [comment]
Ok.. let me upgrade and review everything this morning

**Comment by ricyoung** [comment]
thank you - everything is working.
