### ISSUE TITLE
Reading CAGE Peak data: ERROR

### ISSUE THREAD

**Issue by HeyLifeHD** [ConesaLab/SQANTI3#75]
Dear SQANTI authors,

I had an error during the integration of custom CAGE peaks.
`
**** Reading CAGE Peak data.
Traceback (most recent call last):
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 2486, in <module>
    main()
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 2470, in main
    run(args)
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 1881, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 1566, in isoformClassification
    cage_peak_obj = CAGEPeak(args.cage_peak)
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 2149, in __init__
    self.read_bed()
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 2157, in read_bed
    strand = raw[5]
`
I prepared the input as described in your wiki (column 1 is chromosome (chr1, chr2...); column 2 is 0-based start coordinate; column 3 is 1-based end coordinate; column 5 is strand information). Here the first few lines:
chr1 11868 11874 . +
chr1 12009 12010 . +
chr1 29553 29554 . +
chr1 30266 30267 . +
chr1 30365 30366 . +
chr1 52472 52473 . +
chr1 53048 53049 . +
chr1 62947 62948 . +
chr1 69090 69091 . +
chr1 131024 131025 . +

Would highly appreciate your input. 

Thank you and best regards,

Joschka

**Comment by FJPardoPalacios** [comment]
Hi Joshcka,

I'm sorry, it's a mistake in the wiki that I'll amend right away. the columns should be:
- Column 1 is chromosome (chr1, chr2...)
- Column 2 is 0-based start coordinate
- Column 3 is 1-based end coordinate
- Column 6 is strand information 
- Column 7 is the middle point between the start and end coordinate. It must be an integer and it will serve to calculate the distance to the closest CAGE peak

Bests,
Fran

**Comment by HeyLifeHD** [comment]
Thanks a lot for the quick response! Will try to run it as soon as possible. 

Best,

Joschka
