### ISSUE TITLE
Error during "Running calculation of TSS ratio"

### ISSUE THREAD

**Issue by HeyLifeHD** [ConesaLab/SQANTI3#76]
Dear SQUANTI authors,

I have sadly faced another error upon running your pipeline with my actual dataset. It was working smoothly until the calculation of TSS ratios, when following error occurred: 

`
The following files found and to be read as junctions:
/home/heyj/temp/210713_integrated_deNovo_analysis_LongReadGFF_ShortReadDACSB_CAGEConsenus/STAR_mapping/AS-641779-LR-57123_R1SJ.out.tab
/home/heyj/temp/210713_integrated_deNovo_analysis_LongReadGFF_ShortReadDACSB_CAGEConsenus/STAR_mapping/AS-641795-LR-57123_R1SJ.out.tab
/home/heyj/temp/210713_integrated_deNovo_analysis_LongReadGFF_ShortReadDACSB_CAGEConsenus/STAR_mapping/AS-641787-LR-57123_R1SJ.out.tab
1422701 junctions read. 1644 junctions added to both strands because no strand information from STAR.
Running calculation of TSS ratio
Traceback (most recent call last):
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 2486, in <module>
    main()
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 2470, in main
    run(args)
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 1881, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 1553, in isoformClassification
    inside_bed, outside_bed = get_TSS_bed(corrGTF, chr_order)
  File "/home/heyj/tools/SQANTI3-4.1/utilities/short_reads.py", line 126, in get_TSS_bed
    strand=str(loc[2])
IndexError: list index out of range
`

I am not really sure what caused this problem, but I checked the STAR_mapping output files and they seem correct. Here an example of STAR_mapping/*out.tab:

chr1    8075461 8075554 2       2       1       78      4       54
chr1    8075753 8080645 2       2       1       4       1       42
chr1    8075753 8082452 2       2       1       9       4       55
chr1    8075753 8086217 2       2       1       71      12      37
chr1    8082528 8085563 2       2       1       3       0       54
chr1    8082528 8086217 2       2       1       3       0       39
chr1    8088713 8089193 0       0       1       3       0       50
chr1    8089418 8114365 1       1       1       1       0       18
chr1    8093500 8173424 1       1       1       2       1       22
chr1    8093500 8181533 1       1       1       2       0       54
chr1    8104082 8125526 2       2       1       1       0       46
chr1    8111375 8121243 2       2       1       2       0       28

Would be grateful for your support.

Best regards,

Joschka

**Comment by HeyLifeHD** [comment]
I dont know if this error is related, but I also face a problem when running the pipeline without the short read information:


**** TSS ratio will not be calculated since SR information was not provided
**** Reading CAGE Peak data.
**** Reading PolyA motif list.
**** Performing Classification of Isoforms....
Number of classified isoforms: 111319
Traceback (most recent call last):
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 2486, in <module>
    main()
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 2470, in main
    run(args)
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 1885, in run
    write_collapsed_GFF_with_CDS(isoforms_info, corrGTF, corrGTF+'.cds.gff')
  File "/home/heyj/tools/SQANTI3-4.1/sqanti3_qc.py", line 413, in write_collapsed_GFF_with_CDS
    for r in reader:
  File "/home/heyj/miniconda3/envs/SQANTI3.env/lib/python3.9/site-packages/cupcake-24.3.0-py3.9-linux-x86_64.egg/cupcake/io/GFF.py", line 408, in __next__
    return self.read()
  File "/home/heyj/miniconda3/envs/SQANTI3.env/lib/python3.9/site-packages/cupcake-24.3.0-py3.9-linux-x86_64.egg/cupcake/io/GFF.py", line 592, in read
    rec = gmapRecord(chr, coverage=None, identity=None, strand=strand, seqid=seqid, geneid=geneid)
  File "/home/heyj/miniconda3/envs/SQANTI3.env/lib/python3.9/site-packages/cupcake-24.3.0-py3.9-linux-x86_64.egg/cupcake/io/GFF.py", line 324, in __init__
    assert strand == '+' or strand == '-'
AssertionError


Thanks in advance.

**Comment by FJPardoPalacios** [comment]
Hi Joshcka,

In the last error message it seems that the strand of the transcripts is not defined as "+" or "-". Could you check that in your input GTF? SQANTI3 always needs a strand to characterize a transcript.

Best,
Fran

**Comment by HeyLifeHD** [comment]
Dear Fran,

it seems if the strand information is present. Is gff-version2 fine?

#gff-version 2
#pipeline-nanopore-ref-isoforms: stringtie
chrM    StringTie       transcript      206     409     1000    -       .       gene_id "STR.0..1"; transcript_id "STR.0..1.1"; cov "2734.240234"; FPKM "16920.468750"; TPM "19302.474609";
chrM    StringTie       exon    206     409     1000    -       .       gene_id "STR.0..1"; transcript_id "STR.0..1.1"; exon_number "1"; cov "2734.240234";
chrM    StringTie       transcript      648     1601    1000    +       .       gene_id "STR.0..2"; transcript_id "STR.0..2.1"; cov "4149.361816"; FPKM "25677.751953"; TPM "29292.580078";
chrM    StringTie       exon    648     1601    1000    +       .       gene_id "STR.0..2"; transcript_id "STR.0..2.1"; exon_number "1"; cov "4149.361816";
chrM    StringTie       transcript      1602    1670    1000    +       .       gene_id "STR.0..3"; transcript_id "STR.0..3.1"; reference_id "ENST00000387342.1"; ref_gene_id "ENSG00000210077.1";


Thanks for the quick response.

Best,


Joschka

**Comment by FJPardoPalacios** [comment]
Seems fine, but maybe there are some transcripts with a "." in the column strand (as far as I know, StringTie does it #62). Could you please check it with the following command?

`cut -f7 your_input_GTF.gtf | sort | uniq -c` 

That should tell us how many transcripts were associated to the + and - strand, and if there is any ".". SQANTI3 doesn't accept any transcript with an unknown strand and it will break if it finds one.

Bests,
Fran

**Comment by HeyLifeHD** [comment]
You were right. There were actually some unclassified "*" transcripts in the gtf. I removed them and restarted the pipeline in a fresh working directory. Hope it runs through this time. Thanks for your help.

Best,
Joschka


p.s. was just a bit suprised that this error occurs that late in the pipeline. ORF prediction and so on seems to have worked with the unclassified transcripts.
