### ISSUE TITLE
increase NMD call distance threshold?

### ISSUE THREAD

**Issue by kmattioli** [ConesaLab/SQANTI3#80]
Hello,

Thank you for all of your work with SQANTI! I am wondering if perhaps the current `predicted_NMD` threshold is too stringent. The `sqanti3_qc.py` contains the following code:

```
if isoform_hit.CDS_genomic_end!='NA':
    # NMD detection
    # if + strand, see if CDS stop is before the last junction
    if len(rec.junctions) > 0:
        if rec.strand == '+':
            dist_to_last_junc = isoform_hit.CDS_genomic_end - rec.junctions[-1][0]
        else: # - strand
            dist_to_last_junc = rec.junctions[0][1] - isoform_hit.CDS_genomic_end
        isoform_hit.is_NMD = "TRUE" if dist_to_last_junc < 0 else "FALSE"
```

which I believe means any isoform within a junction downstream of the stop codon is marked NMD. 

However, we know that if the downstream junction is within ~50bp of the stop codon, the final exon junction complex can still be kicked off during an initial round of translation, and thus NMD is not triggered. (Source [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5045715/), see Figure 2, which only shows a ~2% rate of NMD when the final junction is within 50 nt compared to a ~85% rate of NMD when the final junction is further than that. Also covered in [this review](https://www.nature.com/articles/s41580-019-0126-2), which states "Should translation terminate at a premature termination codon (PTC) that is located ≥50–55 nt upstream of an exon–exon junction, the ribosome will not dislocate the EJC, which is effectively in the 3′ UTR." Of course, NMD is complicated, but the ~50bp rule seems to work pretty well.) 

Given this, I wonder if it would be prudent to update the SQANTI rule such that it is only `TRUE` if `dist_to_last_junc < -50`?

(FWIW, I noticed because I initially filtered my transcripts for `predicted_NMD = FALSE`, but saw that some isoforms I expect to see are filtered out here, and would not be if the above rule were amended).

**Comment by FJPardoPalacios** [comment]
Wow! Thank you very much for the insight. 

Of course, I will take a look at the papers you cited and I'll implement it. Let me mark this issue as an "enhancement" and I will close it when the changes in the code are done.

**Comment by FJPardoPalacios** [comment]
Done!

Thank you
