### ISSUE TITLE
 SQANTI3 Quality Control  Failes to Recongize STAR's SJ.out

### ISSUE THREAD

**Issue by sum732** [ConesaLab/SQANTI3#81]
Hello,

I have short read data including SJ.out.tab from STAR and I am including this coverage information while running `sqanti3_qc.py`. I am shown following error:

``` 
R scripting front-end version 4.1.1 (2021-08-10)
WARNING: ref annotation contains chromosomes not in genome: M

**** Parsing Isoforms....
Input pattern: /data/long_read_RNAseq/ShortRead_Data/Sample_2019_0456OU_OS_RP/analysis/star/Sample_2019_0456OU_OS_RP.SJ.out.tab.
The following files found and to be read as junctions:
/data/long_read_RNAseq/ShortRead_Data/Sample_2019_0456OU_OS_RP/analysis/star/Sample_2019_0456OU_OS_RP.SJ.out.tab
363206 junctions read. 0 junctions added to both strands because no strand information from STAR.
Traceback (most recent call last):
  File "/gpfs/fs1/home/Research/Programs/SQANTI3/SQANTI3-4.1/sqanti3_qc.py", line 2486, in <module>
    main()
  File "/gpfs/fs1/home/Research/Programs/SQANTI3/SQANTI3-4.1/sqanti3_qc.py", line 2470, in main
    run(args)
  File "/gpfs/fs1/home/Research/Programs/SQANTI3/SQANTI3-4.1/sqanti3_qc.py", line 1881, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/gpfs/fs1/home/Research/Programs/SQANTI3/SQANTI3-4.1/sqanti3_qc.py", line 1541, in isoformClassification
    for file in b:
  File "/gpfs/fs1/home/.conda/envs/SQANTI3.env/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```
Here is the command I had used:
`python ~/SQANTI3-4.1/sqanti3_qc.py ../CupCake/1_A01.Collapsed.collapsed.gff ../reference/gencode.v37.annotation.sorted.gtf ../reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa -c /data/long_read_RNAseq/star/OS_RP.SJ.out.tab --SR_bam /data/long_read_RNAseq/star/OS_RP.Aligned.sortedByCoord.out.bam --isoAnnotLite --gff3 /data/long_read_RNAseq/reference/tappAS/Homo_sapiens_GRCh38_Ensembl_86.gff3 -o Sqanti3_qc_1_A01 --report both`

Below I am showing random records for the SJ.out file:
| 5  | 1574290   | 1576178   | 2 | 2 | 1 | 2  | 2 | 1  |
|----|-----------|-----------|---|---|---|----|---|----|
| 11 | 105031281 | 105033063 | 2 | 2 | 1 | 4  | 0 | 32 |
| 3  | 123956116 | 123956739 | 2 | 2 | 1 | 1  | 0 | 17 |
| 1  | 23030635  | 23050386  | 1 | 1 | 1 | 44 | 2 | 50 |
| 10 | 91982226  | 91982586  | 1 | 1 | 1 | 49 | 0 | 50 |
| 11 | 61740593  | 61741161  | 1 | 1 | 1 | 9  | 0 | 39 |
| 7  | 44843355  | 44847441  | 2 | 2 | 1 | 0  | 5 | 1  |
| 9  | 77356841  | 77357691  | 1 | 1 | 1 | 1  | 0 | 17 |
| 20 | 34851317  | 34852154  | 2 | 2 | 1 | 14 | 2 | 44 |
| 14 | 104024681 | 104025563 | 1 | 1 | 1 | 6  | 2 | 33 |

The forth column contains strand information, so I am not sure why the error is given.
Your help will be much appreciated. 
Many Thanks in Advance
Deep

**Comment by FJPardoPalacios** [comment]
Hi @sum732 !

Sorry for the late response. I think that the problem is not related with the SJ.out.tab files, but with the `--SR_bam` argument. In order to feed SQANTI3 with those BAM files you have 2 options:
- Input the directory (not the BAM file) where the BAM files are. If there are several BAM files in that directory ALL will be used.
- Using a File Of File Names (.fofn) which is simply a text file with the path(s) of the BAM file(s), with one sample/replicate per line

SQANTI3 detected that your input for `--SR_bam` is not a directory and tried to read it as if it was a .fofn file, but it's not.

Bests,
Fran

**Comment by sum732** [comment]
Thanks Fran for responding with resolution. I did created a "File Of File Names" and gave the hard path to BAM file. 

Now I am shown following error message: 
```
**** Parsing Isoforms....
Input pattern: /data/long_read_RNAseq/ShortRead_Data/Sample_2019_0456OU_OS_RP/analysis/star/Sample_2019_0456OU_OS_RP.SJ.out.tab.
The following files found and to be read as junctions:
/data/long_read_RNAseq/ShortRead_Data/Sample_2019_0456OU_OS_RP/analysis/star/Sample_2019_0456OU_OS_RP.SJ.out.tab
363206 junctions read. 0 junctions added to both strands because no strand information from STAR.
Traceback (most recent call last):
  File "/home/Research/Programs/SQANTI3/SQANTI3-4.1/sqanti3_qc.py", line 2486, in <module>
    main()
  File "/home/Research/Programs/SQANTI3/SQANTI3-4.1/sqanti3_qc.py", line 2470, in main
    run(args)
  File "/home/Research/Programs/SQANTI3/SQANTI3-4.1/sqanti3_qc.py", line 1881, in run
    isoforms_info, ratio_TSS_dict = isoformClassification(args, isoforms_by_chr, refs_1exon_by_chr, refs_exons_by_chr, junctions_by_chr, junctions_by_gene, start_ends_by_gene, genome_dict, indelsJunc, orfDict, corrGTF)
  File "/home/Research/Programs/SQANTI3/SQANTI3-4.1/sqanti3_qc.py", line 1542, in isoformClassification
    bams.append(files)
UnboundLocalError: local variable 'files' referenced before assignment
```
Not sure about `0 junctions added to both strands because no strand information from STAR.`
The command is 
```
python ~/Research/Programs/SQANTI3/SQANTI3-4.1/sqanti3_qc.py ../CupCake/1_A01.Collapsed.collapsed.gff ../../../../reference/gencode.v37.annotation.sorted.gtf ../../../../reference/Homo_sapiens.GRCh38.dna.primary_assembly.fa -c /data/long_read_RNAseq/ShortRead_Data/Sample_2019_0456OU_OS_RP/analysis/star/Sample_2019_0456OU_OS_RP.SJ.out.tab --SR_bam Illumina_SJ_File.fofn --isoAnnotLite --gff3 /data/long_read_RNAseq/reference/tappAS/Homo_sapiens_GRCh38_Ensembl_86.gff3 -o Sqanti3_qc_1_A01 --report both ```

**Comment by FJPardoPalacios** [comment]
Hi!

That error is caused by a bug that was solved last week, sorry for that. Don't worry about the `0 junctions added to both strands because no strand information from STAR`, that's totally fine.

If you cloned the repository, please do `git pull` so you get the least updates in the code.

Fran

**Comment by sum732** [comment]
Thanks Fran, I had used the conda way to install packages. Will try with wget/git method and let you know. Appreciate the quick response. 
Since the short-read libraries are (reverse) stranded, for my better understanding could you please elaborate on why its okay for this message `0 junctions added to both strands because no strand information from STAR` to be reported and safely ignore.

**Comment by FJPardoPalacios** [comment]
There are some situations where STAR is not capable to define the strand on which the splice junction is detected. In those cases, the strand is set to "undefined". When parsing of the `SJ.out.tab` files, SQANTI3 doesn't want to miss SJs with "undefined" strands (since it is evidence of a SJ, we just don't know the strand), so it will record internally those SJs as if they were present in both strands.

In your case, this is not a problem for you since all the SJs that STAR detected were associated to the + or the - strand, which is great and you shouldn't worry about it :+1:
