### ISSUE TITLE
Error with --is_fusion

### ISSUE THREAD

**Issue by xiaonalu** [ConesaLab/SQANTI3#83]
Hi,
I received an error when I run the --is_fusion. May I ask any help to solve it? Thanks

Error in `$<-.data.frame`(`*tmp*`, SJ_type, value = "__SJ") : 
  replacement has 1 row, data has 0
Calls: $<- -> $<-.data.frame
Execution halted
Traceback (most recent call last):
  File "/SQANTI3-4.1/sqanti3_qc.py", line 2486, in <module>
    main()
  File "/SQANTI3-4.1/sqanti3_qc.py", line 2470, in main
    run(args)
  File "/SQANTI3-4.1/sqanti3_qc.py", line 2080, in run
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/conda_envs/SQANTI3.env/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/conda_envs/SQANTI3.env/
bin/Rscript /SQANTI3-4.1/utilities/SQANTI3_report.R /Iso2.fasta.fusion_classification.txt /Iso2.fasta.fusion_junctions.txt /Iso2.fasta.fusion.params.txt /SQANTI3-4.1/utilities False html' returned non-zero exit status 1.

**Comment by Magdoll** [comment]
Hi @xiaonalu 
I'm quite sure the reporting using HTML functionality is broken right now and pending fix. In the meantime, try using `--report pdf` and that should work just fine.

**Comment by FJPardoPalacios** [comment]
Hi @xiaonalu ,

My fault! As @Magdoll said, HTML functionality will break if `--is_fusion` is activated. I'll try to solve it asap, but in the meantime I would recommend you to run SQANTI3 with `--report pdf` argument.

Thank you!

**Comment by xiaonalu** [comment]
Ok. Thank you
