### ISSUE TITLE
No module named 'rt_switching'

### ISSUE THREAD

**Issue by xiaonalu** [ConesaLab/SQANTI3#84]
Hi,
when I ran the sqanti_qc.py, received below error:
File "sqanti3_qc.py", line 27, in <module> from rt_switching import rts
ModuleNotFoundError: No module named 'rt_switching'

Is this a module inside the install package? Thanks

**Comment by adrisede** [comment]
Hi, I am also getting this error when trying to run sqanti_qc.py, , but it's now on line 31 in <module> from rt_switching import rts ModuleNotFoundError: No module named 'rt_switching'.  How can I fix this?
