### ISSUE TITLE
intron retention

### ISSUE THREAD

**Issue by BeatrizdeToledo** [ConesaLab/SQANTI3#87]
Good afternoon,
I would like to know if is possible to retrieve in an easy way the coordinates of the intron retention "events".
Importantly, in some cases my novel transcript was classified as intron retention, and by looking at the structure in igv I could not tell where the intron retention occurred.
Also, how does the sqanti classifies a transcript that has both novel splice site and intron retention?
Thank you
Beatriz

**Comment by FJPardoPalacios** [comment]
Hi Beatriz,

If there's any novel splice site, the transcript should be catalogued as NNC. If, as you say, both novel splice site and an intron retention events occur in the same transcript, it should be catalogued as NNC subcategory `intron_retention`. SQANTI3 classifies any isoform as subcategory `intron_retention` if one exon of the evaluated transcript spans an entire intron present in the reference. 

Would it be possible to see the snapshot of IGV where this "intron retention" transcript does not look like a real intron retention? Please, add the track of the reference transcriptome that you used for SQANTI3.

Bests,
Fran

**Comment by aarzalluz** [comment]
Closing unless OP reopens to provide data for follow-up.
