### ISSUE TITLE
interpretation of saturation plot

### ISSUE THREAD

**Issue by xiaonalu** [ConesaLab/SQANTI3#88]
Hi,
I want to consult about the saturation plots. After running the sqantiQC, I received 4 "Saturation plot per structural category" with the subtitle "Minimum number of FL−reads required to call an isoform = 1/2/3/5". May I ask where these 1-5 number come from? will it changes according to any variables/sequencing depth? Thank you
Best
Xiaona

**Comment by aarzalluz** [comment]
Closing (unanswered).
