### ISSUE TITLE
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working

### ISSUE THREAD

**Issue by MatthiasLienhard** [ConesaLab/SQANTI3#9]
This warning appeared despite following exactly the recommended installation process.

**Comment by FJPardoPalacios** [comment]
It's totally normal and it should not produce any further error.
We are aware of it and as soon as we fix it, I'll close the issue.

Thank you!
