### ISSUE TITLE
No report was created after running sqanti3

### ISSUE THREAD

**Issue by Dongxu-Zheng** [ConesaLab/SQANTI3#90]
Hi, thanks for developing SQANTI3 for Isoseq data analysis! I have some issues with generating the report after running sqanti3_qc.py. I didn't get the report but other output files seem normal. The following is the ERROR information:

R scripting front-end version 4.1.1 (2021-08-10)
WARNING: output directory /exports/01.Project/02.Iso-seq/sqanti_output already exists. Overwriting!
FASTA index file /exports/01.Project/02.Iso-seq/reference/gencode.v38.transcripts.fa.fai created.
WARNING: ref annotation contains chromosomes not in genome: chr7,chr13,chr18,chrM,chr15,chr16,chr22,chr21,chr9,chr10,chr5,chr19,chrX,chr17,chr6,chrY,chr4,chr3,chr20,chr1,chr14,chr12,chr8,chr11,chr2

**** Parsing Isoforms....
**** RT-switching computation....
**** Reading Full-length read abundance files...
Single-sample PacBio FL count format detected.
Isoforms expression files not provided.
**** Writing output files....
**** Generating SQANTI3 report....
Loading required package: Biobase
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

    clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
    clusterExport, clusterMap, parApply, parCapply, parLapply,
    parLapplyLB, parRapply, parSapply, parSapplyLB

The following object is masked from ‘package:gridExtra’:

    combine

The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs

The following objects are masked from ‘package:base’:

    anyDuplicated, append, as.data.frame, basename, cbind, colnames,
    dirname, do.call, duplicated, eval, evalq, Filter, Find, get, grep,
    grepl, intersect, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
    union, unique, unsplit, which.max, which.min

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.

Loading required package: splines
Loading required package: Matrix

Attaching package: ‘Matrix’

The following object is masked from ‘package:reshape’:

    expand

Attaching package: ‘plyr’

The following objects are masked from ‘package:reshape’:

    rename, round_any

Attaching package: ‘plotly’

The following objects are masked from ‘package:plyr’:

    arrange, mutate, rename, summarise

The following object is masked from ‘package:reshape’:

    rename

The following object is masked from ‘package:ggplot2’:

    last_plot

The following object is masked from ‘package:stats’:

    filter

The following object is masked from ‘package:graphics’:

    layout

Attaching package: ‘dplyr’

The following objects are masked from ‘package:plyr’:

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize

The following object is masked from ‘package:Biobase’:

    combine

The following objects are masked from ‘package:BiocGenerics’:

    combine, intersect, setdiff, union

The following object is masked from ‘package:gridExtra’:

    combine

The following object is masked from ‘package:reshape’:

    rename

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
`summarise()` has grouped output by 'lenCat'. You can override using the `.groups` argument.
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning messages:
1: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
2: `guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Error in `[<-.data.frame`(`*tmp*`, which(is.na(x$polyA_motif)), "Coverage_PolyA",  :
  replacement has 1 row, data has 0
Calls: [<- -> [<-.data.frame
Execution halted
Traceback (most recent call last):
  File "/exports/humgen/dzheng/software/SQANTI3/SQANTI3/sqanti3_qc.py", line 2500, in <module>
    main()
  File "/exports/humgen/dzheng/software/SQANTI3/SQANTI3/sqanti3_qc.py", line 2483, in main
    run(args)
  File "/exports/humgen/dzheng/software/SQANTI3/SQANTI3/sqanti3_qc.py", line 2092, in run
    if subprocess.check_call(cmd, shell=True)!=0:
  File "/exports/humgen/dzheng/software/anaconda3/envs/SQANTI3.env/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/exports/anaconda3/envs/SQANTI3.env/bin/Rscript /exports/software/SQANTI3/SQANTI3/utilities/SQANTI3_report.R /exports/01.Project/02.Iso-seq/sqanti_output/0h_sqanti3_classification.txt /exports/01.Project/02.Iso-seq/sqanti_output/0h_sqanti3_junctions.txt /exports/01.Project/02.Iso-seq/sqanti_output/0h_sqanti3.params.txt /exports/software/SQANTI3/SQANTI3/utilities False both' returned non-zero exit status 1.

The Linux system is CentOS 8 and I used the developed version of SQANTI3.

Thanks for any suggestions and help!

Best,
Dongxu Zheng

**Comment by FJPardoPalacios** [comment]
Hi! 

I think that the key of your error is related with the second WARNING message:

`WARNING: ref annotation contains chromosomes not in genome: chr7,chr13,chr18,chrM,chr15,chr16,chr22,chr21,chr9,chr10,chr5,chr19,chrX,chr17,chr6,chrY,chr4,chr3,chr20,chr1,chr14,chr12,chr8,chr11,chr2`

Please, check if the IDs of the chromosomes in the reference genome match the IDs of the chromosomes in the reference GTF. Maybe you have a chromosome ">1" in your genome FASTA file and in your reference GTF it is called "chr1". If this is the case, please, modify your FASTA or your reference GTF so all the files used as input in SQANTI3 (reference genome, reference annotation and your isoforms, if they are in GTF format) are concordant. Then, re-run SQANTI3 and let's see if the issue persists.

Best,
Fran

**Comment by Dongxu-Zheng** [comment]
> Hi!
> 
> I think that the key of your error is related with the second WARNING message:
> 
> `WARNING: ref annotation contains chromosomes not in genome: chr7,chr13,chr18,chrM,chr15,chr16,chr22,chr21,chr9,chr10,chr5,chr19,chrX,chr17,chr6,chrY,chr4,chr3,chr20,chr1,chr14,chr12,chr8,chr11,chr2`
> 
> Please, check if the IDs of the chromosomes in the reference genome match the IDs of the chromosomes in the reference GTF. Maybe you have a chromosome ">1" in your genome FASTA file and in your reference GTF it is called "chr1". If this is the case, please, modify your FASTA or your reference GTF so all the files used as input in SQANTI3 (reference genome, reference annotation and your isoforms, if they are in GTF format) are concordant. Then, re-run SQANTI3 and let's see if the issue persists.
> 
> Best, Fran

Hi Fran,

Thanks for your quick reply! I used another reference genome and the matched annotation GTF. The problem is figured out! I can get the report in pdf and HTML now. Thank you!

Cheers,
Dongxu
