### ISSUE TITLE
What does SQANTI3 QC correct exactly?

### ISSUE THREAD

**Issue by bayraktar1** [ConesaLab/SQANTI3#97]
Hi,

After running sqanti3_qc.py, I noticed that that the results contain "corrected" in the name and I would like to know what sqanti3_qc.py corrects exactly.

I ran Sqanti3_qc.py separately with three different GTF files that were obtained by running FLAIR, TALON, and pipeline-nanopore-ref-isoforms with oxford nanopore direct RNA-seq data.

Only the minimum Input to SQANTI3 QC and the --force_id_ignore flag were used when running.

Thanks,

**Comment by FJPardoPalacios** [comment]
Hi!

The `_corrected` prefix is used to make clear that the sequences evaluated match the corresponding genome sequence, so they can be considered "genome corrected".

SQANTI can use a FASTA file with the sequences of the transcripts as input. It would map them against the genome, a GTF is created and then the sequences of those transcripts extracted. If there was, for instance, a SNP in any if those sequences, that SNP would be lost and it wouldn't be taken into account, for example, to determine if it is a coding or non coding isoform. 

As you used a GTF as input, it can be understood as already "genome corrected" (there is no information about the sequences of the isoforms, just their coordinates in the genome). In your case, this correction is not affecting anything.

Bests,
Fran

**Comment by bayraktar1** [comment]
Thank you very much!
