### ISSUE TITLE
Can't use an expression matrix as input for -- expression when running Squanti3 quality control

### ISSUE THREAD

**Issue by Dongxu-Zheng** [ConesaLab/SQANTI3#99]
Hi, I would like to use short read sequencing data as input when running SQANTI3 Quality Control. According to the tutorial,  it said: "There is also the possibility of using as input an expression matrix, as a tab-separated file, in which each transcript will be a row and each sample/replicate a column". I have four short read RNA-seq data(2 control and 2 treated) and I used kallisto to get the abundance of each sample from the transcriptome generated by my Pacbio Isoseq data. Then I merged all 4 abundance .tsv files together. Each row is a PB transcript and each column represents a sample. However, I failed to use this matrix as the input for running Squanti3 quality control. It seems that the Squanti3 quality control script only accepts Kallisto tsv format. I was wondering if there is any way I can use my own expression matrix? Or maybe I can merge them directly with the output from squanti3 quality control, for instance, the classification file. Many thanks for any suggestions or help!

Best,
Dongxu Zheng

**Comment by aarzalluz** [comment]
Hi @Dongxu-Zheng,

We cannot know for sure until we see the first few lines of your expression matrix or an error message, but I will try to give you some pointers.

In the SQANTI3 documentation, the full paragraph reads:

> There is also the possibility of using as input an expression matrix, as a tab-separated file, in which each transcript will be a row and each sample/replicate a column. Transcript idientifiers must be the same than the ones described in the Long read-defined transcriptome used as input and the name for that column must be ID. The rest of the column names in the header should be the sample/replicate identifier.

Make sure that you have named the transcript identifier column as **ID**, and that you have one named column per sample/replicate with sample-specififc headers.

Alternatively, you may provide one kallisto abundance.tsv file per sample. The info is in the following paragraph of [the SQ3 Wiki](https://github.com/ConesaLab/SQANTI3/wiki/Running-SQANTI3-Quality-Control):

> Use --expression to optionally provide short read expression data. Two formats are supported if you input one file per sample. In any case, you can provide several expression data files as a chain of comma-separated paths or by providing a directory were ONLY expression data is present. If more than one file is provided, iso_exp column will represent the average expression value across all the files.


Best,

Ángeles

**Comment by aarzalluz** [comment]
Closing unless OP reopens.
